### ISSUE TITLE
unbounded malloc panic

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1257]
mars ran out of memory again, this time it looks like protobuf is trying to eat a lot of memory. Not sure if this is our bug, or a protobuf bug (gasp!)

relevant stack:
```
goroutine 28434575 [running]:
runtime.switchtoM()
        /home/whyrusleeping/go/src/runtime/asm_amd64.s:198 fp=0xc20d98f550 sp=0xc20d98f548
runtime.mallocgc(0x211c000, 0x0, 0xc200000003, 0x1a7bffb)
        /home/whyrusleeping/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc20d98f600 sp=0xc20d98f550
runtime.rawmem(0x211c000, 0x211c000)
        /home/whyrusleeping/go/src/runtime/malloc.go:371 +0x39 fp=0xc20d98f628 sp=0xc20d98f600
runtime.growslice(0xa5d6e0, 0xc2357c4000, 0x1a7bffb, 0x1a7c000, 0x3, 0x0, 0x0, 0x0)
        /home/whyrusleeping/go/src/runtime/slice.go:83 +0x237 fp=0xc20d98f688 sp=0xc20d98f628
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto.(*Buffer).EncodeRawBytes(0xc20da55e10, 0xc22df6da50, 0x8, 0x8, 0x0, 0x0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto/encode.go:184 +0xc0 fp=0xc20d98f700 sp=0xc20d98f688
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto.(*Buffer).enc_slice_slice_byte(0xc20da55e10, 0xc209cb7540, 0xc22df67180, 0x0, 0x0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto/encode.go:770 +0x272 fp=0xc20d98f7b8 sp=0xc20d98f700
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto.(*Buffer).enc_struct(0xc20da55e10, 0xc2080e9ce0, 0xc22df67180, 0x0, 0x0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto/encode.go:957 +0x13b fp=0xc20d98f8d0 sp=0xc20d98f7b8
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto.(*Buffer).enc_len_struct(0xc20da55e10, 0xc2080e9ce0, 0xc22df67180, 0xc20d98f9f0, 0x0, 0x0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto/encode.go:1005 +0x184 fp=0xc20d98f990 sp=0xc20d98f8d0
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto.(*Buffer).enc_slice_struct_message(0xc20da55e10, 0xc209cb7900, 0xc20a721880, 0x0, 0x0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto/encode.go:834 +0x633 fp=0xc20d98fac0 sp=0xc20d98f990
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto.(*Buffer).enc_struct(0xc20da55e10, 0xc2080e99d0, 0xc20a721880, 0x0, 0x0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto/encode.go:957 +0x13b fp=0xc20d98fbd8 sp=0xc20d98fac0
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto.(*Buffer).Marshal(0xc20da55e10, 0x7f5d41b5ffa8, 0xc20a721880, 0x0, 0x0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto/encode.go:250 +0x350 fp=0xc20d98fcc0 sp=0xc20d98fbd8
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto.Marshal(0x7f5d41b5ffa8, 0xc20a721880, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/proto/encode.go:219 +0x1a7 fp=0xc20d98fd50 sp=0xc20d98fcc0
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/io.(*varintWriter).WriteMsg(0xc219c0c840, 0x7f5d41b5ffa8, 0xc20a721880, 0x0, 0x0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/gogo/protobuf/io/varint.go:67 +0x333 fp=0xc20d98fde8 sp=0xc20d98fd50
github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).handleNewMessage(0xc20a4a6750, 0x7f5d41b5fb98, 0xc219c0c5c0)
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:62 +0xa6e fp=0xc20d98ffc8 sp=0xc20d98fde8
runtime.goexit()
        /home/whyrusleeping/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20d98ffd0 sp=0xc20d98ffc8
created by github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).handleNewStream
        /home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:18 +0x46
```

**Comment by jbenet** [comment]
Probably ours. Huge varint? Random input to what we think is a varint?



—

**Comment by whyrusleeping** [comment]
this is from an outgoing message. something being returned from the dht stream handler. I have no idea how this could be our bug.

**Comment by whyrusleeping** [comment]
@gogo this doesnt look like a gogoprotobuf bug to you does it?

**Comment by whyrusleeping** [comment]
mars hit this again: http://gateway.ipfs.io/ipfs/QmcYKb9JakQAnorbuu5fyG9hgxM6kzH2MMGdnS7h79QL5C

(ctrl + f fatal error)

**Comment by whyrusleeping** [comment]
ran into this again, looked at a little closer, and i'm more confident that its our bug. The allocation is only 34MB. So the DHT is returning a 34MB record,  this could be too many addresses associated with a given peer, too many provider records for a single key, or maybe someone is just storing a 34MB DHT record, and retreiving it...

**Comment by whyrusleeping** [comment]
okay, so i've ruled out a 34MB dht record, our max message size is hard limited at 4MB. So i'm going to look at adding something around limiting address numbers and provider counts

**Comment by jbenet** [comment]
We still need to do the fix where we only add an own observed address if we've seen it _twice_. That will kill symmetric NAT addrs.



—

**Comment by jbenet** [comment]
> We still need to do the fix where we only add an own observed address if we've seen it _twice_. That will kill symmetric NAT addrs.

did this in aad700b

**Comment by jbenet** [comment]
> okay, so i've ruled out a 34MB dht record, our max message size is hard limited at 4MB. So i'm going to look at adding something around limiting address numbers and provider counts

@whyrusleeping we should still limit the protobuf allocation. the protobuf stream thing should have a max too

**Comment by whyrusleeping** [comment]
the issue i was seeing here was fixed in https://github.com/ipfs/go-ipfs/pull/1315
