### ISSUE TITLE
very strange panic in merkledag tests

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1283]
was running the tests locally and got this, i think its in merkledag,not certain which test though

```
> beep
data: beep
links:
encoded: [10 4 98 101 101 112]
hash: [18 32 193 59 112 166 232 16 218 229 145 229 2 151 79 99 36 226 159 180 250 165 85 42 247 155 206 83 86 22 119 201 126 49]
key:  QmbLwxt77hfvK1o9WA13VBvkV9gvmEK2k8SDZbVaUMZZi8
n.Stat correct: NodeStat{NumLinks: 0, BlockSize: 6, LinksSize: 2, DataSize: 4, CumulativeSize: 6}
> boop
data: boop
links:
encoded: [10 4 98 111 111 112]
hash: [18 32 33 156 63 214 215 143 203 71 241 112 76 170 231 16 224 83 17 164 57 74 202 132 23 167 48 93 108 225 221 217 126 241]
key:  QmQbrML2cXZoNNC1DrAXxZis9Y9kSBXuqRjs96WjYRWwXe
n.Stat correct: NodeStat{NumLinks: 0, BlockSize: 6, LinksSize: 2, DataSize: 4, CumulativeSize: 6}
> beep boop
data: beep boop
links:
- beep-link 6 [18 32 193 59 112 166 232 16 218 229 145 229 2 151 79 99 36 226 159 180 250 165 85 42 247 155 206 83 86 22 119 201 126 49]
- boop-link 6 [18 32 33 156 63 214 215 143 203 71 241 112 76 170 231 16 224 83 17 164 57 74 202 132 23 167 48 93 108 225 221 217 126 241]
encoded: [18 49 10 34 18 32 193 59 112 166 232 16 218 229 145 229 2 151 79 99 36 226 159 180 250 165 85 42 247 155 206 83 86 22 119 201 126 49 18 9 98 101 101 112 45 108 105 110 107 24 6 18 49 10 34 18 32 33 156 63 214 215 143 203 71 241 112 76 170 231 16 224 83 17 164 57 74 202 132 23 167 48 93 108 225 221 217 126 241 18 9 98 111 111 112 45 108 105 110 107 24 6 10 9 98 101 101 112 32 98 111 111 112]
hash: [18 32 232 124 23 19 12 4 210 187 6 15 116 26 216 22 243 100 59 112 164 221 65 115 156 142 201 186 117 182 144 21 14 191]
key:  QmdzB3MPwM8hrJoyuJzKAbF2nDbtQN2R2vD1oTjmki5SAa
n.Stat correct: NodeStat{NumLinks: 2, BlockSize: 113, LinksSize: 104, DataSize: 9, CumulativeSize: 125}
unexpected fault address 0xc20805a300
fatal error: fault
[signal 0xb code=0x2 addr=0xc20805a300 pc=0xc20805a300]

goroutine 8 [running]:
runtime.gothrow(0x8759a0, 0x5)
	/home/whyrusleeping/go/src/runtime/panic.go:503 +0x8e fp=0xc208069988 sp=0xc208069970
runtime.sigpanic()
	/home/whyrusleeping/go/src/runtime/sigpanic_unix.go:29 +0x265 fp=0xc2080699d8 sp=0xc208069988
created by testing.RunTests
	/home/whyrusleeping/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x94b950, 0xaae220, 0x3, 0x3, 0x407c01)
	/home/whyrusleeping/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20802ebe0, 0xaba980)
	/home/whyrusleeping/go/src/testing/testing.go:485 +0x6c
main.main()
	github.com/ipfs/go-ipfs/merkledag/_test/_testmain.go:58 +0x1d5

goroutine 5 [syscall]:
os/signal.loop()
	/home/whyrusleeping/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/home/whyrusleeping/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [chan receive]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/pubsub.(*PubSub).start(0xc20808eb50)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/pubsub/pubsub.go:119 +0xcd
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/pubsub.New
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/pubsub/pubsub.go:43 +0x97

goroutine 10 [chan receive]:
github.com/ipfs/go-ipfs/exchange/bitswap.func·002()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/bitswap.go:75 +0x65
created by github.com/ipfs/go-ipfs/exchange/bitswap.New
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/bitswap.go:77 +0x26e

goroutine 11 [chan receive]:
github.com/ipfs/go-ipfs/exchange/bitswap.func·003()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/bitswap.go:79 +0x65
created by github.com/ipfs/go-ipfs/exchange/bitswap.New
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/bitswap.go:81 +0x2f2

goroutine 12 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap/decision.(*Engine).nextEnvelope(0xc20802e370, 0x7f2f813b08c8, 0xc208062f80, 0x1, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/decision/engine.go:136 +0x3b5
github.com/ipfs/go-ipfs/exchange/bitswap/decision.(*Engine).taskWorker(0xc20802e370, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/decision/engine.go:120 +0x16d
created by github.com/ipfs/go-ipfs/exchange/bitswap/decision.NewEngine
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/decision/engine.go:95 +0x1c8

goroutine 15 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).clientWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:142 +0x894
github.com/ipfs/go-ipfs/exchange/bitswap.func·012(0x7f2f813aff00, 0xc208076080)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:34 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 18 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).taskWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:68 +0x502
github.com/ipfs/go-ipfs/exchange/bitswap.func·013(0x7f2f813aff00, 0xc208076180)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:40 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 21 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).taskWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:66 +0x551
github.com/ipfs/go-ipfs/exchange/bitswap.func·013(0x7f2f813aff00, 0xc208076280)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:40 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 24 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).taskWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:66 +0x551
github.com/ipfs/go-ipfs/exchange/bitswap.func·013(0x7f2f813aff00, 0xc208076380)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:40 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 27 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).taskWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:66 +0x551
github.com/ipfs/go-ipfs/exchange/bitswap.func·013(0x7f2f813aff00, 0xc208076480)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:40 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 30 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).taskWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:66 +0x551
github.com/ipfs/go-ipfs/exchange/bitswap.func·013(0x7f2f813aff00, 0xc208076580)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:40 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 33 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).taskWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:66 +0x551
github.com/ipfs/go-ipfs/exchange/bitswap.func·013(0x7f2f813aff00, 0xc208076780)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:40 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 36 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).taskWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:66 +0x551
github.com/ipfs/go-ipfs/exchange/bitswap.func·013(0x7f2f813aff00, 0xc208076880)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:40 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 39 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).taskWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:66 +0x551
github.com/ipfs/go-ipfs/exchange/bitswap.func·013(0x7f2f813aff00, 0xc208076980)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:40 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 42 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).rebroadcastWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:187 +0x3d6
github.com/ipfs/go-ipfs/exchange/bitswap.func·014(0x7f2f813aff00, 0xc208076b80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:46 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 45 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).provideCollector(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:112 +0x567
github.com/ipfs/go-ipfs/exchange/bitswap.func·015(0x7f2f813aff00, 0xc208076c80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:50 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 48 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).provideWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:87 +0x401
github.com/ipfs/go-ipfs/exchange/bitswap.func·016(0x7f2f813aff00, 0xc208076d80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:58 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 51 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).provideWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:87 +0x401
github.com/ipfs/go-ipfs/exchange/bitswap.func·016(0x7f2f813aff00, 0xc208076e80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:58 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 54 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).provideWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:87 +0x401
github.com/ipfs/go-ipfs/exchange/bitswap.func·016(0x7f2f813aff00, 0xc208076f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:58 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 57 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).provideWorker(0xc208070090, 0x7f2f813b08c8, 0xc208062f80)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:87 +0x401
github.com/ipfs/go-ipfs/exchange/bitswap.func·016(0x7f2f813aff00, 0xc208077080)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:58 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

goroutine 58 [chan receive]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/pubsub.(*PubSub).start(0xc20808e150)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/pubsub/pubsub.go:119 +0xcd
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/pubsub.New
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/briantigerchow/pubsub/pubsub.go:43 +0x97

goroutine 59 [chan receive]:
github.com/ipfs/go-ipfs/exchange/bitswap.func·002()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/bitswap.go:75 +0x65
created by github.com/ipfs/go-ipfs/exchange/bitswap.New
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/bitswap.go:77 +0x26e

goroutine 60 [chan receive]:
github.com/ipfs/go-ipfs/exchange/bitswap.func·003()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/bitswap.go:79 +0x65
created by github.com/ipfs/go-ipfs/exchange/bitswap.New
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/bitswap.go:81 +0x2f2

goroutine 61 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap/decision.(*Engine).nextEnvelope(0xc20802e410, 0x7f2f813b08c8, 0xc2080628c0, 0x1, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/decision/engine.go:136 +0x3b5
github.com/ipfs/go-ipfs/exchange/bitswap/decision.(*Engine).taskWorker(0xc20802e410, 0x7f2f813b08c8, 0xc2080628c0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/decision/engine.go:120 +0x16d
created by github.com/ipfs/go-ipfs/exchange/bitswap/decision.NewEngine
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/decision/engine.go:95 +0x1c8

goroutine 64 [select]:
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).clientWorker(0xc2080702d0, 0x7f2f813b08c8, 0xc2080628c0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:142 +0x894
github.com/ipfs/go-ipfs/exchange/bitswap.func·012(0x7f2f813aff00, 0xc208077200)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:34 +0x37
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

```

**Comment by whyrusleeping** [comment]
havent seen in a while
