### ISSUE TITLE
weird goroutine hang

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1358]
This goroutine was found in mars' out of memory stack dump. Something really weird is going on here.

```
goroutine 34095098 [select, 2677 minutes]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux.(*Session).OpenStream(0xc20cc48000, 0xc20fd52d80, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/hashicorp/yamux/session.go:145 +0x3c7
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/transport/yamux.(*conn).OpenStream(0xc20cc48000, 0x0, 0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/transport/yamux/yamux.go:48 +0x4c
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.(*Swarm).createStream(0xc20a03bad0, 0xc20d9b72d0, 0xc20d9b72d0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/conn.go:216 +0x59
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.(*Swarm).NewStreamWithConn(0xc20a03bad0, 0xc20d9b72d0, 0x1, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go:306 +0x541
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.(*Swarm).newStreamSelectConn(0xc20a03bad0, 0xf0a620, 0xc20c6357c0, 0x1, 0x1, 0x1, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go:251 +0x1ac
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.(*Swarm).NewStreamWithGroup(0xc20a03bad0, 0xc8e120, 0xc213d3e340, 0xc213d3e340, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go:273 +0xb6
github.com/ipfs/go-ipfs/p2p/net/swarm.(*Swarm).NewStreamWithPeer(0xc20a04d810, 0xc20a84de60, 0x22, 0xc212afe2c0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/p2p/net/swarm/swarm.go:164 +0x371
github.com/ipfs/go-ipfs/p2p/net/swarm.(*Network).NewStream(0xc20a04d810, 0xc20a84de60, 0x22, 0x0, 0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/p2p/net/swarm/swarm_net.go:137 +0x1bf
github.com/ipfs/go-ipfs/p2p/host/basic.(*BasicHost).NewStream(0xc20a065860, 0xd5c930, 0x9, 0xc20a84de60, 0x22, 0x0, 0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/p2p/host/basic/basic_host.go:156 +0xa9
github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).sendRequest(0xc20a058750, 0x7f20a2606e00, 0xc20ef9ed40, 0xc20a84de60, 0x22, 0xc210bd0310, 0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:75 +0x1ac
github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).getValueSingle(0xc20a058750, 0x7f20a2606e00, 0xc20ef9ed40, 0xc20a84de60, 0x22, 0xc212383ec0, 0x26, 0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/routing/dht/dht.go:211 +0x28e
github.com/ipfs/go-ipfs/routing/dht.(*IpfsDHT).getValueOrPeers(0xc20a058750, 0x7f20a2606e00, 0xc20ef9ed40, 0xc20a84de60, 0x22, 0xc212383ec0, 0x26, 0x0, 0x0, 0x0, ...)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/routing/dht/dht.go:176 +0xe1
github.com/ipfs/go-ipfs/routing/dht.func·018(0x7f20a2606e00, 0xc20ef9ed40, 0xc20a84de60, 0x22, 0x1, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/routing/dht/routing.go:107 +0x13d
github.com/ipfs/go-ipfs/routing/dht.(*dhtQueryRunner).queryPeer(0xc20eea2d80, 0x7f20a2604a10, 0xc20caac500, 0xc20a84de60, 0x22)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/routing/dht/query.go:254 +0x7f1
github.com/ipfs/go-ipfs/routing/dht.func·015(0x7f20a2604a10, 0xc20caac500)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/routing/dht/query.go:198 +0x4b
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3
```

**Comment by jbenet** [comment]
@whyrusleeping what's the weird part?

**Comment by whyrusleeping** [comment]
OpenStream hanging for 2677 minutes.

**Comment by jbenet** [comment]
Hm. Wonder if conn was fully dead or not. (Ie keepalives or not)

**Comment by whyrusleeping** [comment]
was likely utp or yamux
