### ISSUE TITLE
panic on killing daemon

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1401]
The bootstrap routine seems to try and access the repo after its closed when you ctrl+c the daemon. woo panics!

```
goroutine 10134 [running]:
github.com/ipfs/go-ipfs/repo/fsrepo.(*FSRepo).Config(0xc2080aa150, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/repo/fsrepo/fsrepo.go:423 +0xab
github.com/ipfs/go-ipfs/repo.(*ref).Config(0xc2080724b0, 0x0)
	<autogenerated>:7 +0x57
github.com/ipfs/go-ipfs/core.(*IpfsNode).loadBootstrapPeers(0xc20805c000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/core/core.go:457 +0x7e
github.com/ipfs/go-ipfs/core.func·009(0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/core/core.go:405 +0x5b
github.com/ipfs/go-ipfs/core.bootstrapRound(0x7f0e789f6848, 0xc208bb33e0, 0x7f0e789f50e8, 0xc208e16fc0, 0x4, 0x6fc23ac00, 0x2540be400, 0xc208bce800, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/core/bootstrap.go:118 +0xcc
github.com/ipfs/go-ipfs/core.func·002(0x7f0e789d4240, 0xc208523c00)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/core/bootstrap.go:85 +0x263
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·005()
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:113 +0x3f3

```

**Comment by Kubuxu** [comment]
I think it isn't issue any longer.
