### ISSUE TITLE
go test error in TestConcurentWrites: slice bounds out of range

### ISSUE THREAD

**Issue by chriscool** [ipfs/go-ipfs#1411]
I sometimes get the following error:

```
ok      github.com/ipfs/go-ipfs/exchange/reprovide      0.202s
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
Publishing!
--- FAIL: TestConcurrentWrites (109.97s)
        ipns_test.go:65: close /tmp/fusetest208938457/local/3FILE189: input/output error
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 639 [running]:
testing.func·006()
        /usr/local/go/src/testing/testing.go:441 +0x181
github.com/ipfs/go-ipfs/fuse/ipns.verifyFile(0xc20e086990, 0xc211b1f5c0, 0x25, 0x0, 0x0, 0x0)
        /home/christian/gocode/src/github.com/ipfs/go-ipfs/fuse/ipns/ipns_test.go:86 +0x4f3
github.com/ipfs/go-ipfs/fuse/ipns.TestConcurrentWrites(0xc20e086990)
        /home/christian/gocode/src/github.com/ipfs/go-ipfs/fuse/ipns/ipns_test.go:363 +0x6ab
testing.tRunner(0xc20e086990, 0xe2c0a8)
        /usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0xc13268, 0xe2c000, 0xa, 0xa, 0xc207ffdf01)
        /usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208036780, 0xe385a0)
```

It looks like the following line is not safe:

https://github.com/ipfs/go-ipfs/blob/master/fuse/ipns/ipns_test.go#L86

**Comment by jbenet** [comment]
yeah, that's right. it would happen if the file contents are _longer_ than the data (definitely an error, but shouldnt panic). Should do:

```go
		if offset+n > len(data) {
			t.Fatal("Data not equal")
		}
		if !bytes.Equal(buf[:n], data[offset:offset+n]) {
			t.Fatal("Data not equal")
		}
```
or something.

Looking at the whole function:
- [ ] https://github.com/ipfs/go-ipfs/blob/master/fuse/ipns/ipns_test.go#L82 seems incorrect, this may be `io.EOF` if `n < len(buf)`.

**Comment by chriscool** [comment]
Ok, thanks I will send a PR.
