### ISSUE TITLE
panic on kill during ipfs daemon init

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1637]
```
Initializing daemon...
^C
Received interrupt signal, shutting down...
Swarm listening on /ip4/83.150.19.162/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
panic: repo is closed

goroutine 371 [running]:
github.com/ipfs/go-ipfs/repo/fsrepo.(*FSRepo).Config(0xc208030c40, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/repo/fsrepo/fsrepo.go:463 +0xab
github.com/ipfs/go-ipfs/repo.(*ref).Config(0xc208083680, 0xc209bac000)
	<autogenerated>:8 +0x57
github.com/ipfs/go-ipfs/core/corehttp.func·001(0xc208100580, 0x10a6ce0, 0xc20996c048, 0xc20a93c030, 0x10add70, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/core/corehttp/commands.go:111 +0x194
github.com/ipfs/go-ipfs/core/corehttp.makeHandler(0xc208100580, 0x10a6ce0, 0xc20996c048, 0xc20a881800, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/core/corehttp/corehttp.go:35 +0x16d
github.com/ipfs/go-ipfs/core/corehttp.Serve(0xc208100580, 0x10a6ce0, 0xc20996c048, 0xc20a881800, 0x8, 0x8, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/core/corehttp/corehttp.go:68 +0xcc
main.func·008()
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:366 +0x9e
created by main.serveHTTPApi
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:368 +0x13cf

goroutine 1 [runnable]:
syscall.Syscall(0x68, 0x7, 0xc20a82600c, 0x10, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/asm_darwin_amd64.s:20 +0x5
syscall.bind(0x7, 0xc20a82600c, 0xc200000010, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/zsyscall_darwin_amd64.go:54 +0x56
syscall.Bind(0x7, 0x1086848, 0xc20a826000, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/syscall/syscall_unix.go:190 +0x7f
net.(*netFD).listenStream(0xc209f181c0, 0x10867f8, 0xc20a942a80, 0x80, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/sock_posix.go:164 +0x130
net.socket(0xc209eda30c, 0x4, 0x2, 0x1, 0x0, 0x0, 0x10867f8, 0xc20a942a80, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/sock_posix.go:78 +0x297
net.internetSocket(0xc209eda30c, 0x4, 0x10867f8, 0xc20a942a80, 0x0, 0x0, 0x0, 0xc200000000, 0x0, 0x1, ...)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/ipsock_posix.go:137 +0x148
net.ListenTCP(0xc209eda30c, 0x4, 0xc20a942a80, 0xc20a942a80, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/tcpsock_posix.go:294 +0x1a3
net.Listen(0xc209eda30c, 0x4, 0xc209eda340, 0xc, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/dial.go:266 +0x4ae
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-multiaddr-net.Listen(0x10846b8, 0xc20a83e000, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-multiaddr-net/net.go:236 +0x1d8
main.serveHTTPGateway(0x1086530, 0xc2081520c0, 0x0, 0x0, 0xc209b14060)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:405 +0x5da
main.daemonFunc(0x1086530, 0xc2081520c0, 0x10878a8, 0xc208030bd0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:260 +0xfd8
github.com/ipfs/go-ipfs/commands.(*Command).Call(0xeae320, 0x1086530, 0xc2081520c0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/commands/command.go:106 +0x457
main.callCommand(0x1086658, 0xc2080ee900, 0x1086530, 0xc2081520c0, 0xeae320, 0xea4ce0, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:338 +0x946
main.(*cmdInvocation).Run(0xc2080ee800, 0x1086658, 0xc2080ee900, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:181 +0x1fd
main.main()
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:149 +0x6b5

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 12 [chan receive]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/codahale/metrics.func·004()
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/codahale/metrics/metrics.go:321 +0x80
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/codahale/metrics.init·1
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/codahale/metrics/metrics.go:328 +0x76

goroutine 15 [chan receive]:
main.func·018()
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:537 +0xac
created by main.(*IntrHandler).Handle
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:542 +0x12e

goroutine 26 [chan receive]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-metrics.(*meterArbiter).tick(0xead820)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-metrics/meter.go:243 +0x52
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-metrics.NewMeter
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/whyrusleeping/go-metrics/meter.go:41 +0x1f7

goroutine 27 [select]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.(*Swarm).connGarbageCollect(0xc20801fad0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go:356 +0x1c9
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream.NewSwarm
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-peerstream/swarm.go:61 +0x289

goroutine 49 [select]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/fd/go-nat.DiscoverGateway(0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/fd/go-nat/nat.go:39 +0x2a6
github.com/ipfs/go-ipfs/p2p/nat.DiscoverNAT(0xc20996e000)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/p2p/nat/nat.go:35 +0x27
github.com/ipfs/go-ipfs/p2p/host/basic.func·004()
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/p2p/host/basic/natmgr.go:82 +0x49
created by github.com/ipfs/go-ipfs/p2p/host/basic.func·005
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/p2p/host/basic/natmgr.go:83 +0x10f

goroutine 50 [IO wait]:
net.(*pollDesc).Wait(0xc20999a060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20999a060, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc20999a000, 0xc209a7c000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x10840a0, 0xc209a4c8b8)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc20996c010, 0xc209a7c000, 0x800, 0x800, 0x451b0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc20996c010, 0xc209a7c000, 0x800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:82 +0x12e
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0xc209966020, 0xc2099a0000, 0x7d2b7500, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp/httpu/httpu.go:92 +0xba4
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp/ssdp.SSDPRawSearch(0xc209966020, 0xaf3050, 0x31, 0x2, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp/ssdp/ssdp.go:53 +0x654
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp.DiscoverDevices(0xaf3050, 0x31, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp/goupnp.go:55 +0x129
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/fd/go-nat.func·002()
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/fd/go-nat/upnp.go:21 +0x42
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/fd/go-nat.discoverUPNP_IG1
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/fd/go-nat/upnp.go:61 +0xb5

goroutine 51 [IO wait]:
net.(*pollDesc).Wait(0xc209998060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc209998060, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc209998000, 0xc209a7c800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x10840a0, 0xc209a4c8c8)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc20996a030, 0xc209a7c800, 0x800, 0x800, 0x451b0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc20996a030, 0xc209a7c800, 0x800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:82 +0x12e
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0xc2099703a0, 0xc20814e000, 0x7d2b7500, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp/httpu/httpu.go:92 +0xba4
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp/ssdp.SSDPRawSearch(0xc2099703a0, 0xaf30b0, 0x31, 0x2, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp/ssdp/ssdp.go:53 +0x654
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp.DiscoverDevices(0xaf30b0, 0x31, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/huin/goupnp/goupnp.go:55 +0x129
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/fd/go-nat.func·004()
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/fd/go-nat/upnp.go:70 +0x42
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/fd/go-nat.discoverUPNP_IG2
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/fd/go-nat/upnp.go:122 +0xb5

goroutine 106 [IO wait]:
net.(*pollDesc).Wait(0xc2099ce840, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2099ce840, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc2099ce7e0, 0xc2099e8000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x10840a0, 0xc2099726c8)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc208044700, 0xc2099e8000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc208044700, 0xc2099e8000, 0x10000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.2/libexec/src/net/udpsock_posix.go:82 +0x12e
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/cryptix/mdns.(*Server).recv(0xc2099e6cf0, 0xc208044700)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/cryptix/mdns/server.go:111 +0xcf
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/cryptix/mdns.NewServer
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/cryptix/mdns/server.go:74 +0x22f

goroutine 107 [chan receive]:
github.com/ipfs/go-ipfs/p2p/discovery.(*mdnsService).pollForEntries(0xc209955180)
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/p2p/discovery/mdns.go:115 +0x95
created by github.com/ipfs/go-ipfs/p2p/discovery.NewMdnsService
	/Users/jbenet/go/src/github.com/ipfs/go-ipfs/p2p/discovery/mdns.go:102 +0x5a2
```

**Comment by whyrusleeping** [comment]
duplicate of https://github.com/ipfs/go-ipfs/issues/1589

**Comment by jbenet** [comment]
ah.
