### ISSUE TITLE
panic in DHT tests

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#1639]
https://gist.github.com/whyrusleeping/1be3547b5d2fd0c243f3

Got this panic somewhere, either in `TestConnectCollision` or `TestPeriodicBootstrap`

**Comment by whyrusleeping** [comment]
@jbenet ran into this again.  It also appears that a good number of our tests leak goroutines, which exacerbates problems for subsequent tests.

**Comment by whyrusleeping** [comment]
again:
```
goroutine 77647 [running]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-multiaddr-net.FromNetAddr(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-multiaddr-net/convert.go:16 +0x5a
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-multiaddr-net.WrapNetConn(0x7f41025b7db8, 0xc820222700, 0x0, 0x0, 0x0, 0x0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/go-multiaddr-net/net.go:38 +0x26d
github.com/ipfs/go-ipfs/p2p/net/conn.(*Dialer).rawConnDial(0xc821aa6be0, 0x7f41025b7c90, 0xc821855980, 0x7f41025b1868, 0xc82214b8a0, 0xc820aa85d0, 0x22, 0x0, 0x0, 0x0, ...)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/p2p/net/conn/dial.go:132 +0x97e
github.com/ipfs/go-ipfs/p2p/net/conn.(*Dialer).Dial.func1(0xc821dd4c60, 0x7f41025b7c90, 0xc821855980, 0xc821aa6be0, 0x7f41025b1868, 0xc82214b8a0, 0xc820aa85d0, 0x22, 0xc820f86df0, 0xc820f86de0)
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/p2p/net/conn/dial.go:46 +0xc6
created by github.com/ipfs/go-ipfs/p2p/net/conn.(*Dialer).Dial
	/home/whyrusleeping/gopkg/src/github.com/ipfs/go-ipfs/p2p/net/conn/dial.go:77 +0x38a
```

**Comment by whyrusleeping** [comment]
this one has been resolved
