### ISSUE TITLE
tests: goproc race

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#1774]
```
panic: Process cannot add children after being closed
goroutine 48 [running]:
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).AddChild(0xc2080ee780, 0x2b66015f4ce8, 0xc2080ee900)
	/home/travis/gopath/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:86 +0x172
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go(0xc2080ee780, 0xc208020e60, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:110 +0x45d
github.com/ipfs/go-ipfs/exchange/bitswap.(*Bitswap).provideWorker(0xc20805e500, 0x2b66015f4ce8, 0xc2080ee540)
	/home/travis/gopath/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:113 +0x1cb
github.com/ipfs/go-ipfs/exchange/bitswap.*Bitswap.(github.com/ipfs/go-ipfs/exchange/bitswap.provideWorker)·fm(0x2b66015f4ce8, 0xc2080ee540)
	/home/travis/gopath/src/github.com/ipfs/go-ipfs/exchange/bitswap/workers.go:44 +0x3b
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.func·004()
	/home/travis/gopath/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:112 +0x70
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess.(*process).Go
	/home/travis/gopath/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/jbenet/goprocess/impl-mutex.go:115 +0x501
```

**Comment by jbenet** [comment]
https://travis-ci.org/ipfs/go-ipfs/jobs/83058891#L150

**Comment by rht** [comment]
Testing race conditions should be done periodically.

Running `go test -tags nofuse -race ./...` on https://github.com/ipfs/go-ipfs/commit/62cb6ebf8a8701201dd46a1eb79b2324c7051dcb

```
FAIL	github.com/ipfs/go-ipfs/exchange/bitswap	9.598s
FAIL	github.com/ipfs/go-ipfs/p2p/net/swarm	54.104s
FAIL	github.com/ipfs/go-ipfs/routing/dht	1480.925s
FAIL	github.com/ipfs/go-ipfs/test/integration	196.772s
```

**Comment by whyrusleeping** [comment]
this issue can be closed, but i agree with @rht.

(although, this issue does not show up in the race detector, its not a data race)
