### ISSUE TITLE
adding hidden files directly should work without flag

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2145]
`ipfs add .vimrc` should just figure things out and add the file. The hidden ignore stuff should only take effect on recursive directory enumeration

**Comment by noffle** [comment]
@whyrusleeping: can you confirm & close? (Is that how you usually do things here? Reporter verifies?)

**Comment by jbenet** [comment]
@noffle yeah sometimes. i support doing that often/most of the time.

**Comment by Kubuxu** [comment]
Looks like it is broken in 0.4.2:
```
> ipfs add .Xresources
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x18
gx/ipfs/QmZNVWh8LLjAavuQ2JXuFmuYH3C11xo988vSgp7UQrTRj1/go-ipfs-util.ErrCast(0x0, 0x0)
	/home/kubuxu/AUR/go-ipfs-git/src/src/gx/ipfs/QmZNVWh8LLjAavuQ2JXuFmuYH3C11xo988vSgp7UQrTRj1/go-ipfs-util/util.go:34 +0x20
github.com/ipfs/go-ipfs/core/commands.glob.func7(0x7f66672ffda8, 0xc8200c0540, 0x7f6667301590, 0xc82025aaf0)
	/home/kubuxu/AUR/go-ipfs-git/src/src/github.com/ipfs/go-ipfs/core/commands/add.go:212 +0xba
main.callCommand(0x7f66672fff50, 0xc82030a4c0, 0x7f66672ffda8, 0xc8200c0540, 0x1625100, 0x1602440, 0x0, 0x0, 0x0, 0x0)
	/home/kubuxu/AUR/go-ipfs-git/src/go-ipfs/cmd/ipfs/main.go:351 +0x897
main.(*cmdInvocation).Run(0xc82030a400, 0x7f66672fff50, 0xc82030a4c0, 0x0, 0x0, 0x0, 0x0)
	/home/kubuxu/AUR/go-ipfs-git/src/go-ipfs/cmd/ipfs/main.go:189 +0x1e7
main.main()
	/home/kubuxu/AUR/go-ipfs-git/src/go-ipfs/cmd/ipfs/main.go:154 +0x660
Error: cast error
```

**Comment by Kubuxu** [comment]
This is working, somewhere in last 60 commits it got fixed.
