### ISSUE TITLE
Crash after GC

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#2731]
I made a GC and then refreshed a page. Node crashed with cryptic error:

```
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xa1d197]
ipfs.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by Kubuxu** [comment]
I was able to repeat it: http://hastebin.com/adiyafenip

Reproduce:
1. Load fs:/ipfs/QmRNoge2g4BiaoWqfB2BUo8JFKe6MAoEyueKgwh9dc2fST/
2. `ipfs repo gc`
3. Load fs:/ipfs/QmRNoge2g4BiaoWqfB2BUo8JFKe6MAoEyueKgwh9dc2fST/ again.
4. Repeat until crash.

**Comment by whyrusleeping** [comment]
:+1: thanks for finding this. This is a weird one...

**Comment by dignifiedquire** [comment]
I crashed my node today as well, by just running gc:


```
Initializing daemon...
Swarm listening on /ip4/10.147.17.68/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.0.21/tcp/4001
Swarm listening on /ip4/46.5.209.151/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/fd67:d185:7678:b25b:c4fe:723b:9a7e:7272/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x48ebc7]

goroutine 764 [running]:
panic(0xa595a0, 0xc8200120c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/ipfs/go-datastore/flatfs.(*Datastore).Query.func1.1(0xc8244aabd0, 0x70, 0x0, 0x0, 0x2209988, 0xc823cbf7a0, 0x0, 0x0)
	/Users/dignifiedquire/.go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/ipfs/go-datastore/flatfs/flatfs.go:323 +0x57
path/filepath.walk(0xc821fe17d0, 0x26, 0x23a01c8, 0xc8201a6270, 0xc822084cc0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/path/filepath/path.go:370 +0x415
path/filepath.walk(0xc8200d6900, 0x1d, 0x23a01c8, 0xc820055040, 0xc822084cc0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0xc8200d6900, 0x1d, 0xc822084cc0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/path/filepath/path.go:396 +0xe1
github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/ipfs/go-datastore/flatfs.(*Datastore).Query.func1(0xc820266900, 0xc8200d6920)
	/Users/dignifiedquire/.go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/ipfs/go-datastore/flatfs/flatfs.go:321 +0xc7
created by github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/ipfs/go-datastore/flatfs.(*Datastore).Query
	/Users/dignifiedquire/.go/src/github.com/ipfs/go-ipfs/Godeps/_workspace/src/github.com/ipfs/go-datastore/flatfs/flatfs.go:343 +0x152
```

````
$ ipfs version --commit
ipfs version 0.4.2-385055d
$ ipfs version --all
go-ipfs version: 0.4.2-385055d
Repo version: 3
System version: amd64/darwin
Golang version: go1.6.2
```

**Comment by whyrusleeping** [comment]
I'm pretty sure this one has been solved. The flatfs query func wasnt checking 'err' in its walk call at the time.
