### ISSUE TITLE
ipfs daemon panic(0xde8420, 0xc082002030) if no network connection

### ISSUE THREAD

**Issue by iav** [ipfs/go-ipfs#2751]
Trying to start 
ipfs version 0.4.1, windows 7 x64
> ipfs daemon

 on laptop without any working network connection got error
```
Initializing daemon...
panic: runtime error: index out of range

goroutine 42 [running]:
panic(0xde8420, 0xc082002030)
        /home/whyrusleeping/go/src/runtime/panic.go:464 +0x3f4
Swarm listening on /ip4/127.0.0.1/tcp/4001
gx/ipfs/Qma5KQppqMBmpdNeVUDuNtEkec1BRNWcS3dodUdiP9267q/gateway.DiscoverGateway(0x0, 0x0, 0x0, 0x0, 0
x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/Qma5KQppqMBmpdNeVUDuNtEkec1BRNWcS3dod
UdiP9267q/gateway/gateway_windows.go:37 +0x4e6
gx/ipfs/QmNLvkCDV6ZjUJsEwGNporYBuZdhWT6q7TBVYQwwRv12HT/go-nat.discoverNATPMP(0xc082174120)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmNLvkCDV6ZjUJsEwGNporYBuZdhWT6q7TBVY
QwwRv12HT/go-nat/natpmp.go:18 +0x46
gx/ipfs/QmNLvkCDV6ZjUJsEwGNporYBuZdhWT6q7TBVYQwwRv12HT/go-nat.DiscoverGateway(0x0, 0x0, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmNLvkCDV6ZjUJsEwGNporYBuZdhWT6q7TBVY
QwwRv12HT/go-nat/nat.go:44 +0x86
gx/ipfs/QmYgaiNVVL7f2nydijAwpDRunRkmxfu3PoK87Y3pH84uAW/go-libp2p/p2p/nat.DiscoverNAT(0x8)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmYgaiNVVL7f2nydijAwpDRunRkmxfu3PoK87
Y3pH84uAW/go-libp2p/p2p/nat/nat.go:37 +0x2b
gx/ipfs/QmYgaiNVVL7f2nydijAwpDRunRkmxfu3PoK87Y3pH84uAW/go-libp2p/p2p/host/basic.(*natManager).discov
erNAT.func1.1(0xc082174060, 0xc082020058)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmYgaiNVVL7f2nydijAwpDRunRkmxfu3PoK87
Y3pH84uAW/go-libp2p/p2p/host/basic/natmgr.go:81 +0x46
created by gx/ipfs/QmYgaiNVVL7f2nydijAwpDRunRkmxfu3PoK87Y3pH84uAW/go-libp2p/p2p/host/basic.(*natMana
ger).discoverNAT.func1
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmYgaiNVVL7f2nydijAwpDRunRkmxfu3PoK87
Y3pH84uAW/go-libp2p/p2p/host/basic/natmgr.go:82 +0x96
```

**Comment by Kubuxu** [comment]
Unfortunately I totally removed Windows just a week ago so I don't have a way to try it but we should be able to produce a possible fix for that.

**Comment by Kubuxu** [comment]
Closing in favor of #3226
