### ISSUE TITLE
strange IO wait hangs

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#2793]
I killed my daemon recently and was browsing through the stack dump when i noticed a bunch of goroutines that looked roughly like this:

```
goroutine 15525749 [IO wait, 435 minutes]:
net.runtime_pollWait(0x7f4e4087cbf0, 0x72, 0xc82d4453bc)
    /home/whyrusleeping/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8259b6610, 0x72, 0x0, 0x0)
    /home/whyrusleeping/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8259b6610, 0x0, 0x0)
    /home/whyrusleeping/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8259b65b0, 0xc82d4453bc, 0x4, 0x4, 0x0, 0x7f4e40972050, 0xc82000e058)
    /home/whyrusleeping/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82075d3a0, 0xc82d4453bc, 0x4, 0x4, 0x0, 0x0, 0x0)
    /home/whyrusleeping/go/src/net/net.go:172 +0xe4
gx/ipfs/QmYp8PC6b9M3UY4awdHkdRUim68KpGSmRmz27bANHteen6/go-multiaddr-net.(*maConn).Read(0xc82a6ae450, 0xc82d4453bc, 0x4, 0x4, 0xc825105890, 0x0, 0x0)
    <autogenerated>:3 +0x82
gx/ipfs/QmboVACz6WES3byh3q8jdYPWL9TMz7CT89V34WPtruuRoS/go-libp2p-transport.(*connWrap).Read(0xc8330ee9a0, 0xc82d4453bc, 0x4, 0x4, 0xc8241b4c30, 0x0, 0x0)
    <autogenerated>:24 +0x82
github.com/ipfs/go-libp2p/p2p/metrics/conn.(*MeteredConn).Read(0xc8330eeaa0, 0xc82d4453bc, 0x4, 0x4, 0x0, 0x0, 0x0)
    /home/whyrusleeping/gopkg/src/github.com/ipfs/go-libp2p/p2p/metrics/conn/conn.go:28 +0x75
github.com/ipfs/go-libp2p/p2p/net/conn.(*singleConn).Read(0xc82a50c680, 0xc82d4453bc, 0x4, 0x4, 0xc82d445500, 0x0, 0x0)
    /home/whyrusleeping/gopkg/src/github.com/ipfs/go-libp2p/p2p/net/conn/conn.go:123 +0x6b
io.ReadAtLeast(0x7f4e408f4698, 0xc82a50c680, 0xc82d4453bc, 0x4, 0x4, 0x4, 0x0, 0x0, 0x0)
    /home/whyrusleeping/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f4e408f4698, 0xc82a50c680, 0xc82d4453bc, 0x4, 0x4, 0x0, 0x0, 0x0)
    /home/whyrusleeping/go/src/io/io.go:315 +0x62
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.ReadLen(0x7f4e408f4698, 0xc82a50c680, 0xc82d4453bc, 0x4, 0x4, 0xac6491, 0x0, 0x0)
    /home/whyrusleeping/gopkg/src/gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/num.go:27 +0xb7
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*reader).nextMsgLen(0xc826ba8780, 0x7f4e408f46e8, 0x0, 0x0)
    /home/whyrusleeping/gopkg/src/gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/msgio.go:163 +0x66
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*reader).ReadMsg(0xc826ba8780, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/whyrusleeping/gopkg/src/gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio/msgio.go:195 +0xdb
gx/ipfs/QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL/go-msgio.(*readWriter).ReadMsg(0xc82858b640, 0x0, 0x0, 0x0, 0x0, 0x0)
    <autogenerated>:17 +0x70
gx/ipfs/QmbuSYB51KtX8izgab1fSyBgsyMH2hTuCfBtXm77PeXWca/go-libp2p-secio.readMsgCtx.func1(0xc82858baa0, 0x7f4e4093a8c0, 0xc82858b640, 0xc828a847e0, 0x7f4e4093a3f0, 0xc828a84660)
    /home/whyrusleeping/gopkg/src/gx/ipfs/QmbuSYB51KtX8izgab1fSyBgsyMH2hTuCfBtXm77PeXWca/go-libp2p-secio/rw.go:280 +0x48
created by gx/ipfs/QmbuSYB51KtX8izgab1fSyBgsyMH2hTuCfBtXm77PeXWca/go-libp2p-secio.readMsgCtx
    /home/whyrusleeping/gopkg/src/gx/ipfs/QmbuSYB51KtX8izgab1fSyBgsyMH2hTuCfBtXm77PeXWca/go-libp2p-secio/rw.go:285 +0xe6
```

It seems very strange for a read call to hang for hours without timing out or receiving some sort of activity. yamux keepalives, and random dht queries should happen more frequently than that.

**Comment by whyrusleeping** [comment]
This still might be occuring, need to verify

**Comment by Stebalien** [comment]
This is no longer happening with yamux but *is* happening with go-multiplex (because it doesn't *have* keepalives).

However, I'm not sure this is really a bug.
