### ISSUE TITLE
daemon crash on git master

### ISSUE THREAD

**Issue by czaks** [ipfs/go-ipfs#2835]
This issue happened while simultaneously executing ```ipfs add -pr bigdirtree/``` and downloading some file from the local machine, via ipfs.io to the local machine back. commit: b731c79 (master). The issue happened 3 times, I'm now unsuccessfully trying to reproduce it on a release branch.

```
panic: runtime error: slice bounds out of range

goroutine 103770 [running]:
panic(0xe5d800, 0xc82000e160)
        /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
bufio.(*Reader).Read(0xc8247604e0, 0xc82455d5a0, 0x11, 0x11, 0xca4f40, 0x0, 0x0)
        /usr/lib/golang/src/bufio/bufio.go:214 +0x3c8
io.ReadAtLeast(0x7feb80f060e8, 0xc8247604e0, 0xc82455d5a0, 0x11, 0x11, 0x11, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/io.go:297 +0xe6
io.ReadFull(0x7feb80f060e8, 0xc8247604e0, 0xc82455d5a0, 0x11, 0x11, 0x11, 0x0, 0x0)
        /usr/lib/golang/src/io/io.go:315 +0x62
gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io.(*varintReader).ReadMsg(0xc825f6c340, 0x7feb80eb0868, 0xc8284237a0, 0x0, 0x0)
        /home/*/src/gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io/varint.go:117 +0x1c2
github.com/ipfs/go-ipfs/routing/dht.(*messageSender).ctxReadMsg.func1(0xc824760840, 0xc82236dec0, 0xc8284237a0)
        /home/*/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:234 +0x73
created by github.com/ipfs/go-ipfs/routing/dht.(*messageSender).ctxReadMsg
        /home/*/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:235 +0x8b

```

**Comment by whyrusleeping** [comment]
Thanks for reporting, I saw this once too but assumed it was some of the code i was messing with.

**Comment by whyrusleeping** [comment]
Some initial debugging work i've done so far:

- this appears to be the result of a race condition with using the same stream across multiple goroutines. It happened after the change to reuse streams in the dht code.
- it appears not to kill my daemon (it keeps running after encountering this)
- running `go test -v -race ./routing/dht` appears to show the race condition in question

**Comment by evbogue** [comment]
This is happening to me as well, using the aur.archlinux.org install of go-ipfs-git master.

**Comment by Kubuxu** [comment]
I am also using newest master from `go-ipfs-git` but am not observing any crashes.

**Comment by evbogue** [comment]
```
Initializing daemon...
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/168.235.78.40/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
panic: runtime error: slice bounds out of range

goroutine 237764 [running]:
panic(0xe65500, 0xc82000e0b0)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
bufio.(*Reader).Read(0xc82c96f6e0, 0xc832c04000, 0x12, 0x21cf, 0x0, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:214 +0x3c8
io.ReadAtLeast(0x7fcf7497f5a8, 0xc82c96f6e0, 0xc832c04000, 0x12, 0x21cf, 0x12, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fcf7497f5a8, 0xc82c96f6e0, 0xc832c04000, 0x12, 0x21cf, 0x13, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:315 +0x62
gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io.(*varintReader).ReadMsg(0xc82de71300, 0x7fcf7497f940, 0xc827711ce0, 0x0, 0x0)
        /home/ev/builds/go-ipfs-git/src/src/gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io/varint.go:117 +0x1c2
github.com/ipfs/go-ipfs/routing/dht.(*messageSender).ctxReadMsg.func1(0xc823246cc0, 0xc829c77a40, 0xc827711ce0)
        /home/ev/builds/go-ipfs-git/src/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:234 +0x73
created by github.com/ipfs/go-ipfs/routing/dht.(*messageSender).ctxReadMsg
        /home/ev/builds/go-ipfs-git/src/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:235 +0x8b
```

**Comment by evbogue** [comment]
Above was my VPS. My local just crashed, here's the same error: 
```
panic: runtime error: slice bounds out of range

goroutine 350572 [running]:
panic(0xe65500, 0xc82000e0f0)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
bufio.(*Reader).Read(0xc82530cd80, 0xc8269fa085, 0x1, 0x1, 0xc85, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:214 +0x3c8
io.ReadAtLeast(0x7fbdf876a348, 0xc82530cd80, 0xc8269f9400, 0xc86, 0xc86, 0xc86, 0xc85, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fbdf876a348, 0xc82530cd80, 0xc8269f9400, 0xc86, 0xc86, 0xc86, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:315 +0x62
gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io.(*varintReader).ReadMsg(0xc8203113c0, 0x7fbdf873bb38, 0xc8278e3500, 0x0, 0x0)
	/home/ev/builds/go-ipfs-git/src/src/gx/ipfs/QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV/gogo-protobuf/io/varint.go:117 +0x1c2
github.com/ipfs/go-ipfs/routing/dht.(*messageSender).ctxReadMsg.func1(0xc8266ff500, 0xc8229094a0, 0xc8278e3500)
	/home/ev/builds/go-ipfs-git/src/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:234 +0x73
created by github.com/ipfs/go-ipfs/routing/dht.(*messageSender).ctxReadMsg
	/home/ev/builds/go-ipfs-git/src/src/github.com/ipfs/go-ipfs/routing/dht/dht_net.go:235 +0x8b
```

**Comment by whyrusleeping** [comment]
@evbogue and @czaks  what version of go are you running?

**Comment by evbogue** [comment]
go1.6.2 linux/amd64 on both systems.

**Comment by czaks** [comment]
golang-1.6.2-1.fc24.x86_64

**Comment by Kubuxu** [comment]
I am running: `go1.6.2 linux/amd64`

**Comment by whyrusleeping** [comment]
@evbogue @czaks could you guys try latest master (with the fixes in #2856 ) and see if this issue still occurs?

**Comment by evbogue** [comment]
Updated to master. I'll report back if I have any issues.

**Comment by evbogue** [comment]
I have not been able to replicate the error on the latest master. I think this issue can be closed.
