### ISSUE TITLE
Commands: Verify panic

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#2950]
Version/Platform/Processor information (from `ipfs version --all`):
go-ipfs version: 0.4.3-dev-9d2e1e9
Repo version: 4
System version: amd64/windows
Golang version: go1.7beta2

Type (bug, feature, meta, test failure, question):
bug
Area (api, commands, daemon, fuse, etc):
commands
Priority (from P0: functioning, to P4: operations on fire):
P1

Description:
On the new `repo verify` command I am getting a panic if the daemon is up, it works fine if the daemon is not running.

```
goroutine 1 [running]:
runtime/debug.Stack(0xc0420197e0, 0xc042018a00, 0xc042079ca8)
        C:/Go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        C:/Go/src/runtime/debug/stack.go:16 +0x29
gx/ipfs/QmZNVWh8LLjAavuQ2JXuFmuYH3C11xo988vSgp7UQrTRj1/go-ipfs-util.ErrCast(0x0, 0x0)
        C:/tmp/src/gx/ipfs/QmZNVWh8LLjAavuQ2JXuFmuYH3C11xo988vSgp7UQrTRj1/go-ipfs-util/util.go:34 +0x1b
github.com/ipfs/go-ipfs/core/commands.glob.func77.1(0xb8d9a0, 0xc04206bc80, 0xc042079d40, 0x8001, 0xb51fe0, 0x3598601)
        C:/tmp/src/github.com/ipfs/go-ipfs/core/commands/repo.go:281 +0x350
github.com/ipfs/go-ipfs/commands.(*ChannelMarshaler).Read(0xc0423202d0, 0xc042348000, 0x8000, 0x8000, 0x8000, 0x8000, 0xc042256fc0)
        C:/tmp/src/github.com/ipfs/go-ipfs/commands/channelmarshaler.go:24 +0x1b6
io.copyBuffer(0x10533a0, 0xc04202c010, 0x10514a0, 0xc0423202d0, 0xc042348000, 0x8000, 0x8000, 0x0, 0x10617c0, 0xc042256fc0)
        C:/Go/src/io/io.go:390 +0x14e
io.Copy(0x10533a0, 0xc04202c010, 0x10514a0, 0xc0423202d0, 0xc0423202d0, 0x0, 0x0)
        C:/Go/src/io/io.go:360 +0x6f
main.main()
        C:/tmp/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:166 +0x3a5
Error: cast error
```

**Comment by whyrusleeping** [comment]
@djdv thanks for the report! It seems i forgot to test with a running daemon...
