### ISSUE TITLE
Runtime error with IPNS publish

### ISSUE THREAD

**Issue by mattseh** [ipfs/go-ipfs#2996]
IPFS 0.4.3 RC 1 Linux 64 bit, I did: 

> ipfs name publish QmdpiB5aDu2knhEXzLEn8xY7DBTVj3gTLpHwqZytGVpXJN
Published to QmaVq5GrxoKqwk3SUVHewAoR7PURcJbkqYLEVSLWTkZfdu: QmdpiB5aDu2knhEXzLEn8xY7DBTVj3gTLpHwqZytGVpXJN

It worked, but the daemon output:

```
09:54:02.377 ERROR commands/h: runtime error: index out of range handler.go:128
goroutine 3861042 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /home/whyrusleeping/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        /home/whyrusleeping/go/src/runtime/debug/stack.go:16 +0x18
github.com/ipfs/go-ipfs/commands/http.internalHandler.ServeHTTP.func1()
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/commands/http/handler.go:130 +0x19a
panic(0xe7ac20, 0xc82000c090)
        /home/whyrusleeping/go/src/runtime/panic.go:443 +0x4e9
github.com/ipfs/go-ipfs/core/commands.glob.func61(0x7f44640cac20, 0xc82d975a40, 0x7f44640cadc0, 0xc82734c000)
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/publish.go:81 +0xbfb
github.com/ipfs/go-ipfs/commands.(*Command).Call(0x1642b00, 0x7f44640cac20, 0xc82d975a40, 0x0, 0x0)
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/commands/command.go:111 +0x472
github.com/ipfs/go-ipfs/commands/http.internalHandler.ServeHTTP(0x0, 0xc820211560, 0xb, 0xc8231f8e10, 0xc82017a000, 0x11c2218, 0xc8200786e0, 0xc8231e1ae0, 0x1642b00, 0xc8231f8d20, ...)
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/commands/http/handler.go:186 +0x7ef
github.com/ipfs/go-ipfs/commands/http.(*internalHandler).ServeHTTP(0xc8202d7d60, 0x7f446092d188, 0xc820027418, 0xc8226f0460)
        <autogenerated>:4 +0xba
gx/ipfs/QmQzTLDsi3a37CJyMDBXnjiHKQpth3AGS1yqwU57FfLwfG/cors.(*Cors).Handler.func1(0x7f446092d188, 0xc820027418, 0xc8226f0460)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmQzTLDsi3a37CJyMDBXnjiHKQpth3AGS1yqwU57FfLwfG/cors/cors.go:188 +0x1c5
net/http.HandlerFunc.ServeHTTP(0xc8231f6e80, 0x7f446092d188, 0xc820027418, 0xc8226f0460)
        /home/whyrusleeping/go/src/net/http/server.go:1618 +0x3a
github.com/ipfs/go-ipfs/commands/http.Handler.ServeHTTP(0x0, 0xc820211560, 0xb, 0xc8231f8e10, 0xc82017a000, 0x11c2218, 0x0, 0xc8231e1ae0, 0x1642b00, 0xc8231f8d20, ...)
        /builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/commands/http/handler.go:119 +0x5e
github.com/ipfs/go-ipfs/commands/http.(*Handler).ServeHTTP(0xc8231c0d20, 0x7f446092d188, 0xc820027418, 0xc8226f0460)
        <autogenerated>:5 +0xc6
net/http.(*ServeMux).ServeHTTP(0xc8231f8330, 0x7f446092d188, 0xc820027418, 0xc8226f0460)
        /home/whyrusleeping/go/src/net/http/server.go:1910 +0x17d
net/http.(Handler).ServeHTTP-fm(0x7f446092d188, 0xc820027418, 0xc8226f0460)
        /home/whyrusleeping/go/src/net/http/h2_bundle.go:3847 +0x50
gx/ipfs/QmdhsRK1EK2fvAz2i2SH5DEfkL6seDuyMYEsxKa9Braim3/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0x7f446092d0b0, 0xc824211930, 0xc8226f0460)
        /builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmdhsRK1EK2fvAz2i2SH5DEfkL6seDuyMYEsxKa9Braim3/client_golang/prometheus/http.go:158 +0x336
net/http.HandlerFunc.ServeHTTP(0xc8202d7d10, 0x7f446092d0b0, 0xc824211930, 0xc8226f0460)
        /home/whyrusleeping/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8231f82d0, 0x7f446092d0b0, 0xc824211930, 0xc8226f0460)
        /home/whyrusleeping/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc8231a5680, 0x7f446092d0b0, 0xc824211930, 0xc8226f0460)
        /home/whyrusleeping/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc824f94c00)
        /home/whyrusleeping/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
        /home/whyrusleeping/go/src/net/http/server.go:2137 +0x44e
```

I ran the command again and it didn't reproduce the output.

Cheers

**Comment by whyrusleeping** [comment]
If you could try and reproduce this with 0.4.3-rc3 that would be great. I think this is related to another issue that was fixed since 0.4.3-rc1, so i'm going to mark it as closed. *please* reopen this if you encounter the issue again
