### ISSUE TITLE
Index out of range `ipfs daemon`

### ISSUE THREAD

**Issue by karlek** [ipfs/go-ipfs#3040]
Version/Platform/Processor information (from `ipfs version --all`):
go-ipfs version: 0.4.3-rc2-1eb94e6
Repo version: 4
System version: amd64/linux
Golang version: devel +50edddb Tue Aug 2 21:31:58 2016 +0000

Type (bug, feature, meta, test failure, question): bug
Area (api, commands, daemon, fuse, etc): daemon
Priority (from P0: functioning, to P4: operations on fire): P1

Description:

Hi again; another panic! However the daemon survived this time, which is good :)

```
$ ipfs daemon
Initializing daemon...
[...]
01:04:49.235 ERROR commands/h: a panic has occurred in the commands handler! handler.go:127
01:04:49.235 ERROR commands/h: runtime error: index out of range handler.go:128
goroutine 14282478 [running]:
runtime/debug.Stack(0x21, 0xc421cd5548, 0x646367)
    /home/_/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
    /home/_/go/src/runtime/debug/stack.go:16 +0x22
github.com/ipfs/go-ipfs/commands/http.internalHandler.ServeHTTP.func1()
    /home/_/Desktop/privgo/src/github.com/ipfs/go-ipfs/commands/http/handler.go:130 +0x160
panic(0xbd36e0, 0xc420012110)
    /home/_/go/src/runtime/panic.go:458 +0x243
github.com/ipfs/go-ipfs/core/commands.glob..func70(0x10e69e0, 0xc420283680, 0x10e5da0, 0xc43569d180)
    /home/_/Desktop/privgo/src/github.com/ipfs/go-ipfs/core/commands/ping.go:90 +0x2c2
github.com/ipfs/go-ipfs/commands.(*Command).Call(0x119aa60, 0x10e69e0, 0xc420283680, 0x0, 0x0)
    /home/_/Desktop/privgo/src/github.com/ipfs/go-ipfs/commands/command.go:111 +0x286
github.com/ipfs/go-ipfs/commands/http.internalHandler.ServeHTTP(0x0, 0xc42026e540, 0xd, 0xc421f4d0b0, 0xc42034a1c0, 0xd3c878, 0xc4202f62c0, 0xc421e64c90, 0x119aa60, 0xc421f4cfc0, ...)
    /home/_/Desktop/privgo/src/github.com/ipfs/go-ipfs/commands/http/handler.go:186 +0x3d2
github.com/ipfs/go-ipfs/commands/http.(*internalHandler).ServeHTTP(0xc421cc4dc0, 0x10ddd20, 0xc427eca078, 0xc431aa24b0)
    <autogenerated>:4 +0x8a
gx/ipfs/QmQzTLDsi3a37CJyMDBXnjiHKQpth3AGS1yqwU57FfLwfG/cors.(*Cors).Handler.func1(0x10ddd20, 0xc427eca078, 0xc431aa24b0)
    /home/_/Desktop/privgo/src/gx/ipfs/QmQzTLDsi3a37CJyMDBXnjiHKQpth3AGS1yqwU57FfLwfG/cors/cors.go:188 +0xe9
net/http.HandlerFunc.ServeHTTP(0xc421f295e0, 0x10ddd20, 0xc427eca078, 0xc431aa24b0)
    /home/_/go/src/net/http/server.go:1726 +0x44
github.com/ipfs/go-ipfs/commands/http.Handler.ServeHTTP(0x0, 0xc42026e540, 0xd, 0xc421f4d0b0, 0xc42034a1c0, 0xd3c878, 0x0, 0xc421e64c90, 0x119aa60, 0xc421f4cfc0, ...)
    /home/_/Desktop/privgo/src/github.com/ipfs/go-ipfs/commands/http/handler.go:119 +0x5e
github.com/ipfs/go-ipfs/commands/http.(*Handler).ServeHTTP(0xc421fba300, 0x10ddd20, 0xc427eca078, 0xc431aa24b0)
    <autogenerated>:5 +0x96
net/http.(*ServeMux).ServeHTTP(0xc421f4c120, 0x10ddd20, 0xc427eca078, 0xc431aa24b0)
    /home/_/go/src/net/http/server.go:2022 +0x7f
net/http.(Handler).ServeHTTP-fm(0x10ddd20, 0xc427eca078, 0xc431aa24b0)
    /home/_/go/src/net/http/h2_bundle.go:4066 +0x4d
gx/ipfs/QmdhsRK1EK2fvAz2i2SH5DEfkL6seDuyMYEsxKa9Braim3/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0x10de0e0, 0xc4317cca90, 0xc431aa24b0)
    /home/_/Desktop/privgo/src/gx/ipfs/QmdhsRK1EK2fvAz2i2SH5DEfkL6seDuyMYEsxKa9Braim3/client_golang/prometheus/http.go:158 +0x2ab
net/http.HandlerFunc.ServeHTTP(0xc421cc4d70, 0x10de0e0, 0xc4317cca90, 0xc431aa24b0)
    /home/_/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc421f4c0f0, 0x10de0e0, 0xc4317cca90, 0xc431aa24b0)
    /home/_/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420129d80, 0x10de0e0, 0xc4317cca90, 0xc431aa24b0)
    /home/_/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc431708280, 0x10def60, 0xc4317d2600)
    /home/_/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
    /home/_/go/src/net/http/server.go:2293 +0x44d
01:06:31.163 ERROR commands/h: err: write tcp4 127.0.0.1:5001->127.0.0.1:58746: write: broken pipe handler.go:288
```

**Comment by whyrusleeping** [comment]
@karlek you are very adept at finding these... I have four nodes running on various computers under simulated load and i havent seen any of these things. So thank you for reporting!

Could you please try updating the version of go you are using to compile ipfs with? Thats the one outlier in your setup i'm seeing

**Comment by karlek** [comment]
No problem!

I'm currently running the latest commit of go and have re-installed `ipfs`.
`go version devel +da070be Thu Aug 4 21:42:44 2016 +0000 linux/amd64`

What version are you using? go1.6?

**Comment by whyrusleeping** [comment]
@karlek could you try with a tagged build? something like `go1.6.3` or `go1.7rc3`? development builds tend to be unstable.

**Comment by karlek** [comment]
Sure!

**Comment by whyrusleeping** [comment]
@karlek have you seen any more issues like this since updating?

**Comment by karlek** [comment]
@whyrusleeping 
No, I haven't used my computer for the past two weeks. Will reply if it reoccurs.

**Comment by karlek** [comment]
Hasn't been any update, so I'll close this.
