### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by mateon1** [ipfs/go-ipfs#3156]
Version/Platform/Processor information:
go-ipfs version: 0.4.4-dev-28b01dd
Repo version: 4
System version: amd64/windows
Golang version: go1.7

Type: bug
Area: testing
Priority: P2

Description:
When running `make test` on Windows, a lot of tests fail. While for some it's to be expected (FUSE), for others it's not.

full log: [`QmeZz6QCL4EQencqWiWTFkhqmxJLoPtwP7fGpH4C2UZEta`](https://ipfs.io/ipfs/QmeZz6QCL4EQencqWiWTFkhqmxJLoPtwP7fGpH4C2UZEta) (12.85KB)

Log (fails only):

```
C:\GoPath\src\github.com\ipfs\go-ipfs>make test
bin/gx-v0.9.0 --verbose install --global
make -C cmd/ipfs build
make[1]: Entering directory '/c/GoPath/src/github.com/ipfs/go-ipfs/cmd/ipfs'
go build -i -ldflags="-X "github.com/ipfs/go-ipfs/repo/config".CurrentCommit=6fdfaaf"
make[1]: Leaving directory '/c/GoPath/src/github.com/ipfs/go-ipfs/cmd/ipfs'
IPFS_REUSEPORT=false go test ./...
...
# github.com/ipfs/go-ipfs/Godeps/_workspace/src/bazil.org/fuse
Godeps\_workspace\src\bazil.org\fuse\error_std.go:27: undefined: errNoXattr
Godeps\_workspace\src\bazil.org\fuse\fuse.go:1092: undefined: attr
Godeps\_workspace\src\bazil.org\fuse\fuse_kernel.go:152: undefined: syscall.O_ACCMODE
Godeps\_workspace\src\bazil.org\fuse\fuse_kernel.go:378: undefined: attr
--- FAIL: TestGetBlocksSequential (50.04s)
        blocks_test.go:81: one instance at a time, get blocks concurrently
        blocks_test.go:95: Didnt get enough blocks back: 0/50
FAIL
FAIL    github.com/ipfs/go-ipfs/blockservice/test       50.122s
--- FAIL: TestMultipleAddrsPerPeer (0.00s)
        bootstrap_test.go:54: expected fewer peers
FAIL
FAIL    github.com/ipfs/go-ipfs/core    0.575s
--- FAIL: TestGetBlockFromPeerAfterPeerAnnounces (1.00s)
        bitswap_test.go:89: context deadline exceeded
        bitswap_test.go:90: Expected to succeed
--- FAIL: TestLargeFileNoRebroadcast (0.51s)
        bitswap_test.go:164: Give the blocks to the first instance
        bitswap_test.go:175: not enough peers connected to instance
*** Test killed: ran too long (10m0s).
FAIL    github.com/ipfs/go-ipfs/exchange/bitswap        600.081s
--- FAIL: TestPeerRepeats (0.00s)
        peer_request_queue_test.go:100: [QmPPYFNxpLLovngdWcz3s7CFnTX1VNKNARrQC4iXzkdVmQ QmPPYFNxpLLovngdWcz3s7CFnTX1VNKNARrQC4iXzkdVmQ QmQEYxgHcyqB8RuLpgAw6LbnKJZtCzTmTU8tNBejPUjvpC QmQEYxgHcyqB8RuLpgAw6LbnKJZtCzTmTU8tNBejPUjvpC]
        peer_request_queue_test.go:101: [QmPPYFNxpLLovngdWcz3s7CFnTX1VNKNARrQC4iXzkdVmQ QmPPYFNxpLLovngdWcz3s7CFnTX1VNKNARrQC4iXzkdVmQ QmPPYFNxpLLovngdWcz3s7CFnTX1VNKNARrQC4iXzkdVmQ QmQEYxgHcyqB8RuLpgAw6LbnKJZtCzTmTU8tNBejPUjvpC]
        peer_request_queue_test.go:104: unexpected peer QmQEYxgHcyqB8RuLpgAw6LbnKJZtCzTmTU8tNBejPUjvpC QmPPYFNxpLLovngdWcz3s7CFnTX1VNKNARrQC4iXzkdVmQ
FAIL
FAIL    github.com/ipfs/go-ipfs/exchange/bitswap/decision       8.152s
--- FAIL: TestReprovide (0.01s)
        reprovide_test.go:46: Should have gotten a provider
FAIL
FAIL    github.com/ipfs/go-ipfs/exchange/reprovide      0.177s
FAIL    github.com/ipfs/go-ipfs/fuse/ipns [build failed]
FAIL    github.com/ipfs/go-ipfs/fuse/node [build failed]
FAIL    github.com/ipfs/go-ipfs/fuse/readonly [build failed]
> beep
data: beep
links:
encoded: [10 4 98 101 101 112]
hash: [18 32 193 59 112 166 232 16 218 229 145 229 2 151 79 99 36 226 159 180 250 165 85 42 247 155 206 83 86 22 119 201 126 49]
key:  QmbLwxt77hfvK1o9WA13VBvkV9gvmEK2k8SDZbVaUMZZi8
n.Stat correct: NodeStat{NumLinks: 0, BlockSize: 6, LinksSize: 2, DataSize: 4, CumulativeSize: 6}
> boop
data: boop
links:
encoded: [10 4 98 111 111 112]
hash: [18 32 33 156 63 214 215 143 203 71 241 112 76 170 231 16 224 83 17 164 57 74 202 132 23 167 48 93 108 225 221 217 126 241]
key:  QmQbrML2cXZoNNC1DrAXxZis9Y9kSBXuqRjs96WjYRWwXe
n.Stat correct: NodeStat{NumLinks: 0, BlockSize: 6, LinksSize: 2, DataSize: 4, CumulativeSize: 6}
> beep boop
data: beep boop
links:
- beep-link 6 [18 32 193 59 112 166 232 16 218 229 145 229 2 151 79 99 36 226 159 180 250 165 85 42 247 155 206 83 86 22 119 201 126 49]
- boop-link 6 [18 32 33 156 63 214 215 143 203 71 241 112 76 170 231 16 224 83 17 164 57 74 202 132 23 167 48 93 108 225 221 217 126 241]
encoded: [18 49 10 34 18 32 193 59 112 166 232 16 218 229 145 229 2 151 79 99 36 226 159 180 250 165 85 42 247 155 206 83 86 22 119 201 126 49 18 9 98 101 101 112 45 108 105 110 107 24 6 18 49 10 34 18 32 33 156 63 214 215 143 203 71 241 112 76 170 231 16 224 83 17 164 57 74 202 132 23 167 48 93 108 225 221 217 126 241 18 9 98 111 111 112 45 108 105 110 107 24 6 10 9 98 101 101 112 32 98 111 111 112]
hash: [18 32 232 124 23 19 12 4 210 187 6 15 116 26 216 22 243 100 59 112 164 221 65 115 156 142 201 186 117 182 144 21 14 191]
key:  QmdzB3MPwM8hrJoyuJzKAbF2nDbtQN2R2vD1oTjmki5SAa
n.Stat correct: NodeStat{NumLinks: 2, BlockSize: 113, LinksSize: 104, DataSize: 9, CumulativeSize: 125}
Got first node back.
Got first node back.
*** Test killed: ran too long (10m0s).
FAIL    github.com/ipfs/go-ipfs/merkledag       600.372s
--- FAIL: TestCanManageReposIndependently (0.12s)
        fsrepo_test.go:42: initialize two repos
        fsrepo_test.go:46: ensure repos initialized
        fsrepo_test.go:50: open the two repos
        fsrepo_test.go:56: close and remove b while a is open
        assert.go:7: [remove b] error: remove C:\Users\matin\AppData\Local\Temp\b223754005\._check_writeable: Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces.
FAIL
FAIL    github.com/ipfs/go-ipfs/repo/fsrepo     0.196s

--- FAIL: TestConfig (0.00s)
        serialize_test.go:31: config file should not be executable or accessible to world: -rw-rw-rw-
FAIL
FAIL    github.com/ipfs/go-ipfs/repo/fsrepo/serialize   0.159s
--- FAIL: TestGetFailures (0.00s)
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 38043 [running]:
panic(0x888480, 0xc04200a070)
        C:/Go/src/runtime/panic.go:500 +0x1af
testing.tRunner.func1(0xc04a307380)
        C:/Go/src/testing/testing.go:579 +0x264
panic(0x888480, 0xc04200a070)
        C:/Go/src/runtime/panic.go:458 +0x251
github.com/ipfs/go-ipfs/routing/dht.TestGetFailures(0xc04a307380)
        C:/GoPath/src/github.com/ipfs/go-ipfs/routing/dht/ext_test.go:38 +0x16cd
testing.tRunner(0xc04a307380, 0x954ba8)
        C:/Go/src/testing/testing.go:610 +0x88
created by testing.(*T).Run
        C:/Go/src/testing/testing.go:646 +0x2f3
FAIL    github.com/ipfs/go-ipfs/routing/dht     8.888s
...
--- FAIL: TestTableFindMultiple (0.00s)
        table_test.go:106: Searching for peer: '<peer.ID ahVxFV>'
        table_test.go:109: Got back different number of peers than we expected.
FAIL
FAIL    github.com/ipfs/go-ipfs/routing/kbucket 0.145s
...
--- FAIL: TestValidAfter (0.03s)
        centralized_test.go:168: providers []
FAIL
FAIL    github.com/ipfs/go-ipfs/routing/mock    1.411s
...
make: *** [Makefile:89: test_go_expensive] Error 2
```

**Comment by djdv** [comment]
Adding my bulk results as well.
`go test -tags=nofuse "./..." | tee test.log`

```
?   	github.com/ipfs/go-ipfs	[no test files]
ok  	github.com/ipfs/go-ipfs/assets	0.432s
ok  	github.com/ipfs/go-ipfs/blocks	0.195s
ok  	github.com/ipfs/go-ipfs/blocks/blockstore	0.977s
ok  	github.com/ipfs/go-ipfs/blocks/blocksutil	0.519s
ok  	github.com/ipfs/go-ipfs/blocks/bloom	0.193s
ok  	github.com/ipfs/go-ipfs/blocks/key	0.204s
ok  	github.com/ipfs/go-ipfs/blocks/set	0.837s
?   	github.com/ipfs/go-ipfs/blockservice	[no test files]
--- FAIL: TestGetBlocksSequential (50.01s)
	blocks_test.go:81: one instance at a time, get blocks concurrently
	blocks_test.go:95: Didnt get enough blocks back: 0/50
FAIL
FAIL	github.com/ipfs/go-ipfs/blockservice/test	50.945s
ok  	github.com/ipfs/go-ipfs/cmd/ipfs	5.898s
ok  	github.com/ipfs/go-ipfs/cmd/ipfswatch	10.677s
?   	github.com/ipfs/go-ipfs/cmd/seccat	[no test files]
ok  	github.com/ipfs/go-ipfs/commands	5.664s
ok  	github.com/ipfs/go-ipfs/commands/cli	6.595s
ok  	github.com/ipfs/go-ipfs/commands/files	5.422s
ok  	github.com/ipfs/go-ipfs/commands/http	3.288s
--- FAIL: TestMultipleAddrsPerPeer (0.00s)
	bootstrap_test.go:54: expected fewer peers
FAIL
FAIL	github.com/ipfs/go-ipfs/core	4.461s
ok  	github.com/ipfs/go-ipfs/core/commands	0.847s
?   	github.com/ipfs/go-ipfs/core/commands/files	[no test files]
?   	github.com/ipfs/go-ipfs/core/commands/object	[no test files]
?   	github.com/ipfs/go-ipfs/core/commands/unixfs	[no test files]
ok  	github.com/ipfs/go-ipfs/core/corehttp	10.869s
?   	github.com/ipfs/go-ipfs/core/corenet	[no test files]
?   	github.com/ipfs/go-ipfs/core/corerepo	[no test files]
?   	github.com/ipfs/go-ipfs/core/corerouting	[no test files]
ok  	github.com/ipfs/go-ipfs/core/coreunix	5.269s
?   	github.com/ipfs/go-ipfs/core/mock	[no test files]
?   	github.com/ipfs/go-ipfs/diagnostics	[no test files]
?   	github.com/ipfs/go-ipfs/diagnostics/pb	[no test files]
?   	github.com/ipfs/go-ipfs/exchange	[no test files]
--- FAIL: TestGetBlockFromPeerAfterPeerAnnounces (1.00s)
	bitswap_test.go:89: context deadline exceeded
	bitswap_test.go:90: Expected to succeed
--- FAIL: TestLargeFileNoRebroadcast (0.52s)
	bitswap_test.go:164: Give the blocks to the first instance
	bitswap_test.go:175: not enough peers connected to instance
--- FAIL: TestSendToWantingPeer (5.00s)
	bitswap_test.go:254: Session <peer.ID bMj1pn>
	bitswap_test.go:255: Session <peer.ID bMj1pn>
	bitswap_test.go:277: context timed out and broke promise channel!
--- FAIL: TestLargeFile (0.53s)
	bitswap_test.go:164: Give the blocks to the first instance
	bitswap_test.go:175: not enough peers connected to instance
--- FAIL: TestLargeSwarm (0.56s)
	bitswap_test.go:164: Give the blocks to the first instance
	bitswap_test.go:175: not enough peers connected to instance
FAIL
FAIL	github.com/ipfs/go-ipfs/exchange/bitswap	10.618s
--- FAIL: TestPeerRepeats (0.00s)
	peer_request_queue_test.go:100: [QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP]
	peer_request_queue_test.go:101: [QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x47eb3c]

goroutine 52 [running]:
panic(0x6c02a0, 0xc04200e0a0)
	C:/Go/src/runtime/panic.go:500 +0x1af
testing.tRunner.func1(0xc042080780)
	C:/Go/src/testing/testing.go:579 +0x264
panic(0x6c02a0, 0xc04200e0a0)
	C:/Go/src/runtime/panic.go:458 +0x251
github.com/ipfs/go-ipfs/exchange/bitswap/decision.TestPeerRepeats(0xc042080780)
	C:/tmp/src/github.com/ipfs/go-ipfs/exchange/bitswap/decision/peer_request_queue_test.go:116 +0xcdc
testing.tRunner(0xc042080780, 0x742218)
	C:/Go/src/testing/testing.go:610 +0x88
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:646 +0x2f3
FAIL	github.com/ipfs/go-ipfs/exchange/bitswap/decision	10.988s
ok  	github.com/ipfs/go-ipfs/exchange/bitswap/message	0.246s
?   	github.com/ipfs/go-ipfs/exchange/bitswap/message/pb	[no test files]
?   	github.com/ipfs/go-ipfs/exchange/bitswap/network	[no test files]
ok  	github.com/ipfs/go-ipfs/exchange/bitswap/notifications	0.395s
ok  	github.com/ipfs/go-ipfs/exchange/bitswap/testnet	1.156s
?   	github.com/ipfs/go-ipfs/exchange/bitswap/wantlist	[no test files]
ok  	github.com/ipfs/go-ipfs/exchange/offline	0.293s
--- FAIL: TestReprovide (0.08s)
	reprovide_test.go:46: Should have gotten a provider
FAIL
FAIL	github.com/ipfs/go-ipfs/exchange/reprovide	3.716s
?   	github.com/ipfs/go-ipfs/flags	[no test files]
?   	github.com/ipfs/go-ipfs/fuse/ipns	[no test files]
?   	github.com/ipfs/go-ipfs/fuse/mount	[no test files]
?   	github.com/ipfs/go-ipfs/fuse/node	[no test files]
?   	github.com/ipfs/go-ipfs/fuse/readonly	[no test files]
ok  	github.com/ipfs/go-ipfs/importer	3.336s
ok  	github.com/ipfs/go-ipfs/importer/balanced	1.085s
ok  	github.com/ipfs/go-ipfs/importer/chunk	2.539s
?   	github.com/ipfs/go-ipfs/importer/helpers	[no test files]
ok  	github.com/ipfs/go-ipfs/importer/trickle	14.656s
> beep
data: beep
links:
encoded: [10 4 98 101 101 112]
hash: [18 32 193 59 112 166 232 16 218 229 145 229 2 151 79 99 36 226 159 180 250 165 85 42 247 155 206 83 86 22 119 201 126 49]
key:  QmbLwxt77hfvK1o9WA13VBvkV9gvmEK2k8SDZbVaUMZZi8
n.Stat correct: NodeStat{NumLinks: 0, BlockSize: 6, LinksSize: 2, DataSize: 4, CumulativeSize: 6}
> boop
data: boop
links:
encoded: [10 4 98 111 111 112]
hash: [18 32 33 156 63 214 215 143 203 71 241 112 76 170 231 16 224 83 17 164 57 74 202 132 23 167 48 93 108 225 221 217 126 241]
key:  QmQbrML2cXZoNNC1DrAXxZis9Y9kSBXuqRjs96WjYRWwXe
n.Stat correct: NodeStat{NumLinks: 0, BlockSize: 6, LinksSize: 2, DataSize: 4, CumulativeSize: 6}
> beep boop
data: beep boop
links:
- beep-link 6 [18 32 193 59 112 166 232 16 218 229 145 229 2 151 79 99 36 226 159 180 250 165 85 42 247 155 206 83 86 22 119 201 126 49]
- boop-link 6 [18 32 33 156 63 214 215 143 203 71 241 112 76 170 231 16 224 83 17 164 57 74 202 132 23 167 48 93 108 225 221 217 126 241]
encoded: [18 49 10 34 18 32 193 59 112 166 232 16 218 229 145 229 2 151 79 99 36 226 159 180 250 165 85 42 247 155 206 83 86 22 119 201 126 49 18 9 98 101 101 112 45 108 105 110 107 24 6 18 49 10 34 18 32 33 156 63 214 215 143 203 71 241 112 76 170 231 16 224 83 17 164 57 74 202 132 23 167 48 93 108 225 221 217 126 241 18 9 98 111 111 112 45 108 105 110 107 24 6 10 9 98 101 101 112 32 98 111 111 112]
hash: [18 32 232 124 23 19 12 4 210 187 6 15 116 26 216 22 243 100 59 112 164 221 65 115 156 142 201 186 117 182 144 21 14 191]
key:  QmdzB3MPwM8hrJoyuJzKAbF2nDbtQN2R2vD1oTjmki5SAa
n.Stat correct: NodeStat{NumLinks: 2, BlockSize: 113, LinksSize: 104, DataSize: 9, CumulativeSize: 125}
Got first node back.
Got first node back.
Got first node back.
*** Test killed: ran too long (10m0s).
FAIL	github.com/ipfs/go-ipfs/merkledag	606.929s
ok  	github.com/ipfs/go-ipfs/merkledag/pb	0.533s
?   	github.com/ipfs/go-ipfs/merkledag/test	[no test files]
ok  	github.com/ipfs/go-ipfs/merkledag/traverse	8.292s
ok  	github.com/ipfs/go-ipfs/merkledag/utils	2.498s
ok  	github.com/ipfs/go-ipfs/mfs	1.464s
ok  	github.com/ipfs/go-ipfs/namesys	0.564s
?   	github.com/ipfs/go-ipfs/namesys/pb	[no test files]
ok  	github.com/ipfs/go-ipfs/namesys/republisher	6.220s
?   	github.com/ipfs/go-ipfs/notifications	[no test files]
ok  	github.com/ipfs/go-ipfs/path	0.421s
ok  	github.com/ipfs/go-ipfs/pin	1.288s
?   	github.com/ipfs/go-ipfs/pin/gc	[no test files]
?   	github.com/ipfs/go-ipfs/pin/internal/pb	[no test files]
?   	github.com/ipfs/go-ipfs/repo	[no test files]
?   	github.com/ipfs/go-ipfs/repo/common	[no test files]
?   	github.com/ipfs/go-ipfs/repo/config	[no test files]
--- FAIL: TestCanManageReposIndependently (2.30s)
	fsrepo_test.go:42: initialize two repos
	fsrepo_test.go:46: ensure repos initialized
	fsrepo_test.go:50: open the two repos
	fsrepo_test.go:56: close and remove b while a is open
	assert.go:7: [remove b] error: remove C:\Users\Dominic\AppData\Local\Temp\b377287341\._check_writeable: The process cannot access the file because it is being used by another process.
FAIL
FAIL	github.com/ipfs/go-ipfs/repo/fsrepo	2.541s
?   	github.com/ipfs/go-ipfs/repo/fsrepo/lock	[no test files]
?   	github.com/ipfs/go-ipfs/repo/fsrepo/migrations	[no test files]
--- FAIL: TestConfig (0.00s)
	serialize_test.go:31: config file should not be executable or accessible to world: -rw-rw-rw-
FAIL
FAIL	github.com/ipfs/go-ipfs/repo/fsrepo/serialize	0.108s
?   	github.com/ipfs/go-ipfs/routing	[no test files]
--- FAIL: TestGetFailures (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 50682 [running]:
panic(0x888480, 0xc04200e050)
	C:/Go/src/runtime/panic.go:500 +0x1af
testing.tRunner.func1(0xc043181680)
	C:/Go/src/testing/testing.go:579 +0x264
panic(0x888480, 0xc04200e050)
	C:/Go/src/runtime/panic.go:458 +0x251
github.com/ipfs/go-ipfs/routing/dht.TestGetFailures(0xc043181680)
	C:/tmp/src/github.com/ipfs/go-ipfs/routing/dht/ext_test.go:38 +0x16cd
testing.tRunner(0xc043181680, 0x954ba8)
	C:/Go/src/testing/testing.go:610 +0x88
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:646 +0x2f3
FAIL	github.com/ipfs/go-ipfs/routing/dht	9.919s
ok  	github.com/ipfs/go-ipfs/routing/dht/pb	0.993s
ok  	github.com/ipfs/go-ipfs/routing/dht/providers	1.571s
--- FAIL: TestTableFindMultiple (0.00s)
	table_test.go:106: Searching for peer: '<peer.ID VLjwAX>'
	table_test.go:109: Got back different number of peers than we expected.
FAIL
FAIL	github.com/ipfs/go-ipfs/routing/kbucket	0.158s
ok  	github.com/ipfs/go-ipfs/routing/keyspace	0.133s
--- FAIL: TestValidAfter (0.01s)
	centralized_test.go:168: providers []
FAIL
FAIL	github.com/ipfs/go-ipfs/routing/mock	1.930s
?   	github.com/ipfs/go-ipfs/routing/none	[no test files]
?   	github.com/ipfs/go-ipfs/routing/offline	[no test files]
ok  	github.com/ipfs/go-ipfs/routing/record	0.174s
ok  	github.com/ipfs/go-ipfs/routing/supernode	0.145s
?   	github.com/ipfs/go-ipfs/routing/supernode/proxy	[no test files]
?   	github.com/ipfs/go-ipfs/tar	[no test files]
?   	github.com/ipfs/go-ipfs/test/api-startup	[no test files]
?   	github.com/ipfs/go-ipfs/test/bench/bench_cli_ipfs_add	[no test files]
?   	github.com/ipfs/go-ipfs/test/bench/offline_add	[no test files]
?   	github.com/ipfs/go-ipfs/test/dependencies/go-sleep	[no test files]
ok  	github.com/ipfs/go-ipfs/test/integration	16.305s
?   	github.com/ipfs/go-ipfs/test/sharness/lib	[no test files]
?   	github.com/ipfs/go-ipfs/test/supernode_client	[no test files]
?   	github.com/ipfs/go-ipfs/thirdparty/assert	[no test files]
?   	github.com/ipfs/go-ipfs/thirdparty/datastore2	[no test files]
?   	github.com/ipfs/go-ipfs/thirdparty/delay	[no test files]
?   	github.com/ipfs/go-ipfs/thirdparty/dir	[no test files]
ok  	github.com/ipfs/go-ipfs/thirdparty/ipfsaddr	1.102s
?   	github.com/ipfs/go-ipfs/thirdparty/iter	[no test files]
?   	github.com/ipfs/go-ipfs/thirdparty/loggables	[no test files]
?   	github.com/ipfs/go-ipfs/thirdparty/math2	[no test files]
?   	github.com/ipfs/go-ipfs/thirdparty/multierr	[no test files]
ok  	github.com/ipfs/go-ipfs/thirdparty/notifier	3.417s
?   	github.com/ipfs/go-ipfs/thirdparty/peerset	[no test files]
?   	github.com/ipfs/go-ipfs/thirdparty/pollEndpoint	[no test files]
ok  	github.com/ipfs/go-ipfs/thirdparty/pq	0.073s
?   	github.com/ipfs/go-ipfs/thirdparty/tar	[no test files]
?   	github.com/ipfs/go-ipfs/thirdparty/testutil	[no test files]
?   	github.com/ipfs/go-ipfs/thirdparty/testutil/ci	[no test files]
ok  	github.com/ipfs/go-ipfs/thirdparty/testutil/ci/travis	0.122s
?   	github.com/ipfs/go-ipfs/thirdparty/todocounter	[no test files]
ok  	github.com/ipfs/go-ipfs/thirdparty/unit	0.108s
?   	github.com/ipfs/go-ipfs/tour	[no test files]
ok  	github.com/ipfs/go-ipfs/unixfs	0.209s
?   	github.com/ipfs/go-ipfs/unixfs/archive	[no test files]
?   	github.com/ipfs/go-ipfs/unixfs/archive/tar	[no test files]
?   	github.com/ipfs/go-ipfs/unixfs/io	[no test files]
ok  	github.com/ipfs/go-ipfs/unixfs/mod	1.217s
?   	github.com/ipfs/go-ipfs/unixfs/pb	[no test files]
```

**Comment by djdv** [comment]
I'm gonna say Windows coverage has improved enough to close this.
Individual issues can now be opened instead of general ones.
And things look better :^)

```
go test -tags=nofuse "./..." | tee test.log
go: downloading github.com/ipfs/iptb v1.4.0
go: downloading github.com/ipfs/iptb-plugins v0.0.2
go: downloading github.com/jbenet/go-random v0.0.0-20190219211222-123a90aedc0c
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/ipfs/go-ipfs-blocksutil v0.0.1
go: extracting github.com/jbenet/go-random v0.0.0-20190219211222-123a90aedc0c
go: extracting github.com/ipfs/iptb v1.4.0
go: extracting github.com/ipfs/iptb-plugins v0.0.2
go: downloading github.com/urfave/cli v1.20.0
go: downloading github.com/gxed/go-shellwords v1.0.3
go: extracting github.com/fsnotify/fsnotify v1.4.7
go: extracting github.com/ipfs/go-ipfs-blocksutil v0.0.1
go: extracting github.com/gxed/go-shellwords v1.0.3
go: extracting github.com/urfave/cli v1.20.0
?       github.com/ipfs/go-ipfs [no test files]
ok      github.com/ipfs/go-ipfs/assets  0.216s
?       github.com/ipfs/go-ipfs/blocks/blockstoreutil   [no test files]
ok      github.com/ipfs/go-ipfs/cmd/ipfs        0.265s
?       github.com/ipfs/go-ipfs/cmd/ipfs/util   [no test files]
ok      github.com/ipfs/go-ipfs/cmd/ipfswatch   0.221s
?       github.com/ipfs/go-ipfs/cmd/seccat      [no test files]
?       github.com/ipfs/go-ipfs/commands        [no test files]
ok      github.com/ipfs/go-ipfs/core    0.401s
ok      github.com/ipfs/go-ipfs/core/bootstrap  0.217s
ok      github.com/ipfs/go-ipfs/core/commands   0.231s
ok      github.com/ipfs/go-ipfs/core/commands/cmdenv    0.202s
?       github.com/ipfs/go-ipfs/core/commands/dag       [no test files]
?       github.com/ipfs/go-ipfs/core/commands/e [no test files]
?       github.com/ipfs/go-ipfs/core/commands/name      [no test files]
?       github.com/ipfs/go-ipfs/core/commands/object    [no test files]
?       github.com/ipfs/go-ipfs/core/commands/unixfs    [no test files]
?       github.com/ipfs/go-ipfs/core/coreapi    [no test files]
ok      github.com/ipfs/go-ipfs/core/coreapi/test       3.552s
?       github.com/ipfs/go-ipfs/core/coredag    [no test files]
ok      github.com/ipfs/go-ipfs/core/corehttp   0.665s
?       github.com/ipfs/go-ipfs/core/corerepo   [no test files]
ok      github.com/ipfs/go-ipfs/core/coreunix   0.298s
?       github.com/ipfs/go-ipfs/core/mock       [no test files]
?       github.com/ipfs/go-ipfs/core/node       [no test files]
?       github.com/ipfs/go-ipfs/core/node/helpers       [no test files]
?       github.com/ipfs/go-ipfs/core/node/libp2p        [no test files]
ok      github.com/ipfs/go-ipfs/dagutils        0.186s
ok      github.com/ipfs/go-ipfs/filestore       0.355s
?       github.com/ipfs/go-ipfs/filestore/pb    [no test files]
?       github.com/ipfs/go-ipfs/fuse/ipns       [no test files]
?       github.com/ipfs/go-ipfs/fuse/mount      [no test files]
?       github.com/ipfs/go-ipfs/fuse/node       [no test files]
?       github.com/ipfs/go-ipfs/fuse/readonly   [no test files]
ok      github.com/ipfs/go-ipfs/keystore        0.163s
ok      github.com/ipfs/go-ipfs/namesys 0.483s
ok      github.com/ipfs/go-ipfs/namesys/republisher     3.563s
ok      github.com/ipfs/go-ipfs/namesys/resolve 0.266s
?       github.com/ipfs/go-ipfs/p2p     [no test files]
ok      github.com/ipfs/go-ipfs/pin     13.842s
?       github.com/ipfs/go-ipfs/pin/gc  [no test files]
?       github.com/ipfs/go-ipfs/pin/internal/pb [no test files]
?       github.com/ipfs/go-ipfs/plugin  [no test files]
?       github.com/ipfs/go-ipfs/plugin/loader   [no test files]
?       github.com/ipfs/go-ipfs/plugin/plugins/badgerds [no test files]
?       github.com/ipfs/go-ipfs/plugin/plugins/flatfs   [no test files]
?       github.com/ipfs/go-ipfs/plugin/plugins/git      [no test files]
?       github.com/ipfs/go-ipfs/plugin/plugins/levelds  [no test files]
ok      github.com/ipfs/go-ipfs/provider        0.386s
?       github.com/ipfs/go-ipfs/repo    [no test files]
?       github.com/ipfs/go-ipfs/repo/common     [no test files]
ok      github.com/ipfs/go-ipfs/repo/fsrepo     0.297s
ok      github.com/ipfs/go-ipfs/repo/fsrepo/migrations  0.159s
--- FAIL: TestReprovide (0.05s)
    reprovide_test.go:52: Should have gotten a provider
FAIL
FAIL    github.com/ipfs/go-ipfs/reprovide       0.232s
?       github.com/ipfs/go-ipfs/tar     [no test files]
?       github.com/ipfs/go-ipfs/test/api-startup        [no test files]
?       github.com/ipfs/go-ipfs/test/bench/bench_cli_ipfs_add   [no test files]
?       github.com/ipfs/go-ipfs/test/bench/offline_add  [no test files]
?       github.com/ipfs/go-ipfs/test/dependencies/go-sleep      [no test files]
?       github.com/ipfs/go-ipfs/test/dependencies/go-timeout    [no test files]
?       github.com/ipfs/go-ipfs/test/dependencies/iptb  [no test files]
?       github.com/ipfs/go-ipfs/test/dependencies/ma-pipe-unidir        [no test files]
ok      github.com/ipfs/go-ipfs/test/integration        1.469s
?       github.com/ipfs/go-ipfs/thirdparty/assert       [no test files]
?       github.com/ipfs/go-ipfs/thirdparty/cidv0v1      [no test files]
?       github.com/ipfs/go-ipfs/thirdparty/dir  [no test files]
ok      github.com/ipfs/go-ipfs/thirdparty/notifier     0.129s
?       github.com/ipfs/go-ipfs/thirdparty/pollEndpoint [no test files]
ok      github.com/ipfs/go-ipfs/thirdparty/unit 0.051s
?       github.com/ipfs/go-ipfs/thirdparty/verifbs      [no test files]
```
