### ISSUE TITLE
go test failure+panic: exchange/routing/dht

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#3179]
Result of running `go test -tags=nofuse` in 3303fea on Windows/amd64 with Go 1.7
```
--- FAIL: TestGetFailures (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 50682 [running]:
panic(0x888480, 0xc04200e050)
	C:/Go/src/runtime/panic.go:500 +0x1af
testing.tRunner.func1(0xc043181680)
	C:/Go/src/testing/testing.go:579 +0x264
panic(0x888480, 0xc04200e050)
	C:/Go/src/runtime/panic.go:458 +0x251
github.com/ipfs/go-ipfs/routing/dht.TestGetFailures(0xc043181680)
	C:/tmp/src/github.com/ipfs/go-ipfs/routing/dht/ext_test.go:38 +0x16cd
testing.tRunner(0xc043181680, 0x954ba8)
	C:/Go/src/testing/testing.go:610 +0x88
created by testing.(*T).Run
	C:/Go/src/testing/testing.go:646 +0x2f3
FAIL	github.com/ipfs/go-ipfs/routing/dht	9.919s
```

**Comment by whyrusleeping** [comment]
This code has since been extracted to github.com/libp2p/go-libp2p-kad-dht.

Running the tests there, I get failures, but different ones than youre seeing. Going to open an issue over there to track it: https://github.com/libp2p/go-libp2p-kad-dht/issues/86
