### ISSUE TITLE
go test failure+panic: exchange/bitswap/decision

### ISSUE THREAD

**Issue by djdv** [ipfs/go-ipfs#3180]
Result of running `go test -tags=nofuse` in 3303fea on Windows/amd64 with Go 1.7

```
--- FAIL: TestPeerRepeats (0.00s)
    peer_request_queue_test.go:100: [QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP]
    peer_request_queue_test.go:101: [QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP QmSNdT5avfn1FtWzHXMivY2gPvDMyGei8Z9G5Jg1kFRPPP]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x47eb3c]

goroutine 52 [running]:
panic(0x6c02a0, 0xc04200e0a0)
    C:/Go/src/runtime/panic.go:500 +0x1af
testing.tRunner.func1(0xc042080780)
    C:/Go/src/testing/testing.go:579 +0x264
panic(0x6c02a0, 0xc04200e0a0)
    C:/Go/src/runtime/panic.go:458 +0x251
github.com/ipfs/go-ipfs/exchange/bitswap/decision.TestPeerRepeats(0xc042080780)
    C:/tmp/src/github.com/ipfs/go-ipfs/exchange/bitswap/decision/peer_request_queue_test.go:116 +0xcdc
testing.tRunner(0xc042080780, 0x742218)
    C:/Go/src/testing/testing.go:610 +0x88
created by testing.(*T).Run
    C:/Go/src/testing/testing.go:646 +0x2f3
FAIL    github.com/ipfs/go-ipfs/exchange/bitswap/decision   10.988s

```

**Comment by whyrusleeping** [comment]
Hrm, I cannot reproduce this (windows 10 VM). I'm going to assume the issue has since been fixed. Please reopen if you encounter it again
