### ISSUE TITLE
panic from NAT library

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#3205]
Looks like something wonky is going on in our NAT code.

cc @Kubuxu 

```
Initializing daemon...
Swarm listening on /ip4/10.0.1.12/tcp/4001
Swarm listening on /ip4/10.0.1.12/tcp/4002/ws
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/tcp/4002/ws
Swarm listening on /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
fatal error: concurrent map writes

goroutine 238 [running]:
runtime.throw(0xced983, 0x15)
        /home/whyrusleeping/go/src/runtime/panic.go:566 +0x95 fp=0xc421d6bcb0 sp=0xc421d6bc90
runtime.mapassign1(0xbeaf20, 0xc421cf3e90, 0xc421d6be18, 0xc421d6be10)
        /home/whyrusleeping/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc421d6bd98 sp=0xc421d6bcb0
gx/ipfs/QmYabcy8kaP658zZRZHLqRquJ37ycNWr4qhBL25tUodZWc/go-nat.(*natpmpNAT).AddPortMapping(0xc421cf3ec0, 0xcd9c00, 0x3, 0xfa2, 0xcda77a, 0x4, 0xdf8475800, 0x0, 0x0, 0x0)
        /home/whyrusleeping/gopkg/src/gx/ipfs/QmYabcy8kaP658zZRZHLqRquJ37ycNWr4qhBL25tUodZWc/go-nat/natpmp.go:91 +0x289 fp=0xc421d6be30 sp=0xc421d6bd98
gx/ipfs/QmXnaDLonE9YBTVDdWBM6Jb5YxxmW1MHMkXzgsnu1jTEmK/go-libp2p/p2p/nat.(*NAT).establishMapping(0xc4201c0d20, 0xc42007d980)
        /home/whyrusleeping/gopkg/src/gx/ipfs/QmXnaDLonE9YBTVDdWBM6Jb5YxxmW1MHMkXzgsnu1jTEmK/go-libp2p/p2p/nat/nat.go:337 +0x240 fp=0xc421d6bf50 sp=0xc421d6be30
gx/ipfs/QmXnaDLonE9YBTVDdWBM6Jb5YxxmW1MHMkXzgsnu1jTEmK/go-libp2p/p2p/nat.(*NAT).NewMapping.func2(0x1125560, 0xc421e502a0)
        /home/whyrusleeping/gopkg/src/gx/ipfs/QmXnaDLonE9YBTVDdWBM6Jb5YxxmW1MHMkXzgsnu1jTEmK/go-libp2p/p2p/nat/nat.go:325 +0x33 fp=0xc421d6bf70 sp=0xc421d6bf50
gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess.(*process).Go.func1(0xc42028bc00, 0xc421e502a0, 0xc421e503c0)
        /home/whyrusleeping/gopkg/src/gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess/impl-mutex.go:112 +0x3c fp=0xc421d6bf98 sp=0xc421d6bf70
runtime.goexit()
        /home/whyrusleeping/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc421d6bfa0 sp=0xc421d6bf98
created by gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess.(*process).Go
        /home/whyrusleeping/gopkg/src/gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess/impl-mutex.go:115 +0x375
```

**Comment by Kubuxu** [comment]
Resolved with update in of go-nat.
