### ISSUE TITLE
IpfsNodeCollector crashes in offline mode

### ISSUE THREAD

**Issue by lgierth** [ipfs/go-ipfs#3364]
#### Description:

Requests to :5001/debug/metrics/prometheus crash the daemon:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x55c73cd17b98]

goroutine 94 [running]:
panic(0x55c73d667a60, 0xc420010080)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/ipfs/go-ipfs/core/corehttp.IpfsNodeCollector.PeersTotalValues(0xc42034c2c0, 0x0)
	/go/src/github.com/ipfs/go-ipfs/core/corehttp/metrics.go:56 +0x78
github.com/ipfs/go-ipfs/core/corehttp.IpfsNodeCollector.Collect(0xc42034c2c0, 0xc4222453e0)
	/go/src/github.com/ipfs/go-ipfs/core/corehttp/metrics.go:44 +0x42
github.com/ipfs/go-ipfs/core/corehttp.(*IpfsNodeCollector).Collect(0xc420124288, 0xc4222453e0)
	<autogenerated>:2 +0x5e
gx/ipfs/QmdhsRK1EK2fvAz2i2SH5DEfkL6seDuyMYEsxKa9Braim3/client_golang/prometheus.(*registry).writePB.func2(0xc421e608d0, 0xc4222453e0, 0x55c73dafe180, 0xc420124288)
	/go/src/gx/ipfs/QmdhsRK1EK2fvAz2i2SH5DEfkL6seDuyMYEsxKa9Braim3/client_golang/prometheus/registry.go:415 +0x65
created by gx/ipfs/QmdhsRK1EK2fvAz2i2SH5DEfkL6seDuyMYEsxKa9Braim3/client_golang/prometheus.(*registry).writePB
	/go/src/gx/ipfs/QmdhsRK1EK2fvAz2i2SH5DEfkL6seDuyMYEsxKa9Braim3/client_golang/prometheus/registry.go:416 +0x285
```

**Comment by whyrusleeping** [comment]
huh, nice find

**Comment by Kubuxu** [comment]
I think I have fixed it some time ago.

**Comment by Kubuxu** [comment]
I think that now other value is nil in this case.
Also we need regression test for that.

**Comment by lgierth** [comment]
Yep this is indeed fixed on master -- thanks @Kubuxu!
