### ISSUE TITLE
Crash when go-ipfs@0.4.4 talks to a 0.4.3 daemon

### ISSUE THREAD

**Issue by jbenet** [ipfs/go-ipfs#3452]
A 0.4.4 cli tool talks to a 0.4.3 daemon:

```
goroutine 1 [running]:
runtime/debug.Stack(0xd98df0, 0x42122ac60, 0x42122a7e0)
	/home/whyrusleeping/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/home/whyrusleeping/go/src/runtime/debug/stack.go:16 +0x22
gx/ipfs/QmZNVWh8LLjAavuQ2JXuFmuYH3C11xo988vSgp7UQrTRj1/go-ipfs-util.ErrCast(0x421228380, 0x7e3860)
	/builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZNVWh8LLjAavuQ2JXuFmuYH3C11xo988vSgp7UQrTRj1/go-ipfs-util/util.go:34 +0x14
github.com/ipfs/go-ipfs/core/commands.glob..func7(0xce8a20, 0x42109a480, 0xce7de0, 0x421228380)
	/builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/add.go:223 +0xd64
main.callCommand(0xce2a20, 0x4211c1d00, 0xce8a20, 0x42109a480, 0xdbc120, 0xd99260, 0x0, 0x0, 0x4211b5e60, 0x85d0)
	/builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:355 +0x51f
main.(*cmdInvocation).Run(0x4211c1c40, 0xce2a20, 0x4211c1d00, 0xcd7ae0, 0x4211e77e0, 0xce2a20, 0x4211c1d00)
	/builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:193 +0x116
main.main()
	/builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:158 +0x373
Error: cast error
make: *** [publish] Error 1
```

**Comment by jbenet** [comment]
Of course, this should not happen. it should be a nice error.

**Comment by whyrusleeping** [comment]
Yeah... we just need to stop using that stupid `CastError` thing. Its whats generating that stack trace.
