### ISSUE TITLE
Panic in flat-fs datastore

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3454]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x8402aa]

goroutine 24 [running]:
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs.(*Datastore).Query.func1.1(0xc82007ee10, 0x8b, 0x0, 0x0, 0x2aeeb0b65270, 0xc8206fd2f0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs/flatfs.go:323 +0x5a
path/filepath.walk(0xc8202bb300, 0x7d, 0x2aeeb0b66d00, 0xc8202ad810, 0xc82003ff80, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:370 +0x415
path/filepath.walk(0xc82001a780, 0x74, 0x2aeeb0b66d00, 0xc8202acd70, 0xc82003ff80, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:374 +0x4fc
path/filepath.Walk(0xc82001a780, 0x74, 0xc82003ff80, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:396 +0xe1
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs.(*Datastore).Query.func1(0xc8200ea180, 0xc8201ee560)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs/flatfs.go:321 +0x91
created by gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs.(*Datastore).Query
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs/flatfs.go:343 +0x152

goroutine 1 [runnable]:
syscall.Syscall(0x3, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Close(0xf, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:296 +0x4a
os.(*file).close(0xc8206f9170, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:126 +0x61
os.(*File).Close(0xc82012e130, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:118 +0x54
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs.syncDir(0xc82001ac80, 0x7d, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs/sync_std.go:16 +0xe0
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs.(*Datastore).putMany(0xc8201ee560, 0xc8206f9050, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs/flatfs.go:255 +0x90b
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs.(*flatfsBatch).Commit(0xc8201ef840, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/flatfs/flatfs.go:377 +0x4e
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/measure.logBatchCommit(0x2aeeb17ecbe8, 0xc8201ef840, 0x1, 0xc820018820, 0x4e, 0xc820018870, 0x4e, 0xc8201d5640, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/measure/measure.go:210 +0x7d
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/measure.(*measuredBatch).Commit(0xc82004fe00, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/measure/measure.go:199 +0x164
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/syncmount.(*mountBatch).Commit(0xc8201ef760, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/syncmount/mount.go:192 +0xba
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/measure.logBatchCommit(0x2aeeb17ecaf0, 0xc8201ef760, 0x1, 0xc8200194a0, 0x47, 0xc8200194f0, 0x47, 0xc8200f6400, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/measure/measure.go:210 +0x7d
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/measure.(*measuredBatch).Commit(0xc82004fdc0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/measure/measure.go:199 +0x164
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/keytransform.(*transformBatch).Commit(0xc8201ef7c0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/keytransform/keytransform.go:117 +0x45
github.com/ipfs/go-ipfs/blocks/blockstore.(*blockstore).PutMany(0xc8200f6c00, 0xc8202b1450, 0x1, 0x1, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/blocks/blockstore/blockstore.go:124 +0x20f
github.com/ipfs/go-ipfs/blocks/blockstore.(*bloomcache).PutMany(0xc82001a380, 0xc8202b1450, 0x1, 0x1, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/blocks/blockstore/bloom_cache.go:82 +0x1af
github.com/ipfs/go-ipfs/blocks/blockstore.(*writecache).PutMany(0xc8201eeec0, 0xc8202b1420, 0x1, 0x1, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/blocks/blockstore/write_cache.go:61 +0x3f2
github.com/ipfs/go-ipfs/blockservice.(*BlockService).AddBlocks(0xc8201eeee0, 0xc8202b1420, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/blockservice/blockservice.go:57 +0xa8
github.com/ipfs/go-ipfs/merkledag.(*Batch).Commit(0xc8206f8a80, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/merkledag/merkledag.go:351 +0x52
github.com/ipfs/go-ipfs/importer/helpers.(*DagBuilderHelper).Close(0xc8202c54a0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/importer/helpers/dagbuilder.go:128 +0x31
github.com/ipfs/go-ipfs/importer/trickle.TrickleAppend.func1(0xc8201956d0, 0xc8202c54a0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/importer/trickle/trickledag.go:72 +0x2f
github.com/ipfs/go-ipfs/importer/trickle.TrickleAppend(0x2aeeb0b6b270, 0xc820013260, 0xc8202c5380, 0xc8202c54a0, 0xc8202c5380, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/importer/trickle/trickledag.go:93 +0x203
github.com/ipfs/go-ipfs/unixfs/mod.(*DagModifier).appendData(0xc8202c53e0, 0xc8202c5380, 0x2aeeb17eca00, 0xc8206f8a50, 0x1574b50, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/unixfs/mod/dagmodifier.go:287 +0xca
github.com/ipfs/go-ipfs/unixfs/mod.(*DagModifier).expandSparse(0xc8202c53e0, 0x2b, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/unixfs/mod/dagmodifier.go:106 +0x231
github.com/ipfs/go-ipfs/unixfs/mod.(*DagModifier).Seek(0xc8202c53e0, 0x32, 0x0, 0xc820155b60, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/unixfs/mod/dagmodifier.go:381 +0xf4
github.com/ipfs/go-ipfs/mfs.(*fileDescriptor).Seek(0xc8201ef4e0, 0x32, 0x0, 0x2aeeb0b66868, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/mfs/fd.go:141 +0x45
github.com/ipfs/go-ipfs/core/commands/files.glob.func2(0x2aeeb0b6b368, 0xc8200fc780, 0x2aeeb0b6b5a0, 0xc8201f7ce0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/core/commands/files/files.go:634 +0x72c
github.com/ipfs/go-ipfs/commands.(*Command).Call(0x154e140, 0x2aeeb0b6b368, 0xc8200fc780, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/commands/command.go:110 +0x471
main.callCommand(0x2aeeb0b6b510, 0xc820211300, 0x2aeeb0b6b368, 0xc8200fc780, 0x154e140, 0x152f560, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:346 +0xa84
main.(*cmdInvocation).Run(0xc820211240, 0x2aeeb0b6b510, 0xc820211300, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:189 +0x1e5
main.main()
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:154 +0x660

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 6 [chan receive]:
gx/ipfs/QmV3NSS3A1kX5s28r7yLczhDsXzkgo65cqRgKFXYunWZmD/metrics.init.1.func2()
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmV3NSS3A1kX5s28r7yLczhDsXzkgo65cqRgKFXYunWZmD/metrics/metrics.go:321 +0x73
created by gx/ipfs/QmV3NSS3A1kX5s28r7yLczhDsXzkgo65cqRgKFXYunWZmD/metrics.init.1
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmV3NSS3A1kX5s28r7yLczhDsXzkgo65cqRgKFXYunWZmD/metrics/metrics.go:328 +0x7b

goroutine 7 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [select]:
gx/ipfs/QmYtB7Qge8cJpXc4irsEp8zRqfnZMBeB7aTrMEkPk67DRv/go-log.(*MirrorWriter).logRoutine(0xc8200148c0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmYtB7Qge8cJpXc4irsEp8zRqfnZMBeB7aTrMEkPk67DRv/go-log/writer.go:71 +0x33c
created by gx/ipfs/QmYtB7Qge8cJpXc4irsEp8zRqfnZMBeB7aTrMEkPk67DRv/go-log.NewMirrorWriter
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmYtB7Qge8cJpXc4irsEp8zRqfnZMBeB7aTrMEkPk67DRv/go-log/writer.go:38 +0xe2

goroutine 9 [select]:
gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log.(*MirrorWriter).logRoutine(0xc820014940)
	/home/ubuntu/.go_workspace/src/gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log/writer.go:71 +0x33c
created by gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log.NewMirrorWriter
	/home/ubuntu/.go_workspace/src/gx/ipfs/Qmazh5oNUVsDZTs2g59rq8aYQqwpss8tcUWQzor5sCCEuH/go-log/writer.go:38 +0xe2

goroutine 10 [select]:
gx/ipfs/QmNQynaz7qfriSUJkiEZUrm2Wen1u3Kj9goZzWtrPyu7XR/go-log.(*MirrorWriter).logRoutine(0xc820015d40)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmNQynaz7qfriSUJkiEZUrm2Wen1u3Kj9goZzWtrPyu7XR/go-log/writer.go:71 +0x33c
created by gx/ipfs/QmNQynaz7qfriSUJkiEZUrm2Wen1u3Kj9goZzWtrPyu7XR/go-log.NewMirrorWriter
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmNQynaz7qfriSUJkiEZUrm2Wen1u3Kj9goZzWtrPyu7XR/go-log/writer.go:38 +0xe2

goroutine 20 [select]:
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb.(*DB).mpoolDrain(0xc820113200)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/db_state.go:97 +0x14b
created by gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb.openDB
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/db.go:142 +0x6f4

goroutine 19 [select]:
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb.(*DB).compactionError(0xc820113200)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/db_compaction.go:90 +0x54a
created by gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb.openDB
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/db.go:141 +0x6d2

goroutine 34 [select, locked to thread]:
runtime.gopark(0x10edcd0, 0xc820027f28, 0xf29570, 0x6, 0x43e318, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820027f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820027f28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 35 [chan receive]:
main.(*IntrHandler).Handle.func1(0xc8202b23c0, 0xc8202b05b0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:542 +0x9a
created by main.(*IntrHandler).Handle
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:547 +0x95

goroutine 36 [select]:
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/util.(*BufferPool).drain(0xc8200dec40)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/util/buffer_pool.go:206 +0x29d
created by gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/util.NewBufferPool
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/util/buffer_pool.go:237 +0x26b

goroutine 21 [select]:
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb.(*DB).tCompaction(0xc820113200)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/db_compaction.go:804 +0x7fe
created by gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb.openDB
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/db.go:148 +0x8f8

goroutine 22 [select]:
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb.(*DB).mCompaction(0xc820113200)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/db_compaction.go:751 +0x253
created by gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb.openDB
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/db.go:149 +0x91a

goroutine 23 [select]:
gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb.(*DB).jWriter(0xc820113200)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/db_write.go:37 +0x1a2
created by gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb.openDB
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmbBhyDKsY4mbY6xsKt3qu9Y7FPvMJ6qbD8AMjYYvPRw1g/goleveldb/leveldb/db.go:150 +0x93c

goroutine 50 [chan receive]:
github.com/ipfs/go-ipfs/blocks/blockstore.(*bloomcache).Rebuild(0xc82001a380)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/blocks/blockstore/bloom_cache.go:48 +0x290
created by github.com/ipfs/go-ipfs/blocks/blockstore.BloomCached
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/blocks/blockstore/bloom_cache.go:17 +0x1be

goroutine 51 [select]:
github.com/ipfs/go-ipfs/mfs.(*Republisher).Run(0xc8201c8850)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/mfs/system.go:244 +0x4e5
created by github.com/ipfs/go-ipfs/mfs.NewRoot
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/mfs/system.go:77 +0x144

goroutine 27 [runnable]:
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/query.ResultsWithChan.func1(0x2aeeb0b658e0, 0xc8200eaea0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/query/query.go:202 +0x2bc
gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess.(*process).Go.func1(0xc8201ea100, 0xc8200eaea0, 0xc8200eb260)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess/impl-mutex.go:112 +0x51
created by gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess.(*process).Go
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess/impl-mutex.go:115 +0x3eb

goroutine 28 [chan receive]:
gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess.(*process).CloseAfterChildren(0xc8200ea9c0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess/impl-mutex.go:266 +0x288
created by gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/query.ResultsWithChan
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/query/query.go:220 +0x12e

goroutine 29 [chan receive]:
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/keytransform.(*ktds).Query.func1(0xc8200eb2c0, 0x2aeeb17a8e98, 0xc8201f60e0, 0xc8201ea0e0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/keytransform/keytransform.go:68 +0x107
created by gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/keytransform.(*ktds).Query
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/keytransform/keytransform.go:74 +0x156

goroutine 30 [chan receive]:
gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/namespace.(*datastore).Query.func1(0xc8200eb320, 0x2aeeb17a8e98, 0xc8201f61c0, 0xc8206f4f60)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/namespace/namespace.go:66 +0x10a
created by gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/namespace.(*datastore).Query
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmZ6A6P6AMo8SR3jXAwzTuSU6B9R2Y4eqW2yW9VvfUayDN/go-datastore/namespace/namespace.go:80 +0x157

goroutine 31 [select]:
github.com/ipfs/go-ipfs/blocks/blockstore.(*blockstore).AllKeysChan.func1(0x0, 0x0, 0xc8201b7ec8)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/blocks/blockstore/blockstore.go:152 +0x699
github.com/ipfs/go-ipfs/blocks/blockstore.(*blockstore).AllKeysChan.func2(0x2aeeb17a8e98, 0xc8201f6230, 0xc8200eb380, 0xc8206fc180, 0x2aeeb0b6b270, 0xc820013260)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/blocks/blockstore/blockstore.go:186 +0x74
created by github.com/ipfs/go-ipfs/blocks/blockstore.(*blockstore).AllKeysChan
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/blocks/blockstore/blockstore.go:200 +0x235
```

**Comment by whyrusleeping** [comment]
what version of ipfs?

**Comment by whyrusleeping** [comment]
Yeah... the code involved here is quite old. Where did this come from?

**Comment by Kubuxu** [comment]
go-ipfs-api build, I think. So it might be using 0.4.3

**Comment by Kubuxu** [comment]
Was that resolved?

**Comment by whyrusleeping** [comment]
Yeah, the problem is that the error wasnt being checked during the `fs.Walk`, resulting in us potentially having a nil filestat

**Comment by Kubuxu** [comment]
Ahh, I even might be one that fixed it. :p
