### ISSUE TITLE
ipfs daemon --mount --offline can panic

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3525]
```
Initializing daemon...
Swarm not listening, running in offline mode.
API server listening on /ip4/127.0.0.1/tcp/53573
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/55078
> cat daemon_err
Error: mount is not currently supported in offline mode
Use 'ipfs daemon --help' for information about this command
panic: Process cannot add children after being closed

goroutine 94 [running]:
panic(0xbc6580, 0xc42027a590)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess.(*process).AddChild(0xc420016720, 0x1153ac0, 0xc420320a20)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess/impl-mutex.go:86 +0x384
gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess.(*process).Go(0xc420016720, 0xc42011b040, 0xc420320900, 0xc420268be0)
	/home/ubuntu/.go_workspace/src/gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess/impl-mutex.go:110 +0x33c
github.com/ipfs/go-ipfs/core/corehttp.Serve(0xc420152180, 0x114c520, 0xc420118360, 0xc42001db30, 0x9, 0x9, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/core/corehttp/corehttp.go:85 +0x23a
main.serveHTTPApi.func1(0xc420016d80, 0xc420152180, 0x114ff00, 0xc42016e9c0, 0xc42001db30, 0x9, 0x9)
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:490 +0x7e
created by main.serveHTTPApi
	/home/ubuntu/.go_workspace/src/github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:492 +0xb66
test_expect_code: command exited with 2, we wanted 1 ipfs daemon --offline --mount

not ok 15 - ipfs daemon --offline --mount fails - #2995
#	
#		test_expect_code 1 ipfs daemon --offline --mount 2>daemon_err &&
#		grep "mount is not currently supported in offline mode" daemon_err ||
#		test_fsh cat daemon_err
#
```

**Comment by whyrusleeping** [comment]
@Kubuxu Has this been resolved? I seem to remember you PRing something like this in

**Comment by Kubuxu** [comment]
Yes, duplicate was marked as resolved.
