### ISSUE TITLE
namesys concurrent map write test failure

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/go-ipfs#3731]
```
fatal error: concurrent map writes

goroutine 30 [running]:
runtime.throw(0x85e38d, 0x15)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42016fc48 sp=0xc42016fc28
runtime.mapassign1(0x7eab80, 0xc4204d9560, 0xc42016fd60, 0xc42016fd50)
	/usr/local/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc42016fd30 sp=0xc42016fc48
gx/ipfs/QmRWDav6mzWseLWeYfVd5fvUKiVe9xNH29YfMF438fG364/go-datastore.(*MapDatastore).Put(0xc4204cc010, 0xc4201c60f0, 0x41, 0x7b8f80, 0xc420166380, 0x30, 0x0)
	/go/src/gx/ipfs/QmRWDav6mzWseLWeYfVd5fvUKiVe9xNH29YfMF438fG364/go-datastore/basic_ds.go:28 +0x7a fp=0xc42016fd80 sp=0xc42016fd30
github.com/ipfs/go-ipfs/routing/offline.(*offlineRouting).PutValue(0xc42024f740, 0xa51160, 0xc42015a060, 0xc420209110, 0x28, 0xc4200c0180, 0xdd, 0x180, 0x1, 0x481a50)
	/go/src/github.com/ipfs/go-ipfs/routing/offline/offline.go:51 +0x203 fp=0xc42016fe58 sp=0xc42016fd80
github.com/ipfs/go-ipfs/namesys.PublishEntry(0xa510e0, 0xc420295900, 0x7f7c39d0a238, 0xc42024f740, 0xc420209110, 0x28, 0xc420479a80, 0x0, 0x0)
	/go/src/github.com/ipfs/go-ipfs/namesys/publisher.go:214 +0x244 fp=0xc42016fef8 sp=0xc42016fe58
github.com/ipfs/go-ipfs/namesys.PutRecordToRouting.func1(0xc420156a20, 0xa510e0, 0xc420295900, 0x7f7c39d0a238, 0xc42024f740, 0xc420209110, 0x28, 0xc420479a80)
	/go/src/github.com/ipfs/go-ipfs/namesys/publisher.go:156 +0x7a fp=0xc42016ff60 sp=0xc42016fef8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42016ff68 sp=0xc42016ff60
created by github.com/ipfs/go-ipfs/namesys.PutRecordToRouting
	/go/src/github.com/ipfs/go-ipfs/namesys/publisher.go:157 +0x2b6

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420094240, 0x85e252, 0x15, 0x88d878, 0xc420053d01)
	/usr/local/go/src/testing/testing.go:647 +0x316
testing.RunTests.func1(0xc420094240)
	/usr/local/go/src/testing/testing.go:793 +0x6d
testing.tRunner(0xc420094240, 0xc42003ee30)
	/usr/local/go/src/testing/testing.go:610 +0x81
testing.RunTests(0x88df08, 0xaf80c0, 0x8, 0x8, 0x20)
	/usr/local/go/src/testing/testing.go:799 +0x319
testing.(*M).Run(0xc42003eef8, 0x0)
	/usr/local/go/src/testing/testing.go:743 +0x85
main.main()
	github.com/ipfs/go-ipfs/namesys/_test/_testmain.go:68 +0xc6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [select]:
gx/ipfs/QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52/go-log.(*MirrorWriter).logRoutine(0xc4200147c0)
	/go/src/gx/ipfs/QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52/go-log/writer.go:71 +0x32e
created by gx/ipfs/QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52/go-log.NewMirrorWriter
	/go/src/gx/ipfs/QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52/go-log/writer.go:38 +0xf1

goroutine 29 [select]:
github.com/ipfs/go-ipfs/namesys.waitOnErrChan(0xa510e0, 0xc420295900, 0xc420156a20, 0xa510e0, 0xc420295900)
	/go/src/github.com/ipfs/go-ipfs/namesys/publisher.go:177 +0x149
github.com/ipfs/go-ipfs/namesys.PutRecordToRouting(0xa510e0, 0xc420295900, 0xa51f80, 0xc42013a740, 0xc420295800, 0x34, 0x1, 0xed0487e49, 0x18b228eb, 0xb0e700, ...)
	/go/src/github.com/ipfs/go-ipfs/namesys/publisher.go:163 +0x368
github.com/ipfs/go-ipfs/namesys.(*ipnsPublisher).PublishWithEOL(0xc42024f780, 0xa51120, 0xc42000c590, 0xa51f80, 0xc42013a740, 0xc420295800, 0x34, 0xed0487e49, 0xc418b228eb, 0xb0e700, ...)
	/go/src/github.com/ipfs/go-ipfs/namesys/publisher.go:80 +0x1f0
github.com/ipfs/go-ipfs/namesys.(*ipnsPublisher).Publish(0xc42024f780, 0xa51120, 0xc42000c590, 0xa51f80, 0xc42013a740, 0xc420295800, 0x34, 0x1, 0xc42013a7c0)
	/go/src/github.com/ipfs/go-ipfs/namesys/publisher.go:57 +0x1a7
github.com/ipfs/go-ipfs/namesys.(*mpns).Publish(0xc42013a750, 0xa51120, 0xc42000c590, 0xa51f80, 0xc42013a740, 0xc420295800, 0x34, 0x0, 0xc420030720)
	/go/src/github.com/ipfs/go-ipfs/namesys/namesys.go:92 +0xac
github.com/ipfs/go-ipfs/namesys.TestPublishWithCache0(0xc42020a3c0)
	/go/src/github.com/ipfs/go-ipfs/namesys/namesys_test.go:91 +0x25a
testing.tRunner(0xc42020a3c0, 0x88d878)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec

goroutine 31 [runnable]:
gx/ipfs/QmRWDav6mzWseLWeYfVd5fvUKiVe9xNH29YfMF438fG364/go-datastore.(*MapDatastore).Put(0xc4204cc010, 0xc420295c80, 0x3e, 0x7b8f80, 0xc420155400, 0x30, 0x0)
	/go/src/gx/ipfs/QmRWDav6mzWseLWeYfVd5fvUKiVe9xNH29YfMF438fG364/go-datastore/basic_ds.go:28 +0x7a
github.com/ipfs/go-ipfs/routing/offline.(*offlineRouting).PutValue(0xc42024f740, 0xa51160, 0xc420156ae0, 0xc4202090e0, 0x26, 0xc4201582c0, 0xa7, 0xb0, 0x410b68, 0x8)
	/go/src/github.com/ipfs/go-ipfs/routing/offline/offline.go:51 +0x203
github.com/ipfs/go-ipfs/namesys.PublishPublicKey(0xa510e0, 0xc420295900, 0x7f7c39d0a238, 0xc42024f740, 0xc4202090e0, 0x26, 0xa51460, 0xc4204cc030, 0x0, 0x0)
	/go/src/github.com/ipfs/go-ipfs/namesys/publisher.go:195 +0x241
github.com/ipfs/go-ipfs/namesys.PutRecordToRouting.func2(0xc420156a20, 0xa510e0, 0xc420295900, 0x7f7c39d0a238, 0xc42024f740, 0xc4202090e0, 0x26, 0xa51f80, 0xc42013a740)
	/go/src/github.com/ipfs/go-ipfs/namesys/publisher.go:160 +0x9e
created by github.com/ipfs/go-ipfs/namesys.PutRecordToRouting
	/go/src/github.com/ipfs/go-ipfs/namesys/publisher.go:161 +0x33d
FAIL	github.com/ipfs/go-ipfs/namesys	0.144s
```

**Comment by Kubuxu** [comment]
It is probably because MapDatastore is not thread safe. Wrapping it in `go-datastore/sync.MutexWrap` should solve the issue.

**Comment by Stebalien** [comment]
Looks identical to #4018. Closing as fixed.
