### ISSUE TITLE
Daemon crashes after a number of uploads

### ISSUE THREAD

**Issue by koffisam** [ipfs/go-ipfs#4021]
#### Version information:
root@ipfs:~# ipfs version --all
go-ipfs version: 0.4.4-
Repo version: 4
System version: amd64/linux
Golang version: go1.7

#### Description:
I am using the Node module ipfs-api to upload files. I noticed that after a number of uploads the daemon crashes with the following log:

```
panic: Process cannot add children after being closed

goroutine 376 [running]:
panic(0xb91d60, 0xc421f24ab0)
	/home/whyrusleeping/go/src/runtime/panic.go:500 +0x1a1
gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess.(*process).AddChild(0xc4201703c0, 0x10ed100, 0xc421f8e780)
	/builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess/impl-mutex.go:86 +0x384
gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess.(*process).Go(0xc4201703c0, 0xc421fc8300, 0xc421f8e660, 0xc421f96860)
	/builds/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmQopLATEYMNg7dVqZRNDfeE2S1yKy8zrRh5xnYiuqeZBn/goprocess/impl-mutex.go:110 +0x33c
github.com/ipfs/go-ipfs/core/corehttp.Serve(0xc4200846e0, 0x10e5ee0, 0xc42002c2c0, 0xc421e92e10, 0x9, 0x9, 0x0, 0x0)
	/builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/corehttp/corehttp.go:85 +0x23a
main.serveHTTPApi.func1(0xc421f8e2a0, 0xc4200846e0, 0x10e98a0, 0xc421f19c20, 0xc421e92e10, 0x9, 0x9)
	/builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:450 +0x7e
created by main.serveHTTPApi
	/builds/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:452 +0xc28

```

**Comment by lgierth** [comment]
Please update to the latest release of go-ipfs (0.4.9 from dist.ipfs.io) and try again

**Comment by lgierth** [comment]
Please reopen this issue with more information then, in case it continues to crash.
