### ISSUE TITLE
Pubsub panic - send on closed channel

### ISSUE THREAD

**Issue by mateon1** [ipfs/go-ipfs#4066]
#### Description:
IPFS panicked with the following message when pubsub was used.

```
panic: send on closed channel

goroutine 2828634 [running]:
gx/ipfs/QmYPKo97ssdv3Bsk9sRAS5ZjahGg9Stzys3vybu3r7VuB5/floodsub.(*PubSub).publishMessage.func1(0xc4242ef320, 0xc42312faa0)
        /tmp/nix-build-ipfs-0.4.9.drv-0/go/src/gx/ipfs/QmYPKo97ssdv3Bsk9sRAS5ZjahGg9Stzys3vybu3r7VuB5/floodsub/floodsub.go:346 +0x4b
created by gx/ipfs/QmYPKo97ssdv3Bsk9sRAS5ZjahGg9Stzys3vybu3r7VuB5/floodsub.(*PubSub).publishMessage
        /tmp/nix-build-ipfs-0.4.9.drv-0/go/src/gx/ipfs/QmYPKo97ssdv3Bsk9sRAS5ZjahGg9Stzys3vybu3r7VuB5/floodsub/floodsub.go:346 +0x2fd
```

This is not easily reproducible, the daemon was online for several days, including a 20 minute long loss of internet connection.

**Comment by whyrusleeping** [comment]
@vyzo @Stebalien any idea on this one?

**Comment by Stebalien** [comment]
Fix: https://github.com/libp2p/go-floodsub/pull/34. Would you like me to do a gx release and propagate it or are you fine waiting?
