### ISSUE TITLE
Crashing during download

### ISSUE THREAD

**Issue by zinid** [ipfs/go-ipfs#4160]
#### Version information:
go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/linux
Golang version: go1.8.3

#### Type:
Bug

#### Severity:
Critical
#### Description:

So I uploaded a file (550Mb) at one server:
```
$ ipfs add filename
added QmZnLMNSVVs3kmRp5CJU1pnKygwRNzSo8MGuuQEUpPg7tX filename
```
Then I try to download it on another server using the following command:
```
$ ipfs get /ipfs/QmZnLMNSVVs3kmRp5CJU1pnKygwRNzSo8MGuuQEUpPg7tX
```
But I always either get `Error: http: unexpected EOF reading trailer` with automatic daemon termination, or I have a crash like this:
```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7fc479e9dfdf m=0 sigcode=18446744073709551610

goroutine 0 [idle]:

goroutine 1 [runnable, locked to thread]:
runtime.init.2()
        /home/whyrusleeping/go/src/runtime/mstats.go:424 +0xca
runtime.init()
        /home/whyrusleeping/go/src/runtime/write_err.go:14 +0xa0
runtime.main()
        /home/whyrusleeping/go/src/runtime/proc.go:141 +0xf6
runtime.goexit()
        /home/whyrusleeping/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/whyrusleeping/go/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x6
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x2
rsi    0x7fffb0f42840
rbp    0xf5d3ab
rsp    0x7fffb0f428b8
r8     0x0
r9     0x7fffb0f42840
r10    0x8
r11    0x246
r12    0x1c24050
r13    0x34
r14    0x0
r15    0xf3
rip    0x7fc479e9dfdf
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by zinid** [comment]
Got another crash of `ipfs get` (if that matters). Note that in this case daemon is not dead:
```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f90319f1fdf m=0 sigcode=18446744073709551610

goroutine 0 [idle]:

goroutine 8 [syscall]:
runtime.notetsleepg(0x145e438, 0x3b98c344, 0x0)
        /home/whyrusleeping/go/src/runtime/lock_futex.go:205 +0x42 fp=0xc420023f60 sp=0xc420023f30
runtime.timerproc()
        /home/whyrusleeping/go/src/runtime/time.go:209 +0x327 fp=0xc420023fe0 sp=0xc420023f60
runtime.goexit()
        /home/whyrusleeping/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420023fe8 sp=0xc420023fe0
created by runtime.addtimerLocked
        /home/whyrusleeping/go/src/runtime/time.go:116 +0xed

goroutine 1 [select]:
net/http.(*persistConn).roundTrip(0xc4204fa900, 0xc4204810c0, 0x0, 0x0, 0x0)
        /home/whyrusleeping/go/src/net/http/transport.go:1898 +0x974
net/http.(*Transport).RoundTrip(0x1438620, 0xc42049d600, 0x1438620, 0x0, 0x0)
        /home/whyrusleeping/go/src/net/http/transport.go:391 +0x74c
net/http.send(0xc42049d600, 0x135c900, 0x1438620, 0x0, 0x0, 0x0, 0x0, 0x8, 0xc42000e258, 0x4115e8)
        /home/whyrusleeping/go/src/net/http/client.go:249 +0x162
net/http.(*Client).send(0x145e220, 0xc42049d600, 0x0, 0x0, 0x0, 0xc42000e258, 0x0, 0x1, 0x40a88e)
        /home/whyrusleeping/go/src/net/http/client.go:173 +0x108
net/http.(*Client).Do(0x145e220, 0xc42049d600, 0xc4204fc980, 0xdb9f0a, 0x10)
        /home/whyrusleeping/go/src/net/http/client.go:595 +0x254
github.com/ipfs/go-ipfs/commands/http.(*client).Send(0xc420480fc0, 0x136f0c0, 0xc4200c4540, 0x1, 0xc4200c4540, 0x145f8a0, 0x0)
        /home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/commands/http/client.go:100 +0x60d
main.callCommand(0x1366680, 0xc4204fc940, 0x136f0c0, 0xc4200c4540, 0x145f8a0, 0x143af20, 0x0, 0x0, 0xbce307, 0xc420151eb8)
        /home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:331 +0x62b
main.(*cmdInvocation).Run(0xc4204fc900, 0x1366680, 0xc4204fc940, 0x135c440, 0xc420480e80, 0x1366680, 0xc4204fc940)
        /home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:190 +0x116
main.mainRet(0x0)
        /home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:155 +0x374
main.main()
        /home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:62 +0x22

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/whyrusleeping/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /home/whyrusleeping/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /home/whyrusleeping/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /home/whyrusleeping/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 7 [select]:
gx/ipfs/QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52/go-log.(*MirrorWriter).logRoutine(0xc420016f00)
        /home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52/go-log/writer.go:71 +0x328
created by gx/ipfs/QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52/go-log.NewMirrorWriter
        /home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52/go-log/writer.go:38 +0xce

goroutine 18 [chan receive]:
main.(*IntrHandler).Handle.func1(0xc420480e80, 0xc42012f470)
        /home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:544 +0x96
created by main.(*IntrHandler).Handle
        /home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:549 +0x99

goroutine 16 [select, locked to thread]:
runtime.gopark(0xf13988, 0x0, 0xdaebf5, 0x6, 0x18, 0x2)
        /home/whyrusleeping/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc42001ff50, 0x0, 0x18)
        /home/whyrusleeping/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc42001ff50)
        /home/whyrusleeping/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /home/whyrusleeping/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
        /home/whyrusleeping/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 21 [IO wait]:
net.runtime_pollWait(0x7f903098edd0, 0x72, 0x5)
        /home/whyrusleeping/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4200f55d8, 0x72, 0x135f040, 0x13588c0)
        /home/whyrusleeping/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4200f55d8, 0xc420171000, 0x1000)
        /home/whyrusleeping/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4200f5570, 0xc420171000, 0x1000, 0x1000, 0x0, 0x135f040, 0x13588c0)
        /home/whyrusleeping/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e260, 0xc420171000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/whyrusleeping/go/src/net/net.go:181 +0x70
net/http.(*persistConn).Read(0xc4204fa900, 0xc420171000, 0x1000, 0x1000, 0x50, 0xc42004bef0, 0xc420032b80)
        /home/whyrusleeping/go/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc420055d40)
        /home/whyrusleeping/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc420055d40, 0x1, 0xc420055ec0, 0xc420020480, 0xd7ab00, 0x0, 0x0)
        /home/whyrusleeping/go/src/bufio/bufio.go:129 +0x67
net/http.(*persistConn).readLoop(0xc4204fa900)
        /home/whyrusleeping/go/src/net/http/transport.go:1474 +0x196
created by net/http.(*Transport).dialConn
        /home/whyrusleeping/go/src/net/http/transport.go:1117 +0xa35

goroutine 22 [select]:
net/http.(*persistConn).writeLoop(0xc4204fa900)
        /home/whyrusleeping/go/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
        /home/whyrusleeping/go/src/net/http/transport.go:1118 +0xa5a

rax    0x0
rbx    0x6
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x2
rsi    0x7fffc0f3d970
rbp    0xf5d3ab
rsp    0x7fffc0f3d9e8
r8     0x0
r9     0x7fffc0f3d970
r10    0x8
r11    0x246
r12    0x22b5050
r13    0x34
r14    0x0
r15    0xf3
rip    0x7f90319f1fdf
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by zinid** [comment]
Ah, it seems like in the case of the latest crash, the daemon doesn't respond or something, because any `ipfs` command gets crashed similarly.

**Comment by magik6k** [comment]
This looks very much like [this](https://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel/255603#255603).

Although IPFS shouldn't spawn that many threads, I think there are some fixes in master by @Kubuxu, so you may try to see if using build from git helps.

If this is still the case, can you try monitoring ipfs thread count with `export DPID=$(pidof ipfs); watch -n0 'ls -l /proc/${DPID}/task/ | wc -l'` and report here what number of threads you get before crash?

**Comment by Kubuxu** [comment]
The problem as it stands right now (I think), is: OSX sets the ulimit on processes to 256 or other lowish value, can be checked with `ulimit -u`. The go-reuseport for OSX does not implement the singlepool and such it uses one blocking call per connect call. This in combination with issue that @magik6k fixed (the dials where not rate limited properly), causes to many blocked threads for which Go responds with more created threads. This crash you see there is Go trying to start a new thread but fails to do so due to thread limit.

There are couple of ways to mitigate that:
1. Increasing OSX's thread/process limit
2. Disabling go-reuseport. Start `ipfs daemon` with `IPFS_REUSEPORT=false` environment variable (simple way to test `IPFS_REUSEPORT=false ipfs daemon`).
3. Upgrading to master (unreleased yet 0.4.11) which should fix the unlimited dials problem and fix the issue but it might not be 100% if created threads come from somewhere else.

**Comment by zinid** [comment]
@Kubuxu I'm using Linux (Debian), not OSX.
I monitored threads a couple of hours ago, didn't find overconsumption, although I didn't try it thoroughly, because it's hard to monitor a process which dies almost instantly.

**Comment by Kubuxu** [comment]
Sorry, for that. I think I've read very similar issue recently and it was OSX.
The 1st point still stands, can you check your `ulimit -u`?

**Comment by zinid** [comment]
```
$ ulimit -u
unlimited
```

**Comment by zinid** [comment]
Note that I have only 512Mb of RAM, can it be a problem?

**Comment by Kubuxu** [comment]
Hmm, it is still very weird issue because the crashes you get, I think, should include full goroutine dumps. Have you truncated them or is it all?

**Comment by zinid** [comment]
No, I didn't truncate them, that's all I got ;)

**Comment by zinid** [comment]
Are you able to download this file? Maybe you can reproduce yourself?

**Comment by Kubuxu** [comment]
How much RAM do you have free?
I think it might be an issue with go-ipfs opening too many connections for your system to handle RAM requirements. The master might make it better and we are working on other solution to fix it.

Yes I am able to download it but go-ipfs takes more than 500MB then, mostly due to lack of memory pressure (GC doesn't trigger), memory usage is probably lower but it might be still too much for 512MB of RAM to handle.

**Comment by zinid** [comment]
For the record, I finally was able to monitor threads. No problems here: every ipfs process (both daemon and the command tool) eat 8 threads each.

**Comment by zinid** [comment]
Ah, damn, indeed, just noticed in `dmesg`:
```
[15028537.384627] Out of memory: kill process 13681 (bash) score 606916 or a child
[15028537.385098] Killed process 13690 (ipfs)
```
So this is a memory consumption problem, I close the issue as I think there is another one related: #4145

**Comment by zinid** [comment]
Hum, it seems like not the problem solely with memory. I set `GOGC=20` and `ipfs get` now stalls always at 40.05%:
```
$ ipfs get /ipfs/QmZnLMNSVVs3kmRp5CJU1pnKygwRNzSo8MGuuQEUpPg7tX
Saving file(s) to QmZnLMNSVVs3kmRp5CJU1pnKygwRNzSo8MGuuQEUpPg7tX
 220.00 MB / 549.33 MB [=================================>-------------------------------------------------]  40.05% 8s
```
Here is available memory:
```
$ free -m
             total       used       free     shared    buffers     cached
Mem:           496        490          6          0          4        135
-/+ buffers/cache:        351        145
Swap:            0          0          0
```
Some `top` stats:
```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 1499 xram      20   0  611m 218m  10m S  4.3 43.9   0:07.41 ipfs
 1507 xram      20   0  205m  12m 7896 S  0.0  2.5   0:01.91 ipfs
```
