### ISSUE TITLE
Crash when files add with --hash=blake2b-x and --raw-leaves=false

### ISSUE THREAD

**Issue by alanshaw** [ipfs/go-ipfs#4206]
#### Version information:

go-ipfs version: 0.4.10-
Repo version: 5
System version: amd64/darwin
Golang version: go1.8.3

#### Description:

```sh
ipfs add ../test2.md --hash=blake2b-32
 5 B / 5 B [====================================================================================================================] 100.00% 0s16:00:40.063 ERROR commands/h: unsupported length for blake2b: 4 client.go:247
Error: unsupported length for blake2b: 4
```

...and daemon stays running, but:

```sh
ipfs add ../test2.md --hash=blake2b-24 --raw-leaves=false
Error: Post http://127.0.0.1:5001/api/v0/add?encoding=json&hash=blake2b-24&progress=true&raw-leaves=false&stream-channels=true: EOF
```

Crashes the daemon with the following error:

```
panic: invalid CID of length 0: : unsupported length for blake2b: 3

goroutine 3576 [running]:
github.com/ipfs/go-ipfs/merkledag.(*ProtoNode).Cid(0xc4206ed1f0, 0xc4207edb98)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/merkledag/node.go:304 +0x2f9
github.com/ipfs/go-ipfs/blockservice.(*blockService).AddBlock(0xc4207274d0, 0x24e47d0, 0xc4206ed1f0, 0x24e47d0, 0xc4206ed1f0, 0x0)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/blockservice/blockservice.go:83 +0x35
github.com/ipfs/go-ipfs/merkledag.(*dagService).Add(0xc420feca50, 0x1f70360, 0xc4206ed1f0, 0x0, 0x0, 0xc4207edc40)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/merkledag/merkledag.go:65 +0x8c
github.com/ipfs/go-ipfs/importer/helpers.(*DagBuilderHelper).Add(0xc4201173b0, 0xc420727770, 0x0, 0x0, 0x0, 0x0)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/importer/helpers/dagbuilder.go:202 +0x76
github.com/ipfs/go-ipfs/importer/balanced.BalancedLayout(0xc4201173b0, 0x1f633c0, 0xc420727710, 0xc4201173b0, 0x1f633c0)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/importer/balanced/builder.go:39 +0x497
github.com/ipfs/go-ipfs/core/coreunix.Adder.add(0x1f69640, 0xc420699cc0, 0x1f71160, 0xc4206ce300, 0x1f70260, 0xc4201932e0, 0x1f6eb80, 0xc420feca50, 0xc420622d20, 0x10001, ...)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/coreunix/add.go:150 +0x176
github.com/ipfs/go-ipfs/core/coreunix.(*Adder).addFile(0xc420368280, 0x1f6d800, 0xc42062ae60, 0x0, 0x0)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/coreunix/add.go:475 +0x3fa
github.com/ipfs/go-ipfs/core/coreunix.(*Adder).AddFile(0xc420368280, 0x1f6d800, 0xc42062ae60, 0x0, 0x0)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/coreunix/add.go:419 +0x83
github.com/ipfs/go-ipfs/core/commands.glob..func6.1(0x1f6d7a0, 0xc420727110, 0xc420727110, 0xc4206d41c0)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/add.go:282 +0x97
github.com/ipfs/go-ipfs/core/commands.glob..func6.2(0xc420622d20, 0xc420f16100, 0x1f720e0, 0xc42119afc0, 0x1f714c0, 0xc4206ecf50)
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/add.go:302 +0x7c
created by github.com/ipfs/go-ipfs/core/commands.glob..func6
	/home/whyrusleeping/code/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/add.go:307 +0xd05
```

**Comment by whyrusleeping** [comment]
That should probably fail a little more nicely...

**Comment by kevina** [comment]
Okay, I will look into what's panicking and see if I can do something about it.

**Comment by kevina** [comment]
@whyrusleeping the problem is that it is possible to set the hash of a Cid Prefix to an unsupported version that is not discovered until Prefix.Sum() is called.  In the raw node case the error is being returned.  In the protobuf node case `Prefix.Sum()` is called in `ProtoNode.Cid()` which does not return an error so it panics.

Having ProtoNode.Cid() return an error will likely require a lot of code changes.

A better solution is to validate the Prefix earlier on.  This can be done my calling Prefix.Sum() on an empty value.  However, there doesn't seam to be a very good place to do this.  For now I could do it in the add command, we will need to duplicate this wherever we set the hash function.

**Comment by kevina** [comment]
Note: I added the blocked label because I am waiting for @whyrusleeping feedback before I take action.

**Comment by kevina** [comment]
Changing to needs_refining after a suggestion from IRC, sorry for the noise.

**Comment by whyrusleeping** [comment]
cc @Stebalien @Kubuxu

**Comment by Stebalien** [comment]
This _looks_ fixed (as in, I can't reproduce).
