### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4416]
In a discussion on IRC last night, it was brought up that our error messages kinda suck sometimes. I tend to agree (merkledag: not found).

To improve this, we can distinguish between a few different failure modes for common commands:

1. Cannot find any providers for the given hash
2. Cannot connect to any providers for the given hash
3. MERKLEDAG: NOT FOUND (or maybe: failed to find hash)

Then, if the daemon is offline, we can return something like:
data not found *locally*.

(for context, i also just read [this article](https://blog.keras.io/user-experience-design-for-apis.html) and enjoyed it)

**Comment by djdv** [comment]
Bringing to attention `get`
```
>ipfs get invalid
03:49:44.027 ERROR core/comma: received command error in:
goroutine 25 [running]:
runtime/debug.Stack(0x0, 0x0, 0xc042044780)
        C:/Go/src/runtime/debug/stack.go:24 +0xae
github.com/ipfs/go-ipfs/core/commands/e.New(0x14619a0, 0xc042047ae0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/tmp/src/github.com/ipfs/go-ipfs/core/commands/e/error.go:29 +0x5d
github.com/ipfs/go-ipfs/core/commands.glob..func61.1(0x146dce0, 0xc04215df10, 0x1470320, 0xc0422aa180, 0x1476ac0, 0xc04214e600)
        C:/tmp/src/github.com/ipfs/go-ipfs/core/commands/get.go:113 +0xb2
created by github.com/ipfs/go-ipfs/core/commands.glob..func61
        C:/tmp/src/github.com/ipfs/go-ipfs/core/commands/get.go:108 +0x1e7
 get.go:113
```

**Comment by kevina** [comment]
Fixing the merkeldag error messages was discused is in pr. https://github.com/ipfs/go-ipfs/pull/4099 which seams to have been abandoned.  I will be happy to do what I discussed in that issue and take a pass at giving more informative error messages.

**Comment by kevina** [comment]
I spend some time working with this, I will create a p.r. in a few days once I figure out something I am reasonable happy with,

**Comment by picasso250** [comment]
Error: merkledag: not found

centos 7
ipfs version 0.4.13

**Comment by picasso250** [comment]
After daemon-ed, problem solved.

**Comment by hsanjuan** [comment]
@Stebalien many things have changed but the `merkledag: not found` error remains the same.

I would assume that we can now take advantange of `errors.Is()` and wrap original NotFound errors on higher layers like NotFoundOffline. Do you have an idea of what the best approach would be to address this one?

**Comment by Stebalien** [comment]
That helps but isn't necessary. We can just fix this.

**Comment by hsanjuan** [comment]
> That helps but isn't necessary. We can just fix this.

It seems that proposed fixes so far have not suceeded to land. How do you want to fix it?

**Comment by Stebalien** [comment]
The proposed fix modified the core ErrNotFound error to say "we're offline". The correct solution would involve:

* Checking for this error inside the CoreAPI functions themselves, then checking to see if we're offline, then wrapping the error with a hint.
* Possibly changing the merkledag error text to "block not found".
* Wrapping the error inside go-unixfs to indicate that a part of the file was not found.

**Comment by hsanjuan** [comment]
>     * Possibly changing the merkledag error text to "block not found".

Let's start here: https://github.com/ipfs/go-ipld-format/pull/55

**Comment by lidel** [comment]
This came up during triage today. 

## Inconsistency in errors returned from commands

- the errors we return today are a mix of CLI-specific messages
  - example:  gateway https://ipfs.io/ipfs/Qme7TddCpkz1CZLscPhfDQ9VuarjzThiQ42uNucDPmShKv/lol returns CLI-specific  `ipfs resolve -r /ipfs/Qme7TddCpkz1CZLscPhfDQ9VuarjzThiQ42uNucDPmShKv/lol: no link named "lol" under Qme7TddCpkz1CZLscPhfDQ9VuarjzThiQ42uNucDPmShKv`  which is pretty bizarre 
-  ... or  try to be overly helpful, but then fail anyway and get constantly changed 
   - example: error when mangled CIDv0 in lowercase is detected: https://github.com/ipfs/go-path/pull/45

The lack of deterministic codes makes it impossible to reliably consume errors in userland. Folks will match plaintext message but this may break in the future when someone changes the error message.

## Proposed suggestion

- @petar noted that we should use well-defined error codes as canonical default, and document their meaning in an outside document (eg `/docs/error-codes.md`)
  - prior art: https://cloud.google.com/apis/design/errors#handling_errors (feel free to provide more good examples in comments below :pray:)
- CLI tools and gateways should always include those error codes with error messages as the very first thing 
  - think `{ERROR_CODE}: no link named "lol" under Qme7TddCpkz1CZLscPhfDQ9VuarjzThiQ42uNucDPmShKv`

**Comment by hsanjuan** [comment]
Note that https://github.com/ipfs/go-ipfs/issues/7074 has the tracking around resolving the Block Not Found errors and the changes would allow each layer to better set the errors as they bubble.

**Comment by Winterhuman** [comment]
A user in the Matrix room recently encountered this, here's the issue I created before being pointed to this one: https://github.com/ipfs/kubo/issues/9179

I disagree with "Then, if the daemon is offline, we can return something like:
data not found locally.". In reality, "data not found locally" also doesn't tell the user that they need to start a daemon, it's assuming that they know Kubo needs a daemon which isn't always true, and it's wording makes it seem more like an issue with the software being broken rather than something the user can fix.
