### ISSUE TITLE
Panic on Ctrl-D on ipfs add

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#4436]
To reproduce:

```sh
> ipfs add
^D
```

Result:

```
ipfs: Reading from /dev/stdin; send Ctrl-d to stop.
panic: interface conversion: interface {} is map[string]interface {}, not *coreunix.AddedObject

goroutine 42 [running]:
github.com/ipfs/go-ipfs/core/commands.glob..func7.1(0xc420076960)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/commands/add.go:390 +0x9fc
created by github.com/ipfs/go-ipfs/core/commands.glob..func7.2
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/commands/add.go:449 +0x181
```

**Comment by Stebalien** [comment]
Fixed
