### ISSUE TITLE
`ipfs get` errors

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4452]
Odd error here. @keks 
```
why@manwe ~/c/d/releases> ipfs get /ipns/dists.ipfs.io/go-ipfs 
19:49:39.286 ERROR core/comma: received command error in:
goroutine 15 [running]:
runtime/debug.Stack(0x0, 0x0, 0xc4204e4360)
        /home/why/go/src/runtime/debug/stack.go:24 +0xa7
github.com/ipfs/go-ipfs/core/commands/e.New(0x1cb2260, 0xc420112a90, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/why/gopkg/src/github.com/ipfs/go-ipfs/core/commands/e/error.go:29 +0x56
github.com/ipfs/go-ipfs/core/commands.glob..func61.1(0x1cc0ba0, 0xc42022e070, 0x1cc1f60, 0xc4204fce40, 0x1cc84e0, 0xc420108600)
        /home/why/gopkg/src/github.com/ipfs/go-ipfs/core/commands/get.go:113 +0xab
created by github.com/ipfs/go-ipfs/core/commands.glob..func61
        /home/why/gopkg/src/github.com/ipfs/go-ipfs/core/commands/get.go:108 +0x1e0
 get.go:113
```

**Comment by keks** [comment]
I have a hunch what this is about, will try to fix it later today.

**Comment by keks** [comment]
That was easy! The error actually returned by get (at least for me) is 
```
$ ./ipfs get /ipns/dists.ipfs.io/go-ipfs                                                             
Error: core/resolve: no Namesys on IpfsNode - can't resolve ipns entry
```
