### ISSUE TITLE
error calling `ipfs stats bw`

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-ipfs#4474]
cc @keks 

```
why@whys-mbp /p/t/foo> ipfs stats bw -t /ipfs/bitswap/1.0.0
Total Up    Total Down  Rate Up     Rate Down
panic: interface conversion: interface {} is map[string]interface {}, not *metrics.Stats

goroutine 40 [running]:
github.com/ipfs/go-ipfs/core/commands.glob..func127.1(0x20f55a0, 0xc4201f2850, 0x20f6960, 0xc4201ee580)
	/Users/why/go/src/github.com/ipfs/go-ipfs/core/commands/stat.go:186 +0x602
created by github.com/ipfs/go-ipfs/core/commands.glob..func127
	/Users/why/go/src/github.com/ipfs/go-ipfs/core/commands/stat.go:171 +0x1b5
```

**Comment by Stebalien** [comment]
I can no longer reproduce this. I believe it was fixed by the latest version of commands. @whyrusleeping can you confirm?
