### ISSUE TITLE
Gateway crashes without any load (possibly prometheus related)

### ISSUE THREAD

**Issue by victorb** [ipfs/go-ipfs#4574]
#### Version information:
```
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2
```

#### Type:

Bug

#### Severity:

Critical (gateway crash)

#### Description:

I have a node that is currently used for archiving the npm registry. There is a background process that is continuously adding a lot of files via the Files API (and with sharding enabled) but there is no requests hitting the gateway. 

However, at one point, the gateway is crashing for some reason. Here is the panic:

```
2018/01/10 11:31:20 http: panic serving 180.150.179.202:58738: runtime error: invalid memory address or nil pointer dereference
goroutine 5779183 [running]:
net/http.(*conn).serve.func1(0xc4541e2320)
        /usr/lib/go/src/net/http/server.go:1697 +0xd0
panic(0x12ace40, 0x1c2c880)
        /usr/lib/go/src/runtime/panic.go:491 +0x283
github.com/ipfs/go-ipfs/core/corehttp.IPNSHostnameOption.func1.1(0x1c63140, 0xc4e81614b0, 0xc48f6d2300)
        github.com/ipfs/go-ipfs/core/corehttp/ipns_hostname.go:27 +0x1cf
net/http.HandlerFunc.ServeHTTP(0xc4203042a0, 0x1c63140, 0xc4e81614b0, 0xc48f6d2300)
        /usr/lib/go/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201c0030, 0x1c63140, 0xc4e81614b0, 0xc48f6d2300)
        /usr/lib/go/src/net/http/server.go:2254 +0x130
net/http.(Handler).ServeHTTP-fm(0x1c63140, 0xc4e81614b0, 0xc48f6d2300)
        /usr/lib/go/src/net/http/h2_bundle.go:5462 +0x4d
gx/ipfs/QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B/client_golang/prometheus.InstrumentHandlerFuncWithOpts.func1(0x1c64700, 0xc452a6cfc0, 0xc48f6d2300)
        gx/ipfs/QmX3QZ5jHEPidwUrymXV1iSCSUhdGxj15sm2gP4jKMef7B/client_golang/prometheus/http.go:287 +0x26f
net/http.HandlerFunc.ServeHTTP(0xc42056b1d0, 0x1c64700, 0xc452a6cfc0, 0xc48f6d2300)
        /usr/lib/go/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201c0000, 0x1c64700, 0xc452a6cfc0, 0xc48f6d2300)
        /usr/lib/go/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc4205a71e0, 0x1c64700, 0xc452a6cfc0, 0xc48f6d2300)
        /usr/lib/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4541e2320, 0x1c65580, 0xc4b76f8240)
        /usr/lib/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:2720 +0x288

```

**Comment by VictorBjelkholm** [comment]
cc @lgierth

**Comment by lgierth** [comment]
It looks like it's this line that's panicking: `if _, err := n.Namesys.Resolve(ctx, name); err == nil {`

Are you running that node with `--offline`?

**Comment by VictorBjelkholm** [comment]
Yup, indeed I am.

**Comment by ToxicFrog** [comment]
I'm also seeing this, also with --offline.

If it helps any, I'm running it behind nginx, with a vhost that resolves on the machine accessing but *not* on the machine hosting ipfs.

**Comment by ToxicFrog** [comment]
If I fix that, though, it still panics.

Querying the gateway directly (not via nginx) works fine.

**Comment by ToxicFrog** [comment]
Switching to online mode does fix it.

**Comment by Stebalien** [comment]
I'm not able to reproduce this in 0.4.18-rc1. Is this still an issue?
