### ISSUE TITLE
data in file did not match, during recursive add with local nocopy and fscache

### ISSUE THREAD

**Issue by elopio** [ipfs/go-ipfs#4603]
#### Version information:

```
$ ipfs version --all
go-ipfs version: 0.4.13-
Repo version: 6
System version: amd64/linux
Golang version: go1.9.2
$ uname -a
Linux ipfsapt 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
#### Type:

    High - The main functionality of the application does not work, API breakage, repo format breakage, etc.

#### Description:

We are trying to add a full ubuntu mirror to IPFS.
Today, while running the command:
```$ ipfs add --local=true --nocopy --fscache --recursive /data/repos/ubuntu/mirror/
```
If failed with:

```
11:20:54.548 ERROR commands/h: Failed to get block for zb2rhZzDivybfWjzSiMTq61gVCMqn2s1YokCDUV2nbUbBA6To: data in file did not match. repos/ubuntu/mirror/dists/artful-backports/universe/dep11/Components-amd64.yml.xz offset 0 client.go:247
Error: Failed to get block for zb2rhZzDivybfWjzSiMTq61gVCMqn2s1YokCDUV2nbUbBA6To: data in file did not match. repos/ubuntu/mirror/dists/artful-backports/universe/dep11/Components-amd64.yml.xz offset 0
repoadmin@ipfsapt:/data/repos/ubuntu$ ipfs add --local=true --nocopy --fscache --recursive /data/repos/ubuntu/mirror/dists/artful-backports/universe/dep11/Components-amd64.yml.xz 
added zb2rhoLrX6VKRtM5sk2tPXJ9Pd73mHqgTNgmm3SPHvFkL9xQx Components-amd64.yml.xz
```

I tried to add the file again, and it worked:

```
$ ipfs add --local=true --nocopy --fscache --recursive /data/repos/ubuntu/mirror/dists/artful-backports/universe/dep11/Components-amd64.yml.xz 
added zb2rhoLrX6VKRtM5sk2tPXJ9Pd73mHqgTNgmm3SPHvFkL9xQx Components-amd64.yml.xz
```

This is pretty sad, because we can't resume the add. So for every error, we have to start again from scratch and wait a couple of hours at least.

**Comment by rngkll** [comment]
**Version information:**
```
./ipfs version --all
go-ipfs version: 0.4.14-dev-eca0486e1
Repo version: 6
System version: amd64/linux
Golang version: go1.9.4
```
**Description**

Error is different using the master branch.
```
IPFS_PATH="/data/ipfsrepo"  IPFS_FD_MAX="4096" ./ipfs add --progress --local --nocop
y --fscache --quieter --recursive mirror/                                                                                 
 849.23 GB / 849.35 GB [==========================================================================================================================================]  99.99% 0spanic: interface conversion: interface {} is cmdkit.Error, not *coreunix.AddedObject

goroutine 70 [running]:
github.com/ipfs/go-ipfs/core/commands.glob..func7.2(0xc42001a3c0)
        /home/alvaro/gocode/src/github.com/ipfs/go-ipfs/core/commands/add.go:405 +0xa60
created by github.com/ipfs/go-ipfs/core/commands.glob..func7.3
        /home/alvaro/gocode/src/github.com/ipfs/go-ipfs/core/commands/add.go:467 +0xc7
```

**Comment by Stebalien** [comment]
@rngkll that's a new issue that should be fixed (although it'll just revert back).

**Comment by aidanharris** [comment]
Has there been any progress tracking this down?

```
$ ipfs add  --nocopy --fscache -r ubuntu/dists/bionic-backports
...
 3.62 MiB / 3.62 MiB [==================================================================================================================================================] 100.00%
Error: failed to get block for bafkreiambgok3tq546nfkyd74sxcx4piniiybvar6rua6mpriguv2luryq: data in file did not match. ubuntu/dists/bionic-backports/Release offset 0
```

Interestingly if I do `ipfs filestore verify <obj>` it changes the object:

```
$ ipfs filestore verify bafkreiambgok3tq546nfkyd74sxcx4piniiybvar6rua6mpriguv2luryq
changed bafkreiambgok3tq546nfkyd74sxcx4piniiybvar6rua6mpriguv2luryq  73694 ubuntu/dists/bionic-backports/Release 0
```

I'm running the latest version of go-ipfs from git master.

**Comment by Stebalien** [comment]
> Interestingly if I do ipfs filestore verify <obj> it changes the object:

It's not changing the object, it's saying that the object has changed. That is, it's saying that the `Release` file was changed.

Was it? Given the `--fscache` option, I assume you're re-importing data you may already have from a previous import. Are you trying to re-import the same directory?
