### ISSUE TITLE
ipfs pin update produces error

### ISSUE THREAD

**Issue by reit-c** [ipfs/go-ipfs#4999]
#### Version information:

go-ipfs version: 0.4.14-
Repo version: 6
System version: amd64/linux
Golang version: go1.10

#### Type:

Bug

#### Description:

When doing `ipfs pin update` this error reliably results:
```
goroutine 40 [running]:
runtime/debug.Stack(0xc420042180, 0x10df740, 0xc4204fe280)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x22
gx/ipfs/QmNiJuT8Ja3hMVpBHXv3Q6dwmperaQ6JjLtpMQgMCD7xvx/go-ipfs-util.ErrCast(0xc4204fe360, 0x110be00)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmNiJuT8Ja3hMVpBHXv3Q6dwmperaQ6JjLtpMQgMCD7xvx/go-ipfs-util/util.go:37 +0x20
github.com/ipfs/go-ipfs/core/commands.glob..func116(0x149a6e0, 0xc4204fe360, 0xc420185200, 0x10df740, 0xc4204fe280, 0xc42008ddf0)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/pin.go:421 +0x19d
github.com/ipfs/go-ipfs/commands/legacy.(*MarshalerEncoder).Encode(0xc42000c6e0, 0x10df740, 0xc4204fe280, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/commands/legacy/legacy.go:35 +0x1d9
gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/cli.(*responseEmitter).Emit(0xc4205c3f80, 0x10df740, 0xc4204fe280, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/cli/responseemitter.go:197 +0x390
gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds.Copy(0x14931c0, 0xc4205c3f80, 0x1493d00, 0xc420046280, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/responseemitter.go:75 +0x80
gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/http.(*client).Execute(0xc420597e40, 0xc4205c3ea0, 0x14931c0, 0xc4205c3f80, 0x147d8c0, 0xc420597e00, 0xb066ac, 0xc42001df80)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/http/client.go:116 +0x1ad
gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/cli.Run.func4(0x7f31ca903020, 0xc420597e40, 0xc4205c3ea0, 0x14931c0, 0xc4205c3f80, 0x147d8c0, 0xc420597e00, 0xc4205c03c0)
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/cli/run.go:146 +0x70
created by gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/cli.Run
	/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmfAkMSt9Fwzk48QDJecPcwCUjnf2uG7MLnmCGTp4C6ouL/go-ipfs-cmds/cli/run.go:145 +0x6ac
Error: cast error
```

Note that there is not nor has their ever been a user named 'steb' nor a directory at /home/steb on this computer.

Reproduction:
```
echo "File 1" > a
echo "File 2" > b
hasha=$(ipfs add -q a)
hashb=$(ipfs add --pin=false -q b)
ipfs pin update $hasha $hashb
```

**Comment by Kubuxu** [comment]
@reit-c The `/home/steb` is just a directory of the one who built the current distribution of go-ipfs.
