### ISSUE TITLE
Exception during adding file

### ISSUE THREAD

**Issue by michelion** [ipfs/go-ipfs#5155]
D:\go-ipfs>ipfs version --all
go-ipfs version: 0.4.15-
Repo version: 6
System version: amd64/windows
Golang version: go1.10.2

Bug

Hello together,

I want to add a file. The result was an exception.
How can I get further information about that problem?

Kind regards :)

```
D:\go-ipfs\ipfs.exe version
ipfs version 0.4.15
```

```
D:\go-ipfs\ipfs.exe add D:\go-ipfs\michel_test.txt
Exception 0xe06d7363 0x19930520 0x40bfa60 0x7fefd4ba06d
PC=0x7fefd4ba06d

syscall.Syscall9(0x7feff6313b0, 0x7, 0x138, 0xc04248aef8, 0x1, 0xc04248aee0, 0x0, 0xc04248aeb0, 0x0, 0x0, ...)
/usr/lib/go/src/runtime/syscall_windows.go:197 +0x102
syscall.WSASend(0x138, 0xc04248aef8, 0xc000000001, 0xc04248aee0, 0x0, 0xc04248aeb0, 0x0, 0x0, 0x0)
/usr/lib/go/src/syscall/zsyscall_windows.go:1576 +0xf8
internal/poll.(*FD).Write.func1(0xc04248aeb0, 0x77, 0xc04227f900)
/usr/lib/go/src/internal/poll/fd_windows.go:659 +0x6a
internal/poll.(*ioSrv).ExecIO(0x15630a8, 0xc04248aeb0, 0xf6dbb8, 0x40dcb0, 0xd852a0, 0x25ba10)
/usr/lib/go/src/internal/poll/fd_windows.go:201 +0xce
internal/poll.(*FD).Write(0xc04248adc0, 0xc042291000, 0x23a, 0x1000, 0x0, 0x0, 0x0)
/usr/lib/go/src/internal/poll/fd_windows.go:658 +0x21c
net.(*netFD).Write(0xc04248adc0, 0xc042291000, 0x23a, 0x1000, 0x1588788, 0x0, 0x0)
/usr/lib/go/src/net/fd_windows.go:163 +0x56
net.(*conn).Write(0xc042124388, 0xc042291000, 0x23a, 0x1000, 0x0, 0x0, 0x0)
/usr/lib/go/src/net/net.go:188 +0x71
net/http.persistConnWriter.Write(0xc042274c60, 0xc042291000, 0x23a, 0x1000, 0xc042188bc0, 0xdfc5ae, 0x2)
/usr/lib/go/src/net/http/transport.go:1253 +0x59
bufio.(*Writer).Flush(0xc042188bc0, 0xc042004390, 0xdfc5ae)
/usr/lib/go/src/bufio/bufio.go:573 +0x85
net/http/internal.(*chunkedWriter).Write(0xc0421a16f0, 0xc04229a000, 0xc6, 0x8000, 0xc6, 0x0, 0x0)
/usr/lib/go/src/net/http/internal/chunked.go:215 +0x1d4
io.copyBuffer(0x4e80220, 0xc0421a16f0, 0xfdefc0, 0xc04206d540, 0xc04229a000, 0x8000, 0x8000, 0xce8140, 0xc04218a600, 0x4e80220)
/usr/lib/go/src/io/io.go:402 +0x247
io.Copy(0x4e80220, 0xc0421a16f0, 0xfdefc0, 0xc04206d540, 0xc0421a16f0, 0xdfc5ae, 0x2)
/usr/lib/go/src/io/io.go:362 +0x61
net/http.(*transferWriter).WriteBody(0xc04206d540, 0xfdc7c0, 0xc042188bc0, 0x2, 0x2)
/usr/lib/go/src/net/http/transfer.go:330 +0x16f
net/http.(*Request).write(0xc042485200, 0xfdc7c0, 0xc042188bc0, 0x0, 0xc042185d70, 0x0, 0x0, 0x0)
/usr/lib/go/src/net/http/request.go:622 +0x6b9
net/http.(*persistConn).writeLoop(0xc042274c60)
/usr/lib/go/src/net/http/transport.go:1825 +0x1f1
created by net/http.(*Transport).dialConn
/usr/lib/go/src/net/http/transport.go:1238 +0x986

goroutine 1 [select]:
gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/cli.Run(0xfe8240, 0xc042188a80, 0x156a540, 0xc04205a0c0, 0x3, 0x4, 0xc042004010, 0xc042004018, 0xc042004020, 0xf6dca8, ...)
/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/cli/run.go:152 +0x771
main.mainRet(0x0)
github.com/ipfs/go-ipfs/cmd/ipfs/main.go:132 +0x2d8
main.main()
github.com/ipfs/go-ipfs/cmd/ipfs/main.go:57 +0x29

goroutine 17 [syscall]:
os/signal.signal_recv(0xc04204bfc8)
/usr/lib/go/src/runtime/sigqueue.go:139 +0xad
os/signal.loop()
/usr/lib/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
/usr/lib/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 6 [select]:
gx/ipfs/QmRb5jh8z2E8hMGN2tkvs1yHynUanqnZ3UeKwgN1i9P1F8/go-log.(*MirrorWriter).logRoutine(0xc04205a440)
/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmRb5jh8z2E8hMGN2tkvs1yHynUanqnZ3UeKwgN1i9P1F8/go-log/writer.go:78 +0x146
created by gx/ipfs/QmRb5jh8z2E8hMGN2tkvs1yHynUanqnZ3UeKwgN1i9P1F8/go-log.NewMirrorWriter
/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmRb5jh8z2E8hMGN2tkvs1yHynUanqnZ3UeKwgN1i9P1F8/go-log/writer.go:43 +0xc9

goroutine 14 [chan receive]:
main.(*IntrHandler).Handle.func1(0xc042186640, 0xc04218a3e0)
github.com/ipfs/go-ipfs/cmd/ipfs/main.go:365 +0xc0
created by main.(*IntrHandler).Handle
github.com/ipfs/go-ipfs/cmd/ipfs/main.go:362 +0x9e

goroutine 15 [select]:
net/http.(*persistConn).roundTrip(0xc042274c60, 0xc042185b60, 0x0, 0x0, 0x0)
/usr/lib/go/src/net/http/transport.go:2033 +0x5ae
net/http.(*Transport).RoundTrip(0x15413e0, 0xc042485200, 0x15413e0, 0x0, 0x0)
/usr/lib/go/src/net/http/transport.go:422 +0x8f9
net/http.send(0xc042485200, 0xfddc60, 0x15413e0, 0x0, 0x0, 0x0, 0xc042124378, 0x410723, 0xc042285bd0, 0x1)
/usr/lib/go/src/net/http/client.go:252 +0x18c
net/http.(*Client).send(0x1568f40, 0xc042485200, 0x0, 0x0, 0x0, 0xc042124378, 0x0, 0x1, 0x10)
/usr/lib/go/src/net/http/client.go:176 +0x101
net/http.(*Client).Do(0x1568f40, 0xc042485200, 0xc042188b00, 0xc042485200, 0x11)

    /usr/lib/go/src/net/http/client.go:615 +0x294

gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/http.(*client).Send(0xc042188b80, 0xc0421e43f0, 0xc0421e4540, 0xfe8940, 0xc042185950, 0x2ba6f3002145701)
/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/http/client.go:172 +0x4f3
gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/http.(*client).Execute(0xc042188b80, 0xc0421e43f0, 0xfe8940, 0xc042185950, 0xfdcc20, 0xc042188b40, 0x11e562000158d1, 0xbd75170339ed46)
/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/http/client.go:108 +0xe5
gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/cli.Run.func4(0x3bd2098, 0xc042188b80, 0xc0421e43f0, 0xfe8980, 0xc0421e4540, 0xfdcc20, 0xc042188b40, 0xc042166f00)
/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/cli/run.go:146 +0x77
created by gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/cli.Run
/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/cli/run.go:145 +0x6b3

goroutine 33 [chan receive]:
gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds.(*chanResponse).Error(0xc042185920, 0xfe8998)
/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmTjNRVt2fvaRFu93keEC7z5M1GS1iH6qZ9227htQioTUY/go-ipfs-cmds/ch
an.go:54 +0x3f
github.com/ipfs/go-ipfs/core/commands.glob..func7.3(0xfe8980, 0xc0421e4540, 0xfea740, 0xc042185920, 0xc0420348a0, 0xc0421867e0, 0xc0421e43f0)
/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/add.go:463 +0x84
created by github.com/ipfs/go-ipfs/core/commands.glob..func7
/home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/github.com/ipfs/go-ipfs/core/commands/add.go:459 +0x2b5

goroutine 37 [IO wait]:
internal/poll.runtime_pollWait(0x3bd3030, 0x72, 0xfdf100)
/usr/lib/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc04248af88, 0x72, 0x146a800, 0x0, 0x0)
/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0xa2
internal/poll.(*ioSrv).ExecIO(0x15630a0, 0xc04248add8, 0xf6db98, 0x3282fe2017a1aaa, 0x160ab40282cc75, 0x264ac6002f749ed)
/usr/lib/go/src/internal/poll/fd_windows.go:223 +0x13a
internal/poll.(*FD).Read(0xc04248adc0, 0xc042290000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/lib/go/src/internal/poll/fd_windows.go:484 +0x248
net.(*netFD).Read(0xc04248adc0, 0xc042290000, 0x1000, 0x1000, 0x1de3bf300b195b4, 0x222817300805bf9, 0x7c1b1b015944a3)
/usr/lib/go/src/net/fd_windows.go:151 +0x56
net.(*conn).Read(0xc042124388, 0xc042290000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
/usr/lib/go/src/net/net.go:176 +0x71
net/http.(*persistConn).Read(0xc042274c60, 0xc042290000, 0x1000, 0x1000, 0x402edd, 0xc042299b98, 0x42be50)
/usr/lib/go/src/net/http/transport.go:1453 +0x13d
bufio.(*Reader).fill(0xc042167380)
/usr/lib/go/src/bufio/bufio.go:100 +0x125
bufio.(*Reader).Peek(0xc042167380, 0x1, 0xc042034cc0, 0xc042299c80, 0x24b378701f6e38a, 0x3b262b30168d5b1, 0x1dd522b0126ea29)
/usr/lib/go/src/bufio/bufio.go:132 +0x41
net/http.(*persistConn).readLoop(0xc042274c60)
/usr/lib/go/src/net/http/transport.go:1601 +0x18c
created by net/http.(*Transport).dialConn
/usr/lib/go/src/net/http/transport.go:1237 +0x961
rax 0x734501a0
rbx 0x18005e670
rcx 0x40bf2f0
rdi 0x2c04f8
rsi 0xffffffffffd58221
rbp 0x40bfa30
rsp 0x40bf900
r8 0x0
r9 0x0
r10 0x180000000
r11 0x40bf940
r12 0xc04248aef8
r13 0x138
r14 0x23a
r15 0x1
rip 0x7fefd4ba06d
rflags 0x206
cs 0x33
fs 0x53
gs 0x2b
```

**Comment by Stebalien** [comment]
That looks suspiciously like https://github.com/golang/go/issues/13079. However, it may be caused by a memory unsafety issue.

@djdv any pointers?

**Comment by djdv** [comment]
@Stebalien 
If it is indeed that bug, it may be out of our domain (an issue in Windows).

@michelion 
Can you tell me more about your environment?
What version of Windows, any changes to Windows policies (specifically around networking)?
VPN, etc.

**Comment by Stebalien** [comment]
This was a bug in https://github.com/jbenet/go-os-rename which has since been fixed.
