### ISSUE TITLE
http.parseResponse: nil pointer deref in "marshalled error" branch

### ISSUE THREAD

**Issue by anguslees** [ipfs/go-ipfs#5386]
#### Version information:
Server and client are (separate instances of) ipfs/go-ipfs:v0.4.17 container

#### Type:
Bug

#### Description:

I think there's 2 related issues here:
1. The crash.
2. `--debug` doesn't give me any information to help debug this.  Eg: printing the raw HTTP request/response (or even just URL/headers) before parsing would be wonderful.

```
+ ipfs --debug '--api=/ip4/10.244.2.154/tcp/5001' add '--progress=true' '--wrap-with-directory=true' '--recursive=true' /tmp/staging
[0;37m22:43:29.555 [36mDEBUG [0;34m  cmd/ipfs: [0mconfig path is /data/ipfs [0;37mmain.go:100[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10a1f15]

goroutine 8 [running]:
gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/http.parseResponse(0xc420208990, 0xc4201f22a0, 0xc420208990, 0x0, 0x0, 0xc420046420)
	/go/src/gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/http/parse.go:215 +0x2b5
gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/http.(*client).Send(0xc4201f4a40, 0xc4201f22a0, 0xc4201f24d0, 0x1586660, 0xc4201f1380, 0x1)
	/go/src/gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/http/client.go:178 +0x51a
gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/http.(*client).Execute(0xc4201f4a40, 0xc4201f22a0, 0x1586660, 0xc4201f1380, 0x1571580, 0xc4201f4a00, 0x0, 0x0)
	/go/src/gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/http/client.go:108 +0xde
gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/cli.Run.func4(0x7f9df7b04888, 0xc4201f4a40, 0xc4201f22a0, 0x15866a0, 0xc4201f24d0, 0x1571580, 0xc4201f4a00, 0xc42008c360)
	/go/src/gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/cli/run.go:146 +0x70
created by gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/cli.Run
	/go/src/gx/ipfs/QmNueRyPRQiV7PUEpnP4GgGLuK1rKQLaRW7sfPvUetYig1/go-ipfs-cmds/cli/run.go:145 +0x6ac
```

**Comment by Stebalien** [comment]
1. Duplicate of https://github.com/ipfs/go-ipfs/issues/4998. The fix will be included in the next release.
2. The `debug` flag just tells IPFS to enable debug logging (it's not really related to the commands library or HTTP API).

**Comment by anguslees** [comment]
Thanks, closing this bug as a duplicate.
(I only searched on open bugs, which is why I hadn't found that one)

(And $http_proxy is almost certainly the cause of my error too)

**Comment by Stebalien** [comment]
It's always better to conservatively submit a duplicate. Thanks!
