### ISSUE TITLE
crash: exec command:ipfs repo gc

### ISSUE THREAD

**Issue by diwufeiwen** [ipfs/go-ipfs#5531]
Version information:

0.4.16

Type:

Bug (probably)

Description:
exec cmd:ipfs repo gc,the program will crash,detail:
```
16:00:54.771 ERROR  cmds/http: a panic has occurred in the commands handler! asm_amd64.s:573
16:00:54.774 ERROR  cmds/http: runtime error: invalid memory address or nil pointer dereference asm_amd64.s:573
16:00:54.777 ERROR  cmds/http: stack trace:
goroutine 255 [running]:
runtime/debug.Stack(0xc042214d40, 0xc0426152a0, 0x1)
        D:/Go/src/runtime/debug/stack.go:24 +0xae
gx/ipfs/QmaFrNcnXHp579hUixbcTH1TNtNwsMogtBCwUUUwzBwYoM/go-ipfs-cmds/http.(*handler).ServeHTTP.func1()
        D:/WorkSpace/gospace/src/gx/ipfs/QmaFrNcnXHp579hUixbcTH1TNtNwsMogtBCwUUUwzBwYoM/go-ipfs-cmds/http/handler.go:96 +0x130
panic(0xd09f80, 0x1570030)
        D:/Go/src/runtime/panic.go:502 +0x237
github.com/ipfs/go-ipfs/mfs.(*Root).GetValue(...)
        D:/WorkSpace/gospace/src/github.com/ipfs/go-ipfs/mfs/system.go:113
github.com/ipfs/go-ipfs/core/corerepo.BestEffortRoots(0x0, 0x1, 0x3f, 0x18, 0x101f6c0, 0xc04221f380)
        D:/WorkSpace/gospace/src/github.com/ipfs/go-ipfs/core/corerepo/gc.go:77 +0x2d
github.com/ipfs/go-ipfs/core/corerepo.GarbageCollectAsync(0xc04233a780, 0x101a260, 0xc0426d7440, 0x0)
        D:/WorkSpace/gospace/src/github.com/ipfs/go-ipfs/core/corerepo/gc.go:152 +0x4e
github.com/ipfs/go-ipfs/core/commands.glob..func129(0x1020c80, 0xc042615120, 0x1023320, 0xc0420a6a00)
        D:/WorkSpace/gospace/src/github.com/ipfs/go-ipfs/core/commands/repo.go:74 +0x11c
github.com/ipfs/go-ipfs/commands/legacy.NewCommand.func1(0xc04224b0a0, 0x45e0408, 0xc04224b110, 0x100e820, 0xc042621c80)
```
---
Edit by Kubuxu - added codeblock

**Comment by Stebalien** [comment]
That shouldn't be possible... Mind retrying with the latest release from https://dist.ipfs.io/go-ipfs/v0.4.17?

**Comment by diwufeiwen** [comment]
4.17 no problem,thanks!

**Comment by Stebalien** [comment]
Are you saying it works in 0.4.17?

**Comment by kevina** [comment]
I am going to assume this was fixed.  Closing.
