### ISSUE TITLE
Panic when use api dht/provide.

### ISSUE THREAD

**Issue by ivan386** [ipfs/go-ipfs#5616]
#### Version information:

go-ipfs version: 0.4.17-
Repo version: 7
System version: amd64/windows
Golang version: go1.10.3
#### Type:
Bug

#### Description:

config changes:
```
{
  "API": {
    "HTTPHeaders": {
     "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
		"User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    }
  },
"Addresses": {
"Swarm": []
}
  "Swarm": {
    "DisableNatPortMap": true
  }
}
```

I use fetch() in browser to send provide request to ipfs daemon. This error happen:
```
panic: send on closed channel

goroutine 2628 [running]:
gx/ipfs/QmZ383TySJVeZWzGnWui6pRcKyYZk9VkKTuW7tmKRWk5au/go-libp2p-routing/notifications.PublishQueryEvent(0x109d060, 0xc04287d840, 0xc04228ba80)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmZ383TySJVeZWzGnWui6pRcKyYZk9VkKTuW7tmKRWk5au/go-libp2p-routing/notifications/query.go:48 +0x151
gx/ipfs/QmTktQYCKzQjhxF6dk5xJPRuhHn3JBiKGvMLoiDy1mYmxC/go-libp2p-kad-dht.(*dhtQueryRunner).addPeerToQuery(0xc0425b52c0, 0xc04283a2d0, 0x22)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmTktQYCKzQjhxF6dk5xJPRuhHn3JBiKGvMLoiDy1mYmxC/go-libp2p-kad-dht/query.go:186 +0xee
gx/ipfs/QmTktQYCKzQjhxF6dk5xJPRuhHn3JBiKGvMLoiDy1mYmxC/go-libp2p-kad-dht.(*dhtQueryRunner).queryPeer(0xc0425b52c0, 0x10a4e60, 0xc043011740, 0xc0422e4360, 0x22)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmTktQYCKzQjhxF6dk5xJPRuhHn3JBiKGvMLoiDy1mYmxC/go-libp2p-kad-dht/query.go:307 +0x3bc
gx/ipfs/QmTktQYCKzQjhxF6dk5xJPRuhHn3JBiKGvMLoiDy1mYmxC/go-libp2p-kad-dht.(*dhtQueryRunner).spawnWorkers.func1(0x10a4e60, 0xc043011740)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmTktQYCKzQjhxF6dk5xJPRuhHn3JBiKGvMLoiDy1mYmxC/go-libp2p-kad-dht/query.go:218 +0x57
gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess.(*process).Go.func1(0xc0428acb60, 0xc043011740, 0xc0430117a0)
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess/impl-mutex.go:112 +0x43
created by gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess.(*process).Go
        /home/steb/projects/go/src/github.com/ipfs/distributions/dists/go-ipfs/gopath/src/gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess/impl-mutex.go:111 +0x216
```

**Comment by kisulken** [comment]
In fact, this happens with any request to dht sent after /dht/query

Here is an example of the same error that happened with /dht/get after querying
![screen shot 2018-10-21 at 3 43 09 pm](https://user-images.githubusercontent.com/7709243/47271565-7f020300-d548-11e8-9a7f-41a9a5ef74a1.png)

**Comment by Stebalien** [comment]
There's a fix in the works (for the panic, at least). There may be some other bug/change that's causing this but we'll have to fix that panic first.

**Comment by Stebalien** [comment]
Leaving this open till we bubble the fix.
