### ISSUE TITLE
There was a problem when I executed npm install go-ipfs

### ISSUE THREAD

**Issue by zcyzhu** [ipfs/go-ipfs#5883]
(1).I executed` npm install go-ipfs `and something went wrong.
```
Downloading https://dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-amd64.tar.gz
Error: connect ECONNREFUSED 69.171.248.65:443
Download failed!

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! go-ipfs-dep@0.4.18 install: `node src/bin.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the go-ipfs-dep@0.4.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zcy/.npm/_logs/2019-01-02T11_12_37_683Z-debug.log

```
(2).I want to perform an IPFS performance test on https://github.com/ipfs/ipfs-performance-profiling, which occurs when `npm install` is executed:
```
/home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep/src/index.js:102
      if (res.statusCode !== 200) {
              ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request.get [as _callback] (/home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep/src/index.js:102:15)
    at self.callback (/home/zcy/ipfs-performance-profiling/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/zcy/ipfs-performance-profiling/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! go-ipfs-dep@0.4.7 install: `node src/bin.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the go-ipfs-dep@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zcy/.npm/_logs/2019-01-02T10_58_25_571Z-debug.log

```
（3）I want to combine Ethereum and IPFS, but I chose the image in Dapp. When I click send, I didn't get the IPFS hash value. I used ganache-cli as the test chain, but metaMask didn't respond when I sent a image in Dapp
![_ p 0 x5zk w1wci3 acob8](https://user-images.githubusercontent.com/38487249/50591061-8dfe1d80-0ec8-11e9-95fd-658326d8452e.png)
![csff0hl_uxaxuxp 7g si 4](https://user-images.githubusercontent.com/38487249/50590955-0adcc780-0ec8-11e9-97ee-fd785294702d.png)
What is the reason for this? I always feel that this problem may be the same as the first two problems. I can only ask you now, thank you for answering these questions.
Some people say that it is a proxy problem. Some people say that it is a firewall. Some people say that it is a metaMask version. I am running on Linux. I feel that there may be a problem with the IPFS connection. I am using ubuntu, I don't know if it is a network configuration problem. I don't know how to solve it.

**Comment by eingenito** [comment]
Hey @zcyzhu - it's tricky for us to help troubleshoot your problems. 1 and 2 seem to be network connectivity related. 3 could also be a connectivity problem - it's difficult to tell. go-ipfs issues are for reporting bugs or requesting features in go-ipfs, and therefore your questions are going to the wrong audience. My best suggestion is trying the IPFS discussion forums at https://discuss.ipfs.io/. Good luck.

**Comment by Stebalien** [comment]
Use a proxy or a VPN? Alternatively, you can:

1. Find a working gateway with: https://ipfs.github.io/public-gateway-checker/
2. Set the environment variable `GO_IPFS_DIST_URL` to  "https://SOME_WORKING_GATEWAY/ipns/dist.ipfs.io"

That will allow you to download IPFS from a different gateway.

**Comment by zcyzhu** [comment]
Thank you, thank you very much for your help, you will need your help in the future.

**Comment by zcyzhu** [comment]
@Stebalien,Can you be more specific? I found a gateway such as: https://ipfs.infura.io/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a, how do I use it?
How do I set the environment variable GO_IPFS_DIST_URL to "https://SOME_WORKING_GATEWAY/ipns/dist.ipfs.io"  .Thanks

**Comment by Stebalien** [comment]
That depends on your operating system. On everything but windows, you should be able to run: `GO_IPFS_DIST_URL="https://ipfs.infura.io/ipns/dist.ipfs.io" npm install go-ipfs`

**Comment by zcyzhu** [comment]
@Stebalien ，I am running npm install at https://github.com/ipfs/ipfs-performance-profiling or I am getting an error.
```
home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep/src/index.js:102
      if (res.statusCode !== 200) {
              ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request.get [as _callback] (/home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep/src/index.js:102:15)
    at self.callback (/home/zcy/ipfs-performance-profiling/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/zcy/ipfs-performance-profiling/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! go-ipfs-dep@0.4.7 install: `node src/bin.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the go-ipfs-dep@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I want to cry.Is there any other way to test IPFS performance?

**Comment by zcyzhu** [comment]
@Stebalien ，I am a student, so I need your help.Sorry to bother you again, but I can't get help except here.
```
zcy@ubuntu:~/ipfs-performance-profiling$ GO_IPFS_DIST_URL="https://hardbin.com/ipns/dist.ipfs.io/"
zcy@ubuntu:~/ipfs-performance-profiling$ npm install
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> go-ipfs-dep@0.4.7 install /home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep
> node src/bin.js

Downloading https://dist.ipfs.io/go-ipfs/v0.4.7/go-ipfs_v0.4.7_linux-amd64.tar.gz
/home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep/src/index.js:102
      if (res.statusCode !== 200) {
              ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request.get [as _callback] (/home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep/src/index.js:102:15)
    at self.callback (/home/zcy/ipfs-performance-profiling/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/zcy/ipfs-performance-profiling/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! go-ipfs-dep@0.4.7 install: `node src/bin.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the go-ipfs-dep@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zcy/.npm/_logs/2019-01-15T01_37_13_237Z-debug.log

```
I used the gateway in your way, but why the website is still downloaded from `Downloading https://dist.ipfs.io/go-ipfs/v0.4.7/go-ipfs_v0.4.7_linux-amd64.tar.gz`

**Comment by zcyzhu** [comment]
@Stebalien ，The great teacher, I succeeded, thank you for your guidance, my last problem was finally solved, and many methods were useless before.
```
Downloading https://hardbin.com/ipns/dist.ipfs.io//go-ipfs/v0.4.7/go-ipfs_v0.4.7_linux-amd64.tar.gz
/home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep/src/index.js:102
      if (res.statusCode !== 200) {
              ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.request.get [as _callback] (/home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep/src/index.js:102:15)
    at self.callback (/home/zcy/ipfs-performance-profiling/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/home/zcy/ipfs-performance-profiling/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! go-ipfs-dep@0.4.7 install: `node src/bin.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the go-ipfs-dep@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zcy/.npm/_logs/2019-01-15T09_21_59_256Z-debug.log
zcy@ubuntu:~/ipfs-performance-profiling$  GO_IPFS_DIST_URL=https://hardbin.com/ipns/dist.ipfs.io npm install
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> go-ipfs-dep@0.4.7 install /home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep
> node src/bin.js

Downloading https://hardbin.com/ipns/dist.ipfs.io/go-ipfs/v0.4.7/go-ipfs_v0.4.7_linux-amd64.tar.gz
Downloaded ipfs_v0.4.7_linux-amd64.tar.gz
Installed go-ipfs v0.4.7 linux-amd64 to /home/zcy/ipfs-performance-profiling/node_modules/go-ipfs-dep/go-ipfs/
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 22 packages from 23 contributors in 145.954s

```

**Comment by Stebalien** [comment]
Note, you can also use:

```bash
$ export GO_IPFS_DIST_URL="https://hardbin.com/ipns/dist.ipfs.io/"
$ npm install
```

Which is (mostly) equivalent to:

```bash
$ GO_IPFS_DIST_URL=https://hardbin.com/ipns/dist.ipfs.io npm install
```

**Comment by zcyzhu** [comment]
@Stebalien ，yes,thank you
