### ISSUE TITLE
panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by gaillard** [ipfs/go-ipfs#5961]
#### Version information:

go-ipfs version: 0.4.19-dev-aefb372
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.1

#### Type:
- "panic": If you'd like to report an application panic, segfault, crash, etc.

#### Description:

Just trying to help if this panic is useful, I was just browsing `http://127.0.0.1:8081/ipns/docs.ipfs.io`.

```
Initializing daemon...
go-ipfs version: 0.4.19-dev-aefb372
Repo version: 7
System version: amd64/darwin
Golang version: go1.11.1

Swarm listening on /ip4/MYIP2/tcp/4003
Swarm listening on /ip4/MYIP2/tcp/4004/ws
Swarm listening on /ip4/127.0.0.1/tcp/4003
Swarm listening on /ip4/127.0.0.1/tcp/4004/ws
Swarm listening on /ip4/MYIP/tcp/4003
Swarm listening on /ip4/MYIP/tcp/4004/ws
Swarm listening on /p2p-circuit
Swarm announcing /ip4/MYIP2/tcp/4003
Swarm announcing /ip4/MYIP2/tcp/4004/ws
Swarm announcing /ip4/127.0.0.1/tcp/4003
Swarm announcing /ip4/127.0.0.1/tcp/4004/ws
Swarm announcing /ip4/MYIP/tcp/4003
Swarm announcing /ip4/MYIP/tcp/4004/ws
API server listening on /ip4/127.0.0.1/tcp/5002
WebUI: http://127.0.0.1:5002/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8081
Daemon is ready
panic: concurrent write to websocket connection

goroutine 269354 [running]:
gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket.(*messageWriter).flushFrame(0xc0039273b0, 0x6417101, 0x0, 0x0, 0x0, 0x1bd42a0, 0x0)
	/Users/me/go/src/gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket/conn.go:585 +0x68b
gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket.(*messageWriter).Close(0xc0039273b0, 0x0, 0x6417148)
	/Users/me/go/src/gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket/conn.go:699 +0x56
gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket.(*Conn).prepWrite(0xc005a6cdc0, 0x2, 0x0, 0x0)
	/Users/me/go/src/gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket/conn.go:468 +0x10a
gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket.(*Conn).NextWriter(0xc005a6cdc0, 0x2, 0xc0011bd750, 0x10, 0xc005a6ce80, 0xc003c95c38)
	/Users/me/go/src/gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket/conn.go:488 +0x39
gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket.(*Conn).WriteMessage(0xc005a6cdc0, 0x2, 0xc0046e4000, 0x23, 0x1000, 0xc000e75800, 0x1)
	/Users/me/go/src/gx/ipfs/QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts/websocket/conn.go:745 +0x76
gx/ipfs/QmPMuvbzktV1oUfBVf6dc3t2DF5qyB2pKKqhDfAZbcbRg6/go-ws-transport.(*Conn).Write(0xc002480680, 0xc0046e4000, 0x23, 0x1000, 0xc003c95cd8, 0x100e448, 0x1)
	/Users/me/go/src/gx/ipfs/QmPMuvbzktV1oUfBVf6dc3t2DF5qyB2pKKqhDfAZbcbRg6/go-ws-transport/conn.go:75 +0x59
bufio.(*Writer).Flush(0xc002480700, 0xc002480700, 0xc003b1c060)
	/usr/local/go/src/bufio/bufio.go:575 +0x75
gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream.delimWriteBuffered(0x2f9e230, 0xc003943830, 0xc003b1c060, 0x21, 0x30, 0x30, 0xc000066ed0)
	/Users/me/go/src/gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream/multistream.go:64 +0xbd
gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream.ReadNextTokenBytes(0x2f9e250, 0xc003943830, 0x100bd08, 0x1bbdfa0, 0x1c80f40, 0xc000e71b00, 0x2f9e250)
	/Users/me/go/src/gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream/multistream.go:380 +0x190
gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream.ReadNextToken(0x2f9e250, 0xc003943830, 0xc003943830, 0x2f9e250, 0xc003943830, 0x15e073f)
	/Users/me/go/src/gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream/multistream.go:364 +0x39
gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream.handshake(0x2f9e200, 0xc003943830, 0x0, 0xc003942420)
	/Users/me/go/src/gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream/client.go:52 +0xb2
gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream.SelectOneOf(0xc0002e50b0, 0x1, 0x1, 0x2f9e200, 0xc003943830, 0x0, 0x0, 0xc0038927b8, 0x15e01f7)
	/Users/me/go/src/gx/ipfs/QmabLh8TrJ3emfAoQk5AbqbLTbMyj7XqumMFmAFxa9epo8/go-multistream/client.go:28 +0x3f
gx/ipfs/QmXrweWQgN62WvMcP2EWDpD2qYXiFqenqdaLjUzX7yBqLv/go-conn-security-multistream.(*SSMuxer).selectProto.func1(0xc002b9d740, 0x1b31500, 0xc0002e8e80, 0x2f9e1a8, 0xc003943830, 0xc0021a4840, 0xc0021a4850)
	/Users/me/go/src/gx/ipfs/QmXrweWQgN62WvMcP2EWDpD2qYXiFqenqdaLjUzX7yBqLv/go-conn-security-multistream/ssms.go:68 +0x192
created by gx/ipfs/QmXrweWQgN62WvMcP2EWDpD2qYXiFqenqdaLjUzX7yBqLv/go-conn-security-multistream.(*SSMuxer).selectProto
	/Users/me/go/src/gx/ipfs/QmXrweWQgN62WvMcP2EWDpD2qYXiFqenqdaLjUzX7yBqLv/go-conn-security-multistream/ssms.go:63 +0xe5
```

**Comment by zebul** [comment]
I encountered a similar problem and solved it by moving the go-ipfs directory.  I have installed ipfs on a few machines (Linux and Windows).  I encountered this problem only when using ipfs-update to install in Linux.  go-ipfs was placed in my go/bin directory (usr/local/go/bin) and I solved the problem by moving the go-ipfs directory to usr/local/ (outside of the go directory).  Hope this helps.

**Comment by Stebalien** [comment]
I believe this has now been fixed upstream. @zebul could you try building the latest master?
