### ISSUE TITLE
Pinning interop broken

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs#6534]
#### Version information:

https://github.com/ipfs/go-ipfs/pull/6533

#### Description:

`pin rm` interop test is broken.

```
  1) pin
       pin rm
         pin recursively, remove the root pin:
     Uncaught TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at send (node_modules/ipfs-http-client/src/pin/ls.js:28:29)
      at f (node_modules/once/once.js:25:25)
      at streamToValue (node_modules/ipfs-http-client/src/utils/stream-to-json-value.js:30:5)
      at pump (node_modules/ipfs-http-client/src/utils/stream-to-value.js:14:14)
      at /home/circleci/ipfs/go-ipfs/interop/node_modules/ipfs-http-client/node_modules/pump/index.js:75:7
      at f (node_modules/once/once.js:25:25)
      at ConcatStream.<anonymous> (node_modules/ipfs-http-client/node_modules/pump/index.js:33:5)
      at ConcatStream.f (node_modules/once/once.js:25:25)
      at ConcatStream.onfinish (node_modules/end-of-stream/index.js:30:27)
      at finishMaybe (node_modules/ipfs-http-client/node_modules/readable-stream/lib/_stream_writable.js:620:14)
      at endWritable (node_modules/ipfs-http-client/node_modules/readable-stream/lib/_stream_writable.js:629:3)
      at ConcatStream.Writable.end (node_modules/ipfs-http-client/node_modules/readable-stream/lib/_stream_writable.js:567:22)
      at IncomingMessage.onend (_stream_readable.js:655:10)
      at endReadableNT (_stream_readable.js:1129:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by aschmahmann** [comment]
Closed by #6685
