### ISSUE TITLE
0.5.0-dev-3cb33b2 crashing hourly

### ISSUE THREAD

**Issue by gmasgras** [ipfs/go-ipfs#6722]
#### Version information:
```
go-ipfs version: 0.5.0-dev-3cb33b2
Repo version: 7
System version: amd64/linux
Golang version: go1.12.9
```

#### Description:
Running commit `3cb33b22ea2774b3eacb067a3f22dca8d8cf24a9` of `feat/stabilize-dht` results in hourly crashes with ` panic: runtime error: invalid memory address or nil pointer dereference`. 

Also noticed that even though `"HighWater": 5000`, the number of peers stays between 9-14k

Crash trace:
```
ipfs[16659]: Daemon is ready
ipfs[16659]: 2019-10-22 16:56:54.968581 ERROR dht dht.go:320: called update on a peer with no connection
ipfs[16659]: 2019-10-22 16:59:54.930702 ERROR dht dht.go:320: called update on a peer with no connection
ipfs[16659]: 2019-10-22 17:02:54.914289 ERROR dht dht.go:320: called update on a peer with no connection
ipfs[16659]: 2019-10-22 17:06:55.286257 ERROR dht dht.go:320: called update on a peer with no connection
ipfs[16659]: panic: runtime error: invalid memory address or nil pointer dereference
ipfs[16659]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x111ab87]
ipfs[16659]: goroutine 42303041 [running]:
ipfs[16659]: github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).sendRequest(0xc0000d4900, 0x1aeba80, 0xc0787907b0, 0xc053456390, 0x22, 0xc03c31fe00, 0x1, 0x1, 0xc065e320a0)
                     pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.2.2-0.20190912025123-02d0ee9bca9e/dht_net.go:215 +0x487
ipfs[16659]: github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).findPeerSingle(0xc0000d4900, 0x1aeb9c0, 0xc01c430600, 0xc053456390, 0x22, 0xc07ae89b00, 0x22, 0x0, 0x0, 0x0)
ipfs[16659]:         pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.2.2-0.20190912025123-02d0ee9bca9e/dht.go:415 +0x30a
ipfs[16659]: github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).FindPeer.func2(0x1aeb9c0, 0xc01c430600, 0xc053456390, 0x22, 0x1aeb9c0, 0xc01c430600, 0xc07d0296f0)
ipfs[16659]:         pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.2.2-0.20190912025123-02d0ee9bca9e/routing.go:642 +0x114
ipfs[16659]: github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).queryPeer(0xc018387680, 0x1afe0a0, 0xc03810f680, 0xc053456390, 0x22)
ipfs[16659]:         pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.2.2-0.20190912025123-02d0ee9bca9e/query.go:282 +0xef
ipfs[16659]: github.com/libp2p/go-libp2p-kad-dht.(*dhtQueryRunner).spawnWorkers.func1(0x1afe0a0, 0xc03810f680)
ipfs[16659]:         pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.2.2-0.20190912025123-02d0ee9bca9e/query.go:228 +0x50
ipfs[16659]: github.com/jbenet/goprocess.(*process).Go.func1(0xc065e32040, 0xc03810f680, 0xc03810f740)
ipfs[16659]:         pkg/mod/github.com/jbenet/goprocess@v0.1.3/impl-mutex.go:134 +0x3c
ipfs[16659]: created by github.com/jbenet/goprocess.(*process).Go
ipfs[16659]:         pkg/mod/github.com/jbenet/goprocess@v0.1.3/impl-mutex.go:133 +0x1f7
```
-->

**Comment by Stebalien** [comment]
> Also noticed that even though "HighWater": 5000, the number of peers stays between 9-14k

Would it be possible to generate a histogram of peer ages (e.g., by dumping the list of peers every second for ~1hr).

**Comment by Stebalien** [comment]
Fixing and rebasing.

**Comment by olizilla** [comment]
Can confirm that `0.5.0-dev-096f70d` seems to be much less crashy. We're 12hrs into running it on the gateway with zero crashes.
