### ISSUE TITLE
Badger still crashing on shutdown after latest fixes

### ISSUE THREAD

**Issue by ribasushi** [ipfs/go-ipfs#6986]
#### Version information:

Local build off https://github.com/ipfs/go-ipfs/commit/6ae79efc2f86

```
go-ipfs version: 0.5.0-dev
Repo version: 7
System version: amd64/darwin
Golang version: go1.14
```

#### Description:
Badger crashes on shutdown despite the latest merged fixes ( this issues is **separate** from https://github.com/ipfs/go-ipfs/issues/6985 ). ~@Stebalien I actually can not find a badger-related merge in master's history...~ nevermind, apparently this was fixed ages ago, which is why I couldn't find it. 

```
... | go run ./cmd/ipfs --encoding=json add --progress=false --chunker=rabin --trickle=false --raw-leaves=true --cid-version=1 
added bafybeicms4x7k62edxnnyysfufsotnivbfjoj6a7aouujcgg4l2kasnsey bafybeicms4x7k62edxnnyysfufsotnivbfjoj6a7aouujcgg4l2kasnsey
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x4abe3b1]

goroutine 65 [running]:
github.com/dgraph-io/badger/skl.(*Skiplist).IncrRef(...)
	/Users/admin/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/skl/skl.go:86
github.com/dgraph-io/badger.(*DB).getMemTables(0xc0000c2000, 0x0, 0x0, 0x0, 0x0)
	/Users/admin/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/db.go:481 +0xd1
github.com/dgraph-io/badger.(*Txn).NewIterator(0xc0000b2380, 0x1, 0x64, 0x0, 0xc00052c360, 0x13, 0x20, 0x0, 0x0)
	/Users/admin/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/iterator.go:407 +0x89
github.com/ipfs/go-ds-badger.(*txn).query(0xc00000e680, 0xc00019b760, 0x12, 0x0, 0x0, 0x0, 0xc0005105b0, 0x1, 0x1, 0x1, ...)
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ds-badger@v0.2.1/datastore.go:601 +0x1f1
github.com/ipfs/go-ds-badger.(*Datastore).Query(0xc0000a73e0, 0xc00019b760, 0x12, 0x0, 0x0, 0x0, 0xc0005105b0, 0x1, 0x1, 0x1, ...)
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ds-badger@v0.2.1/datastore.go:329 +0x12a
github.com/ipfs/go-ds-measure.(*measure).Query(0xc0000ec000, 0xc00019b760, 0x12, 0x0, 0x0, 0x0, 0xc0005105b0, 0x1, 0x1, 0x1, ...)
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ds-measure@v0.1.0/measure.go:246 +0x12b
github.com/ipfs/go-ds-measure.(*measure).Query(0xc0000ec300, 0xc00019b760, 0x12, 0x0, 0x0, 0x0, 0xc0005105b0, 0x1, 0x1, 0x1, ...)
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ds-measure@v0.1.0/measure.go:246 +0x12b
github.com/ipfs/go-datastore/keytransform.(*Datastore).Query(0xc0003a81e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0005105b0, 0x1, 0x1, 0x1, ...)
	/Users/admin/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/keytransform/keytransform.go:71 +0x1d5
github.com/ipfs/go-ipfs-provider/queue.(*Queue).getQueueHead(0xc000398ff0, 0x0, 0x0, 0x0)
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ipfs-provider@v0.3.0/queue/queue.go:137 +0x124
github.com/ipfs/go-ipfs-provider/queue.(*Queue).work.func1(0xc000398ff0)
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ipfs-provider@v0.3.0/queue/queue.go:83 +0x782
created by github.com/ipfs/go-ipfs-provider/queue.(*Queue).work
	/Users/admin/go/pkg/mod/github.com/ipfs/go-ipfs-provider@v0.3.0/queue/queue.go:73 +0x3f
exit status 2
```

**Comment by hsanjuan** [comment]
Is #7015 the fix-approach for this? Still happening on master (when adding offline).

**Comment by Stebalien** [comment]
Damn. I thought I fixed it.
