### ISSUE TITLE
Intermittent failure: failed to negotiate security protocol: error reading handshake message: noise: message is too short

### ISSUE THREAD

**Issue by achingbrain** [ipfs/go-ipfs#7734]
#### Version information:

go-ipfs 0.7.0

#### Description:

I'm seeing an intermittent failure in the setup of the [transfer a block between 3 peers](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/bitswap/transfer.js#L50-L72) interface test:

```
HTTPError: connect 12D3KooWDuMRjYxBhRFAoftyEDvZmHuycj1XAVikFW6pnD7pwXoG failure: failed to dial 12D3KooWDuMRjYxBhRFAoftyEDvZmHuycj1XAVikFW6pnD7pwXoG: all dials failed
* [/ip4/127.0.0.1/tcp/59690] failed to negotiate security protocol: error reading handshake message: noise: message is too short
    at Object.errorHandler [as handleError] (/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-http-client/src/lib/core.js:75:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Client.fetch (/Users/alex/Documents/Workspaces/ipfs/js-ipfs/node_modules/ipfs-utils/src/http.js:156:9)
    at async Object.connect (/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/ipfs-http-client/src/swarm/connect.js:10:17)
    at async Context.<anonymous> (/Users/alex/Documents/Workspaces/ipfs/js-ipfs/packages/interface-ipfs-core/src/bitswap/transfer.js:57:9)
```

The test is running under node and the three go-IPFS nodes are orchestrated via the http api using the ipfs-http-client.

**Comment by Stebalien** [comment]
Maybe a handshake timeout in js or go?

**Comment by jacobheun** [comment]
There is an existing issue in Noise around simultaneous connects, https://github.com/libp2p/go-libp2p-noise/issues/70, since this is intermittent this could be the issue.

**Comment by Stebalien** [comment]
The upstream issue has been closed. Comment if this is still an issue and I can reopen it.
