### ISSUE TITLE
ipfs config profile apply hangs after unclean shutdown.

### ISSUE THREAD

**Issue by kevincox** [ipfs/go-ipfs#8407]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

third-party binary

### Version

```Text
go-ipfs version: 0.9.1
Repo version: 11
System version: amd64/linux
Golang version: go1.16.7
```

### Config

```json
{
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Origin": [
        "https://REDACTED"
      ]
    }
  },
  "Addresses": {
    "API": "/unix/run/ipfs-api.sock",
    "Announce": [],
    "Gateway": "/unix/run/ipfs-gateway.sock",
    "NoAnnounce": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "Swarm": [
      "/ip4/0.0.0.0/tcp/4001",
      "/ip6/::/tcp/4001",
      "/ip4/0.0.0.0/udp/4001/quic",
      "/ip6/::/udp/4001/quic"
    ]
  },
  "AutoNAT": {},
  "Bootstrap": [
    "/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
    "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"
  ],
  "DNS": {
    "Resolvers": null
  },
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "Spec": {
      "mounts": [
        {
          "child": {
            "path": "blocks",
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2",
            "sync": true,
            "type": "flatfs"
          },
          "mountpoint": "/blocks",
          "prefix": "flatfs.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "StorageGCWatermark": 90,
    "StorageMax": "10GB"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": false,
      "Interval": 10
    }
  },
  "Experimental": {
    "AcceleratedDHTClient": false,
    "FilestoreEnabled": false,
    "GraphsyncEnabled": false,
    "Libp2pStreamMounting": false,
    "P2pHttpProxy": false,
    "ShardingEnabled": false,
    "StrategicProviding": false,
    "UrlstoreEnabled": false
  },
  "Gateway": {
    "APICommands": [],
    "HTTPHeaders": {
      "Access-Control-Allow-Headers": [
        "X-Requested-With",
        "Range",
        "User-Agent"
      ],
      "Access-Control-Allow-Methods": [
        "GET"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    },
    "NoDNSLink": false,
    "NoFetch": false,
    "PathPrefixes": [],
    "PublicGateways": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
    "PeerID": "REDACTED"
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Migration": {
    "DownloadSources": null,
    "Keep": ""
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "Peering": {
    "Peers": null
  },
  "Pinning": {},
  "Plugins": {
    "Plugins": null
  },
  "Provider": {
    "Strategy": ""
  },
  "Pubsub": {
    "DisableSigning": false,
    "Router": ""
  },
  "Reprovider": {
    "Interval": "12h",
    "Strategy": "all"
  },
  "Routing": {
    "Type": "dht"
  },
  "Swarm": {
    "AddrFilters": [
      "/ip4/10.0.0.0/ipcidr/8",
      "/ip4/100.64.0.0/ipcidr/10",
      "/ip4/169.254.0.0/ipcidr/16",
      "/ip4/172.16.0.0/ipcidr/12",
      "/ip4/192.0.0.0/ipcidr/24",
      "/ip4/192.0.2.0/ipcidr/24",
      "/ip4/192.168.0.0/ipcidr/16",
      "/ip4/198.18.0.0/ipcidr/15",
      "/ip4/198.51.100.0/ipcidr/24",
      "/ip4/203.0.113.0/ipcidr/24",
      "/ip4/240.0.0.0/ipcidr/4",
      "/ip6/100::/ipcidr/64",
      "/ip6/2001:2::/ipcidr/48",
      "/ip6/2001:db8::/ipcidr/32",
      "/ip6/fc00::/ipcidr/7",
      "/ip6/fe80::/ipcidr/10"
    ],
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 900,
      "LowWater": 600,
      "Type": "basic"
    },
    "DisableBandwidthMetrics": false,
    "DisableNatPortMap": true,
    "EnableAutoRelay": false,
    "EnableRelayHop": false,
    "Transports": {
      "Multiplexers": {},
      "Network": {},
      "Security": {}
    }
  }
}
```

### Description

Sometimes after an unclean shutdown (My server is often hanging and getting killed by SIGKILL) running `ipfs profile apply PROFILE` hangs.

```zsh
% ipfs -D --local config profile apply server
2021-09-02T13:21:15.151Z	DEBUG	cmd/ipfs	ipfs/main.go:130	config path is /var/lib/ipfs
```

I have found that this can be mitigated by starting the daemon temporarily (which presumably cleans up the repo) then `ipfs profile apply` works as expected.

Presumably `ipfs profile apply` (and all commands) need to do the appropriate cleanup if the repo is in an unclean shutdown state.

**Comment by Stebalien** [comment]
Both should clean the repo. Could you post the "goroutine" dumps described in https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md? Tat'll help us figure out what's hanging.

**Comment by Stebalien** [comment]
Note: the hang could be due to https://github.com/ipfs/go-ipfs/issues/8149, but I'd expect it to _always_ hang in that case, not _just_ hang when applying a profile.

**Comment by kevincox** [comment]
It definitely only hangs on the profile apply. I didn't try other commands but once finding the workaround of starting the daemon it was solved the issue a number of times while no amout of restarting the profile command did. 

I'll try to grab a stack dump next time this happens.

**Comment by kevincox** [comment]
Hi @Stebalien the info in https://github.com/ipfs/go-ipfs/blob/master/docs/debug-guide.md appears to assume that there is an ipfs daemon running. I am currently running `ipfs config profile apply` before the daemon is running (so that it can be run with the correct settings) so none of the provided steps to get stack traces and similar appear to apply.

**Comment by Stebalien** [comment]
Bleh, sorry about that. Could you try killing `ipfs config profile apply` with a `SIGQUIT` (`killall -QUIT ipfs`) and capturing the output?

**Comment by kevincox** [comment]
```
	net/http/transport.go:592 +0xacb
net/http.(*Transport).RoundTrip(0xc0002228c0, 0xc001778400, 0xc0002228c0, 0x0, 0x0)
	net/http/roundtrip.go:17 +0x35
net/http.send(0xc001778400, 0x230bde0, 0xc0002228c0, 0x0, 0x0, 0x0, 0xc000010750, 0xc00188cab0, 0x1, 0x0)
	net/http/client.go:251 +0x454
net/http.(*Client).send(0xc001888ae0, 0xc001778400, 0x0, 0x0, 0x0, 0xc000010750, 0x0, 0x1, 0xd0000c0017fdb00)
	net/http/client.go:175 +0xff
net/http.(*Client).do(0xc001888ae0, 0xc001778400, 0x0, 0x0, 0x0)
	net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	net/http/client.go:585
github.com/ipfs/go-ipfs-cmds/http.(*client).send(0xc00021e1e0, 0xc00177e150, 0x0, 0x0, 0x230a660, 0xc00166c920)
	github.com/ipfs/go-ipfs-cmds@v0.6.0/http/client.go:204 +0x165
github.com/ipfs/go-ipfs-cmds/http.(*client).Execute(0xc00021e1e0, 0xc00177e150, 0x2332ac8, 0xc0017ea780, 0x1ddd220, 0xc0017ea660, 0xc0017ea780, 0x0)
	github.com/ipfs/go-ipfs-cmds@v0.6.0/http/client.go:101 +0x8b
github.com/ipfs/go-ipfs-cmds/cli.Run(0x23326d8, 0xc0011930c0, 0x2f5dfc0, 0xc00003c1e0, 0x6, 0x6, 0xc000010010, 0xc000010018, 0xc000010020, 0x2195470, ...)
	github.com/ipfs/go-ipfs-cmds@v0.6.0/cli/run.go:137 +0xab8
main.mainRet(0x0)
	github.com/ipfs/go-ipfs/cmd/ipfs/main.go:168 +0x45e
main.main()
	github.com/ipfs/go-ipfs/cmd/ipfs/main.go:71 +0x25
goroutine 6 [select, 4 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc00010de00)
	github.com/ipfs/go-log@v1.0.5/writer/writer.go:71 +0x106
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	github.com/ipfs/go-log@v1.0.5/writer/writer.go:36 +0xb9
goroutine 37 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000214600)
	go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xcd
created by go.opencensus.io/stats/view.init.0
	go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x68
goroutine 13 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	runtime/sigqueue.go:168 +0xa5
os/signal.loop()
	os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x45
goroutine 53 [select, 4 minutes]:
github.com/ipfs/go-ipfs/cmd/ipfs/util.(*IntrHandler).Handle.func1(0xc00020a630, 0xc0011dc2a0, 0xc00118cff0)
	github.com/ipfs/go-ipfs/cmd/ipfs/util/signal.go:47 +0x11d
created by github.com/ipfs/go-ipfs/cmd/ipfs/util.(*IntrHandler).Handle
	github.com/ipfs/go-ipfs/cmd/ipfs/util/signal.go:41 +0xbe
goroutine 55 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7f9f39d83eb8, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00015e498, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00015e480, 0xc0017f1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc00015e480, 0xc0017f1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010760, 0xc0017f1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc00189a000, 0xc0017f1000, 0x1000, 0x1000, 0xb4dd10, 0x60, 0x0)
	net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc0017eaa20)
	bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc0017eaa20, 0x1, 0xc0002be420, 0x0, 0x0, 0x0, 0x0)
	bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc00189a000)
	net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
	net/http/transport.go:1743 +0xc77
goroutine 56 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc00189a000)
	net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	net/http/transport.go:1744 +0xc9c
rax    0xca
rbx    0x2f5ed80
rcx    0xbbdf63
rdx    0x0
rdi    0x2f5eed0
rsi    0x80
rbp    0x7ffc989bae60
rsp    0x7ffc989bae18
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc00005a7a4
r13    0x0
r14    0x1
r15    0x0
rip    0xbbdf61
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by kevincox** [comment]
It sounds to me like it is trying to connect to the daemon which isn't running. Maybe on an unclean shutdown it thinks that the daemon is alive?

Is there a way to tell it not to try and talk to the daemon?

**Comment by Stebalien** [comment]
I think the unix domain sockets are causing issues in this case. Usually, the connection will get rejected and we'll fallback on running the command locally.

Are you using systemd socket activation? If so, set `FlushPending=yes` in the socket unit.

**Comment by kevincox** [comment]
I would prefer not to set that. I like that restarts are seamless. Would it be possible to tell `ipfs config profile apply` to not try to connect to the socket or otherwise work correctly even after an unclean shutdown?

**Comment by Stebalien** [comment]
You can remove the `$IPFS_REPO/api` file first. But if it exists, we'll try to connect to the listed API. If that endpoint hangs, there isn't really anything we can do.

**Comment by kevincox** [comment]
I'll implement that fix. It would be nice if there was a flag to ignore that fix for people who know that they are configuring before starting the daemon.

**Comment by Stebalien** [comment]
This is an exceedingly unusual situation. You:

1. Have a valid "api" file.
2. Something listening on the API endpoint that hangs forever.

The best solution would be to either not have something that listens on the API port and hangs. Alternatively, let systemd actually start go-ipfs so the command will succeed.

Telling go-ipfs to "please ignore the running daemon and do the thing anyways" would usually just fail to lock the repo.

**Comment by kevincox** [comment]
systemd is starting IPFS.

The problem is that I want to apply a configuration before starting it. Another option would be to separate IPFS configuration and state so that we could just pass a fixed configuration file. But right now I think the config file effectively needs to be writable.

> Telling go-ipfs to "please ignore the running daemon and do the thing anyways" would usually just fail to lock the repo.

This actually seems like a much cleaner solution. Better to Ask For Forgiveness than Permission. Try to lock the repo and make the change ourselves, if that fails because the repo is locked then see if the running daemon can do it.

**Comment by kevincox** [comment]
> 2. Have an "api" file pointing to a remote go-ipfs daemon.

Ah yes. That case does make sense if you want to edit the remote config.

**Comment by kevincox** [comment]
Removing `$IPFS_REPO/api` appears to just cause everything to lock up due to stale lockfiles. I got the service to start up again by removing `$IPFS_REPO/repo.lock` and `$IPFS_REPO/datastore/LOCK`.

**Comment by Stebalien** [comment]
> Removing $IPFS_REPO/api appears to just cause everything to lock up due to stale lockfiles. I got the service to start up again by removing $IPFS_REPO/repo.lock and $IPFS_REPO/datastore/LOCK.

Those can't be stale (on most platforms) because we use we use flock (which is automatically released when go-ipfs exits). That usually means go-ipfs _is_ running, or at least something is holding onto the lock. Check `fuser` and/or `lsof` to see who's using the lock (and avoid deleting these files as that will likely lead to repo corruption).

**Comment by kevincox** [comment]
This problem persisted across a reboot and go-ipfs wasn't running. I'll take another look if IPFS locks up agian.
