### ISSUE TITLE
nil pointer dereference in /api/v0/add

### ISSUE THREAD

**Issue by feld** [ipfs/go-ipfs#8523]
### Checklist

- [X] This is a bug report, not a question. Ask questions on [discuss.ipfs.io](https://discuss.ipfs.io).
- [X] I have searched on the [issue tracker](https://github.com/ipfs/go-ipfs/issues?q=is%3Aissue) for my bug.
- [X] I am running the latest [go-ipfs version](https://dist.ipfs.io/#go-ipfs) or have an issue updating.

### Installation method

built from source

### Version

```Text
go-ipfs version: 0.9.1
Repo version: 11
System version: amd64/freebsd
Golang version: go1.17
```

### Config

```json
n/a
```

### Description

If you send a malformed request to `/api/v0/add` you can trigger this crash. In my case it was due to a buggy http client that was failing to do multipart correctly. The result was that it was not passing any form parameters and the body was like this:

```
b'--3016153d38093a6b453ff98f82524060\r\ncontent-type: multipart/form-data\r\ncontent-disposition: form-data; name="file"; filename="index.html"\r\n\r\n<!DOCTYPE html>\n<html>redacted</html>\n\r\n--3016153d38093a6b453ff98f82524060—\r\n’
```

crash log:

```
2021-10-21T17:45:25.717Z	^[[31mERROR^[[0m	cmds/http	http/handler.go:94	a panic has occurred in the commands handler!
2021-10-21T17:45:25.717Z	^[[31mERROR^[[0m	cmds/http	http/handler.go:95	runtime error: invalid memory address or nil pointer dereference
2021-10-21T17:45:25.717Z	^[[31mERROR^[[0m	cmds/http	http/handler.go:96	stack trace:
goroutine 167399509 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x9f
github.com/ipfs/go-ipfs-cmds/http.(*handler).ServeHTTP.func1()
	github.com/ipfs/go-ipfs-cmds@v0.6.0/http/handler.go:96 +0x15b
panic({0xabf0c0, 0x2c06fb0})
	runtime/panic.go:1052 +0x2fe
bufio.(*Reader).fill(0xc00f7aa2a0)
	bufio/bufio.go:101 +0xf6
bufio.(*Reader).ReadSlice(0xc00f7aa2a0, 0xa)
	bufio/bufio.go:360 +0x3d
bufio.(*Reader).collectFragments(0xc00f7aa2a0, 0xa)
	bufio/bufio.go:435 +0x7a
bufio.(*Reader).ReadString(0xc00f7aa2a0, 0xa)
	bufio/bufio.go:483 +0x4f
github.com/ipfs/go-ipfs-cmds.(*arguments).Scan(0xc00829c380)
	github.com/ipfs/go-ipfs-cmds@v0.6.0/arguments.go:75 +0x45
github.com/ipfs/go-ipfs-cmds.(*Command).CheckArguments(0x2c25da0, 0xc00b556460)
	github.com/ipfs/go-ipfs-cmds@v0.6.0/command.go:335 +0x565
github.com/ipfs/go-ipfs-cmds/http.parseRequest(0xc01097a400, 0x2c20040)
	github.com/ipfs/go-ipfs-cmds@v0.6.0/http/parse.go:174 +0x1271
github.com/ipfs/go-ipfs-cmds/http.(*handler).ServeHTTP(0xc001959700, {0x82d1b02f0, 0xc010580280}, 0xc01097a400)
	github.com/ipfs/go-ipfs-cmds@v0.6.0/http/handler.go:150 +0x38b
github.com/ipfs/go-ipfs-cmds/http.prefixHandler.ServeHTTP({{0xcb13ac, 0x7}, {0x1099620, 0xc001959700}}, {0x82d1b02f0, 0xc010580280}, 0xc01097a400)
	github.com/ipfs/go-ipfs-cmds@v0.6.0/http/apiprefix.go:24 +0x139
github.com/rs/cors.(*Cors).Handler.func1({0x82d1b02f0, 0xc010580280}, 0xc01097a400)
	github.com/rs/cors@v1.7.0/cors.go:219 +0x22b
net/http.HandlerFunc.ServeHTTP(0xc001959740, {0x82d1b02f0, 0xc010580280}, 0xc01097a400)
	net/http/server.go:2046 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0010c3700, {0x82d1b02f0, 0xc010580280}, 0xc01097a400)
	net/http/server.go:2424 +0x1b1
github.com/ipfs/go-ipfs/core/corehttp.CheckVersionOption.func1.1({0x82d1b02f0, 0xc010580280}, 0xc01097a400)
	github.com/ipfs/go-ipfs/core/corehttp/commands.go:184 +0x376
net/http.HandlerFunc.ServeHTTP(0xc0019596a0, {0x82d1b02f0, 0xc010580280}, 0xc01097a400)
	net/http/server.go:2046 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0010c3640, {0x82d1b02f0, 0xc010580280}, 0xc01097a400)
	net/http/server.go:2424 +0x1b1
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1({0x82d1b02f0, 0xc010580230}, 0xc01097a400)
	github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:198 +0xe4
net/http.HandlerFunc.ServeHTTP(0xc0010d71d0, {0x82d1b02f0, 0xc010580230}, 0xc01097a400)
	net/http/server.go:2046 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerRequestSize.func2({0x82d1b02f0, 0xc010580230}, 0xc01097a400)
	github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:172 +0x73
net/http.HandlerFunc.ServeHTTP(0xc0010d72f0, {0x82d1b02f0, 0xc010580230}, 0xc01097a400)
	net/http/server.go:2046 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x82d1b02f0, 0xc010580230}, 0xc01097a400)
	github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:76 +0xb2
net/http.HandlerFunc.ServeHTTP(0xc0010d7410, {0x82d1b02f0, 0xc010580230}, 0xc01097a400)
	net/http/server.go:2046 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x10af438, 0xc00a60c620}, 0xc01097a400)
	github.com/prometheus/client_golang@v1.10.0/prometheus/promhttp/instrument_server.go:101 +0xd7
net/http.HandlerFunc.ServeHTTP(0xc0010d75f0, {0x10af438, 0xc00a60c620}, 0xc01097a400)
	net/http/server.go:2046 +0x44
net/http.(*ServeMux).ServeHTTP(0xc001156040, {0x10af438, 0xc00a60c620}, 0xc01097a400)
	net/http/server.go:2424 +0x1b1
github.com/ipfs/go-ipfs/core/corehttp.makeHandler.func1({0x10af438, 0xc00a60c620}, 0xc01097a400)
	github.com/ipfs/go-ipfs/core/corehttp/corehttp.go:54 +0x93
net/http.HandlerFunc.ServeHTTP(0xc00020bbe0, {0x10af438, 0xc00a60c620}, 0xc01097a400)
	net/http/server.go:2046 +0x44
net/http.serverHandler.ServeHTTP({0xc0010c82a0}, {0x10af438, 0xc00a60c620}, 0xc01097a400)
	net/http/server.go:2878 +0x482
net/http.(*conn).serve(0xc0083519a0, {0x10c0bc0, 0xc0010d7ce0})
	net/http/server.go:1929 +0xd55
created by net/http.(*Server).Serve
	net/http/server.go:3033 +0x545
```

**Comment by aschmahmann** [comment]
@feld can you try this with go-ipfs v0.12.0-rc1 and see if it is still present?
